### PR TITLE
Update EIP-1: Allow links to the Yellow Paper

### PR DESCRIPTION
**Pull request by SamWilsn**
Split off from https://github.com/ethereum/EIPs/pull/6306

### CODE REVIEW

**Comment by lightclient** [comment]
I'm strongly against adding the yellow paper preemptively (as discussed on EIPIP). I would like to see something which is not / cannot be expressed in the execution specs, but is expressed in the yellow paper.

In my eyes, the yellow paper is a deprecated resource.

**Comment by xinbenlv** [comment]
I support allowing linking to Yellow Paper

**Review by Pandapip1 — APPROVED** [review]
This meets the requirements set out by EIP-5757, although since @lightclient is our resident Core dev expert and he suggests it's deprecated as a source, I recommend that all links to it have a warning EIPW annotation attached to them.

FWIW I would love to see the yellow paper updated. I might take that on as a project some time.

**Comment by SamWilsn** [comment]
Closed in favour of #7884

**Pull request closed without merging**
