### PR TITLE
Update EIP-6404: Move to Draft

### PR DESCRIPTION
**Pull request by etan-status**
EIP-6493 mixes the introduction of SSZ transactions converted from RLP with native SSZ transactions, implying that the corresponding Receipt definition and engine API changes also must be part of EIP-6493.

Splitting the RLP converted transactions into the other SSZ transaction EIP-6404 achieves a clearer balance, and is also closer to practical implementation order where an EL initially may choose to support only RLP converted transactions before adding the native SSZ profiles.

### CODE REVIEW

**Comment by etan-status** [comment]
This one needs an editor approval because eip-6465 is stagnant, but has a link to a section of 6493 that has been moved to 6404. reactivating 6465 resolves this.

also planning to subsequently split the receipts stuff into 6466, so that 6493 can focus on its core purpose: defining the native ssz signature scheme. to avoid getting stuck waiting for approvals, also reactivating 6466 as part of this PR.

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by Mikhai56** [comment]
no artifacts found

**Comment by Mikhai56** [comment]
f3deac81cfe9806b5d742e37c0178801b73c040f

**Review by Mikhai56 — APPROVED** [review]

**Pull request merged**
