### PR TITLE
Update EIP-5656: Move to Review

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Review by xinbenlv — APPROVED** [review]
LGTM! 
Don't forget to clean up the linter error

**Comment by xinbenlv** [comment]
> To be fair this linter error makes little sense, as markdown renders properly on the website, and requiring extra empty lines feel weird. Will do nevertheless.

I agree very much with you that it doesn't make much sense to require extra empty lines,

Also I personally think it doesn't make too much sense to require committer to fix linter error (1) when the part of not touched is not even being changed in this commit, or (2) every-time the linter error comes from a change of editing policy(e.g. EIP->ERC), it could totally be batched before moving to last call.

**Comment by axic** [comment]
@g11tech @lightclient @Pandapip1 @SamWilsn can we move this to review?

**Review by g11tech — APPROVED** [review]
:+1:

**Pull request merged**
