### PR TITLE
Strip the list of chain ID's

### PR DESCRIPTION
**Pull request by ligi**
context: https://github.com/ethereum/EIPs/pull/1755#issuecomment-470863529 and #1703 

cc @nicksavers

### CODE REVIEW

**Comment by nicksavers** [comment]
Maybe a good idea to leave in mainnet and testnets like Morden and Ropsten.

**Comment by ligi** [comment]
yea - was also thinking about this when doing the change - but where to draw the line?-)

added a commit with a suggestion

**Comment by axic** [comment]
I think this was a bad idea 😢

**Comment by nicksavers** [comment]
We can change it back, but as you may have noticed, many networks are already on that list and this is theoretically endless. This is pushing that responsibility off the proposal. We can also update the link to a different or multiple registries if necessary.

**Pull request merged**
