### PR TITLE
adds "consensus level" tracking to EIP process

### PR DESCRIPTION
**Pull request by owocki**
As the Ethereum community moves from simply discussing technical EIPs to a wider universe of EIPS, there will inevitably be debate as to whether specific EIPs are good for Ethereum.

The community is currently not very good at measuring consensus for EIPs that have achieved other than 100% consensus.  This EIP aims to correct that by putting the onus on EIP authors to measure consensus across as broad a swath of the community as possible, and to enter that information into the EIP.

All new EIPs should now fill out the 'Consensus' field of the EIP template.  In said field, the EIP author should claim whether they have a majority, supermajority, or 99% consensus across different constituencies.  Authors are required to link to objective data which supports their claims.

As the old saying goes "If you can measure it you can manage it".  I believe that beginning to measure this signal will be an important step forward in Ethereum community's ability to self assemble.

### CODE REVIEW

**Comment by Arachnid** [comment]
The EIP process is a process for writing and hosting technical standards. Whether someone wants to implement those standards, or whether other people don't like them, is completely irrelevant to the EIP process.

The EIP process is *not* a political governance process. It does not decide what gets implemented or deployed.

We don't need to measure how many people agree with an EIP, because writing an EIP does not get your idea implemented in a hard fork. Client developers do that, and they do it separately from the EIP process.

**Comment by Arachnid** [comment]
In addition to my objections as to content, this is in the wrong format. If you want to propose a change to the EIPs process, you need to propose a change to EIP-1.

You can't amend the EIP process by writing a new EIP; doing so would lead to a nightmare where prospective EIP authors would need to read every single existing EIP in case they change the rules for writing new EIPs.

If you still want to pursue this, please open a new PR against EIP-1. I personally think this is a very bad idea, however.

**Comment by owocki** [comment]
> We don't need to measure how many people agree with an EIP, because writing an EIP does not get your idea implemented in a hard fork. Client developers do that, and they do it separately from the EIP process.

Thanks for candid feedback.  My perspective is that core developers seem to need additional signal to decide whether an EIP should go into their perspective clients.  I'd be curious if others share this perspective, and if so, would they support an augmentation to EIP 1, or something else.

> In addition to my objections as to content, this is in the wrong format. If you want to propose a change to the EIPs process, you need to propose a change to EIP-1.

OK Cool - If others think that that this is a good idea; I will follow that process.

**Comment by Arachnid** [comment]
> Thanks for candid feedback. My perspective is that core developers seem to need additional signal to decide whether an EIP should go into their perspective clients. I'd be curious if others share this perspective, and if so, would they support an augmentation to EIP 1, or something else.

That's fine, but that shouldn't be part of the EIP process, because it's not relevant to writing technical standards. I'd also argue that this is scoped to "changes", not EIPs. A decision people want to come to consensus on might involve multiple EIPs as a bundle, or might involve a change that isn't standardised in an EIP.

**Pull request closed without merging**
