### PR TITLE
Revert EIP-875 to draft

### PR DESCRIPTION
**Pull request by fulldecent**
Last call is long overdue

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 875 state from Last Call to Draft
 - EIP 875 requires approval from one of (a@colourful.land, @james-sangalli)

**Comment by fulldecent** [comment]
@nicksavers requesting merge please

**Comment by axic** [comment]
@fulldecent so the reason is that the author has not followed up asking for final, despite the deadline lapsing? I think that may be fair, would be nice codifying some rules around this.

@MicahZoltu @lightclient @Souptacular any opinions?

**Comment by MicahZoltu** [comment]
If we cannot get the authors to PR to final then I agree with moving to abandoned.  We should probably make sure we try to reach out via email and GitHub @mention before doing so though, in case they aren't subscribed to the discussion thread for some reason.

@James-Sangalli Are you interested in moving 875 to final, or have you abandoned the effort?

Does someone want to volunteer emailing Weiwu Zhang <a@colourful.land>, James Sangalli <j.l.sangalli@gmail.com>?

**Comment by James-Sangalli** [comment]
> If we cannot get the authors to PR to final then I agree with moving to abandoned. We should probably make sure we try to reach out via email and GitHub @mention before doing so though, in case they aren't subscribed to the discussion thread for some reason.
> 
> @James-Sangalli Are you interested in moving 875 to final, or have you abandoned the effort?
> 
> Does someone want to volunteer emailing Weiwu Zhang [a@colourful.land](mailto:a@colourful.land), James Sangalli [j.l.sangalli@gmail.com](mailto:j.l.sangalli@gmail.com)?

Hi @MicahZoltu, sorry for taking so long. Let's revert it to abandoned rather than draft. Thank you.

**Comment by axic** [comment]
Replaced by #2943, though @MicahZoltu could have just pushed to this PR.

**Comment by MicahZoltu** [comment]
Oh, good point.  I always forget that GitHub will (by default) let organization members mess with other people's forks.

**Pull request closed without merging**
