### PR TITLE
Update EIP-6315: Move to Review

### PR DESCRIPTION
**Pull request by Pandapip1**

### CODE REVIEW

**Review by SamWilsn — CHANGES_REQUESTED** [review]
The EIP is not complete, so shouldn't be moved to review.

**Comment by Pandapip1** [comment]
Are you talking about the Rationale? That's the only part that isn't completely done.

**Comment by Pandapip1** [comment]
It's no longer filled with a placeholder.

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Review by SamWilsn — COMMENTED** [review]
> the sender being extracted as defined in [ERC-2771](./eip-2771.md)

Does this include "The Recipient **MUST** check that it trusts the Forwarder to prevent it from extracting address data appended from an untrusted contract"? If so, what drops the requirement of trusted forwarders? If not, you should be more specific about how the extraction works / differs from ERC-2771.

**Comment by SamWilsn** [comment]
> Fixed with #6658

The bit I quoted was from that section, so I'm not sure this clears it up at all.

**Comment by Pandapip1** [comment]
Fixed with https://github.com/ethereum/EIPs/pull/6739

**Comment by Pandapip1** [comment]
> So, I hate to be that guy, but... how does this EIP work? I'm going through this on the EIP Office Hours and I just don't really get it 😅


Think poor man's address space extension, where each contract is in full control over its own space.

**Comment by Pandapip1** [comment]
I've done a rewrite: https://github.com/ethereum/EIPs/pull/7858

**Review by SamWilsn — APPROVED** [review]
Left a few technical comments on the discussion thread, but otherwise this looks good!

**Pull request merged**
