### PR TITLE
fix typo: "SELFEDESTRUCT" to "SELFDESTRUCT" for EIP-2929

### PR DESCRIPTION
**Pull request by VieYang**
EIP-2929: fix typo "SELFEDESTRUCT" to "SELFDESTRUCT"

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2929 requires approval from one of (@holiman, @vbuterin)

**Comment by MicahZoltu** [comment]
Since this is just a typo fix, going to merge without waiting for approval.

**Comment by VieYang** [comment]
hi @MicahZoltu , @vbuterin , the blog https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement/ still has this typo,  but I can't found where to submit issue for this, so can you help to fixed this typo in the blog. By the way, this typo has been broadcast all of the world.

**Comment by lightclient** [comment]
@VieYang, thank you. I pinged the author.

**Pull request merged**
