### PR TITLE
Add EIP: On-chain registration of chain identifiers

### PR DESCRIPTION
**Pull request by yuliyaalexiev**
This ERC proposes deriving chain identifiers by hashing their chain name (along with other relevant information) and using ENS to map chain names to these identifiers, replacing the centralized list currently maintained on GitHub.

### CODE REVIEW

**Comment by abcoathup** [comment]
@yuliyaalexiev ERCs should be created in the ERC repo: https://github.com/ethereum/ERCs

**Comment by yuliyaalexiev** [comment]
@abcoathup , can you please point me in the right direction of what I should name the initial file - I do not have an EIP or ERC number yet and are getting a failure on the file-name in CI in the new PR https://github.com/ethereum/ERCs/actions/runs/11246461426/job/31268323567?pr=669

**Comment by abcoathup** [comment]
> can you please point me in the right direction of what I should name the initial file

EIP/RIP/ERC numbers are assigned manually by editors and associates.  I generally assign most week days.  You can name the initial file anything until a number is assigned.

I just assigned a number: https://github.com/ethereum/ERCs/pull/669/files#r1792676163

This PR can now be closed.

**Comment by yuliyaalexiev** [comment]
moved to a new PR: https://github.com/ethereum/ERCs/pull/669

**Pull request closed without merging**
