### PR TITLE
Update EIP-2537: update precompile addresses to avoid collision with latest precompile set

### PR DESCRIPTION
**Pull request by ralexstokes**
puts 2537 precompiles after the latest mainnet precompiles in #4788

### CODE REVIEW

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by g11tech** [comment]
linter failure

**Review by jochem-brouwer — APPROVED** [review]
LGTM

**Review by xinbenlv — APPROVED** [review]
LGTM, 

Per https://github.com/ethereum/EIPs/issues/7198, we should let contributor submit without fixing the linter error of untouched lines except for moving status.

@ralexstokes it seems the EIPW errors now are all warnings. If you still have difficulty triggering eth-bot's action, try change click on this "Convert to draft"  (sorry if the "draft" here seems confusing with the `EIP status Draft`. They are two things.)

image

Then click on "Ready for Review" which might help re-trigger the eth-bot. (sorry if the "review" here seems confusing with the `EIP status Review`. They are two things.)

image

**Comment by ralexstokes** [comment]
at this point we just need @ineffectualproperty  or @shamatar to approve, I've also added myself as an author so I can update this EIP moving forward w/o needing to involve them

**Review by shamatar — APPROVED** [review]

**Pull request merged**
