### PR TITLE
EIP: Gas Abstraction

### PR DESCRIPTION
**Pull request by 3esmit**
## Simple Summary

Allow block validators to include account contract's gas abstract transactions. 

Softfork miners to accept other tokens as gas through [ERC-1077] meta-transactions. 

## Abstract

[ERC-1077] allows for users agreeing with gas relayers, but also for agreeing with next `block.coinbase`, this proposal suggests that the gas market, currently only in ether, becomes abstracted by allowing the validators of listening directly for those type of transactions.

## Motivation

There are ongoing efforts in creating parallel gas markets, while this should ideally be solved at root through the validators. With PoS, staking ETH would allow rewards in any ERC20 token staker chooses to accept.

## Specification

Block validators should listen to messages in the [ERC-1077] format with `_gasRelayer` set as `address(0)`, and while forging a block, test their event outcomes to see if it's valid within custom configs (min gas prices in USD).
Valid meta transactions should be included early as transactions from any address (`msg.sender` is not used) with gas price zero.
A separated whisper channel would be made for every different token, including ether as meta transaction. 
Validators choose the tokens they accept and a minimal value in USD for all of them. 

## Rationale

This change would become an effective way of creating an abstract gas market in top of ether, however with mining pools this will not have too much network effects. The network effects would be more evident as proof of stake would remove the need of mining pools. 

## Backwards Compatibility

Regular transactions are not affected. This provides additional feature that won't affect other parts of the system.

## Test Cases

TBD 

## Implementation

TBD

## Security Considerations

Potential risks on DoS should be mitigated by gas limit and adding bad contracts (infinite loops, always reverts out of gas) should be added to an ignore list.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

[ERC-1077]: https://eips.ethereum.org/EIPS/eip-1077

### CODE REVIEW

**Comment by 3esmit** [comment]
I am open to discussion on this soft fork, but EIP 2938 makes this not necessary anymore, as Account Abstraction can allow to play around with gas payment and validation rules, so AA can enable this without the need of this soft fork.

**Comment by 3esmit** [comment]
Maybe I should update it to use EIP 2938, but for that I need to see how AA will end up.

**Review by MicahZoltu — CHANGES_REQUESTED** [review]
This doesn't appear to be an actual standard, just a suggestion for miner behavior.  Such suggestions would be better suited as issues or pull requests against Ethereum clients.  There is no need to come to consensus on miner transaction selection algorithms, and already there is not consistency across clients.

If you do intend on having this be an actual change to consensus, then those changes need to be included in the specification section of the EIP very clearly.

**Comment by 3esmit** [comment]
This is a soft fork suggestion, and it was described as EIP because it's relation with Coinbase Calls (2474) and Gas Relay (1077).
Perhaps this all (2474, 1077 and 2473) should be inside the same EIP in order to achieve similar solution as EIP 2938.

These 3 EIPs can be adopted independently of each other, and that's why I chosen to separate them.

IF EIP 2938 gets merged, EIP 2474 will be abandoned and this EIP will be updated to take advantage of 2938 AA_TX_TYPE to make coinbase 1077 relayers.

**Comment by MicahZoltu** [comment]
This EIP, as currently written, is not a soft fork as there is are no new block validity rules.  Unless I'm misunderstanding something, all this EIP does is *suggest* a transaction selection strategy for miners.

I glanced over 1077 and it appears to also not be a consensus change as it is just introducing a new contract interface/design pattern.  2474 appears to be a consensus change, though I don't fully grok the purpose of that particular change, it sounds like it just wants to reduce the base gas cost of certain transactions?

I generally am against combining EIPs together that could be separate, and each of these can be separate.  This one in particular though doesn't need standardization which is why I am hesitant to merge it.  You could make a change to geth today that does this and deploy that version of Geth as a miner and it would mine valid blocks, and users would be able to use that version of Geth with no trouble trouble following the main Ethereum chain.

**Comment by 3esmit** [comment]
> no new block validity rules

Yes, I don't think there is any change on that. The only difference is that some gas price zero transactions would be included by coinbase because it is own interest, just like the incentive for regular ETH gas transactions, but block creator would also check for specific state change for eval if including a transaction is beneficial. 

I am open to suggestion on how I should move forwards this EIP, considering it will probably use EIP 2938.

**Comment by MicahZoltu** [comment]
I personally think the way to move forward with this idea is to just create a GitHub issue or PR against Geth or Nethermind or OpenEthereum repository.  They all have their own transaction selection strategy and while there are certainly similarities between them, they are not identical and any one of them could include this change without any of the others including it (which is why it doesn't need to be a standard, thus doesn't need to be an EIP).

**Comment by DGKSK8LIFE** [comment]
I personally agree with @3esmit here

**Pull request closed without merging**
