### PR TITLE
Update EIP-1: add external links for post-quantum algorithm implementations

### PR DESCRIPTION
**Pull request by eum602**
Hello, this PR proposes to add new PQClean implementations. The intention of this PR is to allow such references in new EIP proposals such as [Precompile Falcon512 generic verifier](https://github.com/ethereum/EIPs/pull/8190)

### CODE REVIEW

**Comment by SamWilsn** [comment]
I've created a "Call for Input" to collect input from EIP Editors: https://github.com/ethcatherders/EIPIP/issues/318

**Comment by SamWilsn** [comment]
It might be easier if you can provide a source with a DOI number (eg. [`10.1007/3-540-48071-4_1`](https://doi.org/10.1007/3-540-48071-4_1)). We allow any links that have DOIs without any special exceptions.

**Comment by eum602** [comment]
> It might be easier if you can provide a source with a DOI number (eg. [`10.1007/3-540-48071-4_1`](https://doi.org/10.1007/3-540-48071-4_1)). We allow any links that have DOIs without any special exceptions.

Thanks for pointing it out @SamWilsn .  I couldn't find a DOI for Falcon; since all information was originally published in the author's page  (https://falcon-sign.info/)  which is the main page that implementers refer to. There the key differentiator is the specification version (20211101) . For example that number is used in the [OpenQuantumSafe project](https://openquantumsafe.org/liboqs/algorithms/sig/falcon) to point the specification version they use. Just leaving this information to hopefully find a way to address the observation.

**Comment by SamWilsn** [comment]
Sorry for the runaround on this @eum602; thanks a ton for putting up with us!

You mentioned that you're going to copy the implementation into your assets directory instead, so I'm going to close this PR.

**Pull request closed without merging**
