### PR TITLE
Upgrade to https

### PR DESCRIPTION
**Pull request by fulldecent**
Update to https links where possible

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2028 is in state Final, not Draft or Last Call
 - EIP 1123 requires approval from one of (@djrtwo, @pipermerriam, @njgheorghita, @gnidan)
 - EIP 1829 requires approval from one of (recmo@0x.org)
 - EIP 2020 requires approval from one of (daniel@io.builders, julio@adhara.io, fer@io.builders)
 - EIP 205 requires approval from one of (nick@ethereum.org)
 - EIP 2098 requires approval from one of (nick@ethereum.org, @ricmoo)

**Comment by axic** [comment]
Wasn't this already merged under #2626?

**Comment by pipermerriam** [comment]
@axic it appears it was, yes.

**Comment by fulldecent** [comment]
This PR is more changes. I went through again.

**Comment by axic** [comment]
It somehow seems to be the same ones here. Can you do a merge from master?

I did one locally here and the diff is zero.

**Comment by fulldecent** [comment]
Closing in favor of --> https://github.com/ethereum/EIPs/pull/2639

**Comment by axic** [comment]
Could have just pushed it here :confused:

**Pull request closed without merging**
