### PR TITLE
Set Status of EIP-1066 to Last Call

### PR DESCRIPTION
**Pull request by expede**
Update EIP-1066 ("status codes") to last call for v1.0.0. This will still be open to further codes, but we are happy with this as a first version to be widely used.

(Also fix a typo 😅)

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1066 state from Draft to Last Call

**Comment by expede** [comment]
@Souptacular any idea why this isn't automerging? I _do_ want this in Last Call, and am listed as an author on the PR. Halp?

**Comment by Arachnid** [comment]
Last Calls aren't handled by the bot, they require editor intervention.

**Comment by expede** [comment]
Thanks for the merge, @Arachnid! 🎉🎉🎉

**Pull request merged**
