### PR TITLE
1679 propose 1965

### PR DESCRIPTION
**Pull request by wighawag**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1679 requires approval from one of (@5chdn, @axic)

**Comment by nicksavers** [comment]
You can point to the Draft EIP https://eips.ethereum.org/EIPS/eip-1965
Does this mean you can close https://github.com/ethereum/EIPs/pull/1959?

**Comment by wighawag** [comment]
Hi @nicksavers I would say it still depends on potential discussion. I would not close #1959 until on options is chosen.

**Comment by axic** [comment]
Also fixed the typo introduced in #1965 here.

**Comment by axic** [comment]
> I would not close #1959 until on options is chosen.

Currently it is not proposed for Istanbul though.

**Pull request merged**
