### PR TITLE
Update EIP-3525

### PR DESCRIPTION
**Pull request by stoneworld**
_getNewTokenId do not use the fromTokenId_  && when you call ERC721._burn(tokenId_) call ownerOf  can't get the valid tokenId Owner.

### CODE REVIEW

**Review by will-edge — CHANGES_REQUESTED** [review]
The correction for burn() method is good, and thanks for that. It is a typo when creating this this separate demo version for EIP proposal. We will later post a Readme document,  indicating that the code committed here is not a complete implementation for use in production, it is only for the purpose of demonstrating how to implement this EIP.

The parameter of _getNewTokenId is added deliberately, indicating that one should not assume that the generation of a new id only depends on the internal status of the contract, although the implementation in this version did not use this parameter.

**Comment by will-edge** [comment]
> The correction for burn() method is good, and thanks for that. It is a typo when creating this this separate demo version for EIP proposal. We will later post a Readme document, indicating that the code committed here is not a complete implementation for use in production, it is only for the purpose of demonstrating how to implement this EIP.
> 
> The parameter of _getNewTokenId is added deliberately, indicating that one should not assume that the generation of a new id only depends on the internal status of the contract, although the implementation in this version did not use this parameter.

Please remove the change to _getNewTokenId as explained above.

**Comment by stoneworld** [comment]
> 

Thanks for the explanation, it has been revised.

**Review by xinbenlv — DISMISSED** [review]

**Review by Pandapip1 — APPROVED** [review]
This is fine by me

**Review by will-edge — APPROVED** [review]
Thanks for the fix.

**Pull request merged**
