### PR TITLE
Added Ubiq chain ID's

### PR DESCRIPTION
**Pull request by erikrijn**
Added Ubiq mainnet and testnet chain ID's.

### CODE REVIEW

**Comment by TomaszWaszczyk** [comment]
What is the rationale of the PR?

**Comment by jyap808** [comment]
The rationale is to state what Chain ID’s are active and reserved to avoid collision

**Comment by eosclassicteam** [comment]
Can you add EOS Classic's chain id also?

| 20             | EOS Classic mainnet |
| 21             | EOS Classic testnet  |

**Comment by axic** [comment]
I am not familiar with Ubiq and EOS Classic, but if both use the same P2P protocol as Ethereum then it makes sense reserving the chain id's here so that no other potential network collides with them.

@vbuterin @Arachnid @nicksavers @gcolvin @Souptacular what do you think?

**Comment by axic** [comment]
@eosclassicteam please create a pull request adding your IDs.

**Pull request merged**
