### PR TITLE
Promote EIP to final

### PR DESCRIPTION
**Pull request by fulldecent**
Passed Last Call period without any changes

### CODE REVIEW

**Comment by fulldecent** [comment]
Requesting merge please @alita-moore

**Comment by alita-moore** [comment]
cc @MicahZoltu @lightclient

**Review by MicahZoltu — APPROVED** [review]

**Comment by alita-moore** [comment]
weird, @MicahZoltu should this have auto merged provided that you approved it?

**Comment by fulldecent** [comment]
Here is the relevant bot error message which as @alita-moore notes, is inaccurate:

> https://github.com/ethereum/EIPs/pull/3654/checks?check_run_id=3073655592#step:4:17

Requesting manual merge here please and then bot fixing where that happens.

**Comment by alita-moore** [comment]
okay I'll make a ticket to investigate what's going on here

**Comment by alita-moore** [comment]
@MicahZoltu this should be fixed now (both issues), you can see the code from the issue: https://github.com/alita-moore/PM/issues/6

**Pull request merged**
