### PR TITLE
Typos fixed in eip-1011

### PR DESCRIPTION
**Pull request by amiller**
fix "follow" -> "following"

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1011 requires approval from one of (@djrtwo, @chihchengliang)

**Comment by djrtwo** [comment]
I approve

**Comment by djrtwo** [comment]
If that doesn't cut it, I'll integrate it into an upcoming change

**Comment by Arachnid** [comment]
@djrtwo You need to go to the review page and submit a review with the 'approve' option.

**Comment by axic** [comment]
Is there any point waiting for the travis run to finish on a single typo change? (After the merge commit was done, it is clear it won't conflict)

**Pull request merged**
