### PR TITLE
Update EIP-2537: Sync gas meter with geth

### PR DESCRIPTION
**Pull request by hujw77**
I sync gas meter with geth at https://github.com/ethereum/go-ethereum/blob/e9f59b5d5ea44df607f826c72f42916b552ab33d/params/protocol_params.go#L153-L160

### CODE REVIEW

**Comment by g11tech** [comment]
for adding yourself to the authorlist will require approval from atleast one of the previous authors

**Comment by hujw77** [comment]
> for adding yourself to the authorlist will require approval from atleast one of the previous authors

Alex Vlasov (@shamatar), Kelly Olson (@ineffectualproperty), Alex Stokes (@ralexstokes)
I contribute for [EIP-2539](https://eips.ethereum.org/EIPS/eip-2539) and [EIP-3026](https://eips.ethereum.org/EIPS/eip-3026), Please give me a approval.

**Comment by mostafalarkii** [comment]
> I sync gas meter with geth at https://github.com/ethereum/go-ethereum/blob/e9f59b5d5ea44df607f826c72f42916b552ab33d/params/protocol_params.go#L153-L160

**Comment by hujw77** [comment]
@g11tech It seems that the authors of this eip don't care about this eip anymore. Pleaese take a review and add me to contribute this eip.

**Comment by ralexstokes** [comment]
hey @hujw77  thanks for this! I think I'm the only author actively maintaining this EIP and there are a number of things we may end up doing to prepare for Petra inclusion that may change the content quite a bit

let's just keep this PR for now and I'll keep it in mind as we refresh 2537 to get it ready for the next hard fork

**Comment by yperbasis** [comment]
geth uses an older gas schedule. See https://github.com/ethereum/EIPs/pull/3077

**Pull request closed without merging**
