### PR TITLE
Update EIP-2718: Add 155 to requires list

### PR DESCRIPTION
**Pull request by Pandapip1**
CC @MicahZoltu

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I think I would prefer to just delete line 18 instead.  It doesn't add significant value to understanding the EIP.

**Comment by MicahZoltu** [comment]
Alternatively, maybe just rewording it to something like,
> This was seen in previous proposals to create new types of transactions where some new value was bit-packed into one of the encoded fields.

**Comment by Pandapip1** [comment]
Actually, EIP-155 is implicitly mentioned on L35

**Comment by MicahZoltu** [comment]
Assuming we are talking about the same line 35, there is no implicit mention of EIP-155:
```
`LegacyTransaction` is `rlp([nonce, gasPrice, gasLimit, to, value, data, v, r, s])`
```
EIP-155 redefines how to interpret `v`, but it doesn't have any impact on how the transaction is encoded.

**Comment by Pandapip1** [comment]
> EIP-155 redefines how to interpret v, but it doesn't have any impact on how the transaction is encoded.

Fair enough.

**Pull request closed without merging**
