### PR TITLE
ERC-2309 Updating Username / Adding backwards compatibility

### PR DESCRIPTION
**Pull request by pizzarob**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2309 requires approval from one of (@pizza-r0b)

**Comment by pizzarob** [comment]
Hi @axic I updated my username from when I first creating this EIP. Can this be merged?

**Comment by su45fg** [comment]
[](url)https; //join.Skype.com/invite/it5VewCeJSBR

**Comment by su45fg** [comment]
I will get start working for etherscan. io Now

**Comment by su45fg** [comment]
How to work?

**Comment by su45fg** [comment]
OK show all chechs

**Comment by su45fg** [comment]
#1001

**Comment by su45fg** [comment]
### 

>   #@`_****_` #2717

**Comment by su45fg** [comment]
All chechs have passe

- This branch has no conflicts with the base branch

- checks have passed

**Comment by su45fg** [comment]
- 

1. 

- [ ] @eip-automerger

**Comment by su45fg** [comment]
Come back

**Pull request merged**
