### PR TITLE
EIP-2645 spelling fixes

### PR DESCRIPTION
**Pull request by 0xfawkes**
Fix a spelling error (protosals -> protocols) and remove trailing whitespace.

### CODE REVIEW

**Comment by chee-chyuan** [comment]
can you remove to Simple Summary and use the description in the header instead?

**Comment by MicahZoltu** [comment]
> can you remove to Simple Summary and use the description in the header instead?

This person is not the original author of the PR, so it isn't their responsibility to fix any inconsistencies it has with the standard format.  The author should, at some point, address this issue, but this PR isn't the right place to do it.

**Comment by chee-chyuan** [comment]
> > can you remove to Simple Summary and use the description in the header instead?
> 
> This person is not the original author of the PR, so it isn't their responsibility to fix any inconsistencies it has with the standard format. The author should, at some point, address this issue, but this PR isn't the right place to do it.

my bad

**Comment by axic** [comment]
Looks good to me, but would need feedback form @bbrandtom and @louisguthmannStarkWare.

**Review by bbrandtom — APPROVED** [review]
LGTM, thanks

**Review by axic — APPROVED** [review]

**Pull request merged**
