### PR TITLE
Add myself to editors

### PR DESCRIPTION
**Pull request by James-Sangalli**
Hi @Arachnid, I was there during your devcon panel whereby you mentioned that you would like more EIP editors to help out. 

Let me know if you need any further information before merging this PR.

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@Arachnid bump

**Comment by loredanacirstea** [comment]
@Arachnid , bump. You said there are no editor applications waiting - this is one. You also said:
 > If we had a list of would-be editors waiting, we'd add them now. https://github.com/ethereum/EIPs/pull/2166#issuecomment-508579095

@James-Sangalli do you still want to volunteer as an editor?

**Comment by Arachnid** [comment]
@James-Sangalli Sorry we never got to this. Please let us know if you're still interested in acting as an editor.

**Comment by James-Sangalli** [comment]
@loredanacirstea @Arachnid happy to help with some basic reviewing/merging of PRs. 

Are there any particular criteria that I need to understand before merging something? I am already aware that merging is not dependant on the soundness or utility of a PR, just that the review period and syntax requirements are fulfilled. 

In any case, PR merging can be reverted, so the damage potential is very limited.

**Comment by axic** [comment]
I think it would make sense laying out some rules regarding the selection process of editors and those rules should also apply to the current editors.

I personally have been reviewing EIPs by commenting and pinging people months before I was added as an editor. I was also pinging editors on https://gitter.im/ethereum/EIPs to merge PRs I thought were good. I would encourage everyone to start reviewing and pinging people, because that shows their genuine interest and helps them get familiar with the process and the rules set out by EIP-1.

**Comment by axic** [comment]
@James-Sangalli while on topic, could you please fix your EIPs to be according to EIP-1? https://github.com/ethereum/EIPs/issues/1386#issuecomment-495399645 raised that ERC-1386 doesn't have a copyright statement, but in fact it is missing every single section required by EIP-1.

**Pull request closed without merging**
