### PR TITLE
Update EIP-7514: Move to Final

### PR DESCRIPTION
**Pull request by dapplion**
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by poojaranjan** [comment]
Remove `Needs discussion` from "Security Considerations". 

Since the proposal has already been deployed, either add `None` or text if there are any considerations.

**Comment by timbeiko** [comment]
+1 @dapplion

**Comment by timbeiko** [comment]
@dapplion I opened this one instead 😄 https://github.com/ethereum/EIPs/pull/8345

**Comment by lightclient** [comment]
Done in #8345

**Pull request closed without merging**
