### PR TITLE
WIP: Decentralized Base Network Service

### PR DESCRIPTION
**Pull request by ongrid**
'umbrella' EIP for Decentralized Base Network Service

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I don't think there is much value in having an EIP that just describes a problem without a proposed solution.  Gravity also sucks, but without an alternative/solution to the problem discussing how much it sucks is just commiserating and not particularly productive.  In particular, while some kind of global mesh network would be cool, I don't see Ethereum (in its current phase of life) to be the source of creating some new global mesh network that replaces the internet.  99.999% (some large number of nines) of actors connect to peers via the existing Internet.  Even if we make it so Ethereum can peer via crossover cable or WiFi mesh networks, this will benefit hardly anyone pragmatically unless there is a plan in place to get the whole world (or some non-trivial portion of it) to adopt the proposed changes.  IPv6 is a _minor_ upgrade and it has taken decades to try to get a non-trivial portion of the world migrated to it.

My vote is to either provide some concrete solutions in this EIP or close it to reduce noise.  Note: I don't disagree with your arguments, just that they aren't particularly valuable without a solution that can realistically be launched (e.g., a solution that involves everyone launching a personal satellite into space isn't tenable).

**Comment by ongrid** [comment]
@MicahZoltu, thank you for your feedback. The described issues are fundamental as it looks for me, so I intentionally tried to focus reader's attention to the vulnerabilities itself and global impact on the platform, not solution. For last weeks I had several face-to-face discussions (including devp2p group, research room, ETH inspirers personally) and the most difficult was to describe what I mean under 'deanonymized', 'censored', 'insecure', 'disconnected' from the technical, network-related point of view. At the PhysTech standup meeting @vbuterin said that the submission of such EIP is the good point to start. Regarding solutions, I did my best to propose a rough plan in the draft. 

Before submission, I observed [EIP contribution rules](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md) - they look relaxed for 'Informational EIP' and allow just design issue description without any specific solution. In my case I believe EIP could be considered as 'Informational' with status 'Draft'. This would allow me to build community consensus around the idea and specify the detailed solution proposals incrementally.

* 'Even if we make it so Ethereum can peer via crossover cable or WiFi mesh networks' - the idea is to build framework for global routing, while the 'links' could be abstract, not just native physical spans. The links could be established and maintained by lots of technologies including dynamically-formed overlays over existing inetv4/v6. The ToR is a good illustration of the concept - to connect to the global ToR network you don't need to connect neighbor nodes physically - it's done over existing global IPv4/6. I'm not a ToR fan, so proposed design will be aligned for speed and routing efficiency.

* 'IPv6 is a minor upgrade and it has taken decades to try' - Perfect example, IPv6 looks pretty native for you as you consider it a minor upgrade, but implementation wasn't so trivial a decade ago (I'm personally one of the first adopters of v6 in high scale). The IPv6 technology is the illustration of iterative approach from the just problem statement (initial ideas for IPNG are from early 1990s), to the current standard track which is about tens of RFCs and hundreds of ietf-drafts. I believe it was absolutely impossible to specify the implementation in a single document first. Such things are mostly iterative (try/think/change/try) and this shouldn't be the problem for EIP submission, I believe.

* 'launching a personal satellite into space' - I think we should consider Ethereum node as strong analogue of 'personal satellite'. Several years ago nobody could imagine distributed network of PoW miner rigs over the world (look like 'personal banks' for me). I don't see much difference compared to the network of personally-owned routing nodes (motivated by financial reward for providing service). Larger or medium-size investors could theoretically find feasible to provide service over satellites - why not - such broadcasting looks as fantastic, but it's not a big deal really.

**Comment by ongrid** [comment]
@MicahZoltu I'm gonna to submit the first 'child' EIP which specifies the solution for the one of mentioned points - connectivity enhancement. I'd like to propose these changes first:
* bootnode MUST be IPv6 capable (go-ethereum bootnode doesn't support IPv6 now, doesn't know about IPv6 address/URI format and so on). 
* The bootstrap node should establish reverse connection to the peer to verify the node really available before advertising it to other peers (for both IPv4 and IPv6 to avoid advertising of NATed/firewalled endpoints)

Is this a proper way to move forward from abstraction to implementation? How can I refer the umbrella document from subordinate EIP? As EIP-Pull-Request-711 or my own repository?

**Comment by MicahZoltu** [comment]
If you think there is value in discussing first, then start with an issue.  If you believe you have a a full solution already figured out and want to submit it for feedback (which will of course include discussion), then start with a pull request (follow the EIP template).  While you can reference this GitHub issue, I think it would be better to have the new EIP be self contained and talk about the specific problems the EIP solves in the motivation section of the new EIP rather than depending on referencing this one.

**Comment by ongrid** [comment]
@MicahZoltu, so we're in the egg-and-chicken situation what goes the first - the EIP proposal or discussion on it. The pretty democratic EIP-1 👍 states the proposal should be initiated first, then it's discussed. Passing through EIP issue is specified for early-stage thoughts (to save time writing EIP, but currently it's already composed).

I'd like to highlight the backstory of this PR again - during the recent lecture at Moscow Institute of Physics and Technology (MIPT) several guys (I've never met them before) asked about transport-level issues and opportunities (about IoT peering, firewalls traversal and subscribers onboarding schemes). I asked @vbuterin especially regarding transport-level risks censorship, DoS- and Sybil- resistance and we agreed that such base-level vulnerabilities should be raised and discussed as detailed EIP describing the possible vectors, so I'm just following the agreement with him. I think going through additional 'EIP issue' step looks a bit redundant and bureaucratic - for now I've already passed a lot of stages of its discussion:
- in gitter rooms
- personnally with Vitalik
- personally with developers (from p2p)
- current Pull request discussion
- within the telco- and SDN-industries communities

Trust me, there is a much longer non-public discussion in Telco and Special-authorities regarding TLS, IPSeC VPN, ToR, bitcoin and now Ethereum censorship. Publishing attack vectors could be painful and unresolvable topic for Bitcoin, but for the Ethereum it looks a huge opportunity and competitive advantage to rethink the existing internet and make it more independent using smart contracts for global packet routing.

@cdetrio, @frozeman, @gavofyork, @Souptacular, @obscuren, @wanderer, @arachnid), @romanman, @vbuterin could you guys please consider adding this document in the repo as Informational, Draft EIP-711. Many thanks!

**Comment by Arachnid** [comment]
I'd support adding this to the repo as an informational EIP, but only at the same time as a standard EIP that references it as background.

**Comment by Arachnid** [comment]
This is a courtesy notice to let you know that the format for EIPs has been modified slightly. If you want your draft merged, you will need to make some small changes to how your EIP is formatted:

 - Frontmatter is now contained between lines with only a triple dash ('---')
 - Headers in the frontmatter are now lowercase.

If your PR is editing an existing EIP rather than creating a new one, this has already been done for you, and you need only rebase your PR.

In addition, a continuous build has been setup, which will check your PR against the rules for EIP formatting automatically once you update your PR. This build ensures all required headers are present, as well as performing a number of other checks.

Please rebase your PR against the latest master, and edit your PR to use the above format for frontmatter. For convenience, here's a sample header you can copy and adapt:

```
---
eip: <num>
title: <title>
author: <author>
type: [Standards Track|Informational|Meta]
category: [Core|Networking|Interface|ERC] (for type: Standards Track only)
status: Draft
created: <date>
---
```

**Pull request closed without merging**
