### PR TITLE
Add EIP: Clustered ERC-721

### PR DESCRIPTION
**Pull request by sullof**
This is a proposal for a clustered NFT able to manage unlimited sub collections.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

// Authors: Francesco Sullo <francesco@sullo.co>

/**
 * @title IERC7108
 * @dev This interface allows managing clusters or sub-collections of ERC721 tokens within a single contract
 */
interface IERC7108 {
  /**
   * @dev Emitted when a new cluster is added
   */
  event ClusterAdded(uint256 indexed clusterId, string name, string symbol, string baseTokenURI, uint256 size, address owner);

  /**
   * @dev Emitted when ownership of a cluster is transferred
      The interface does not specify functions to transfer the ownership of the cluster
      to leave the implementer full freedom about how to implement it, with the only
      requirement that a ClusterOwnershipTransferred event MUST be emitted if so
   */
  event ClusterOwnershipTransferred(uint256 indexed clusterId, address indexed newOwner);

  /**
   * @notice Gets the id of the cluster to which a token belongs
   * @param tokenId ID of the token
   * @return uint256 ID of the cluster to which the token belongs
   */
  function clusterOf(uint256 tokenId) external view returns (uint256);

  /**
   * @notice Gets the name of a cluster
   * @param clusterId ID of the cluster
   * @return string Name of the cluster
   */
  function nameOf(uint256 clusterId) external view returns (string memory);

  /**
   * @notice Gets the symbol of a cluster
   * @param clusterId ID of the cluster
   * @return string Symbol of the cluster
   */
  function symbolOf(uint256 clusterId) external view returns (string memory);

  /**
   * @notice Gets the range of token IDs that are included in a specific cluster
   * @param clusterId ID of the cluster
   * @return (uint256, uint256) Start and end of the token ID range
   */
  function rangeOf(uint256 clusterId) external view returns (uint256, uint256);

  /**
   * @notice Gets the owner of a cluster
   * @param clusterId ID of the cluster
   * @return address Owner of the cluster
   */
  function clusterOwner(uint256 clusterId) external view returns (address);

  /**
   * @notice Gets how many clusters have been added
   * @return uint256 Total number of clusters
   */
  function clustersCount() external view returns (uint256);

  /**
   * @notice Adds a new cluster
   * @dev The ClusterAdded event MUST be emitted upon successful execution
   * @param name Name of the cluster
   * @param symbol Symbol of the cluster
   * @param baseTokenURI Base Token URI of the cluster
   * @param size Size of the cluster (number of tokens)
   * @param clusterOwner Address of the cluster owner
   */
  function addCluster(
    string memory name,
    string memory symbol,
    string memory baseTokenURI,
    uint256 size,
    address clusterOwner
  ) external;

  /**
   * @notice Gets the normalized token ID for a token
   * @dev The normalized token ID is the token ID within the cluster, starting from 1
   * @param tokenId ID of the token
   * @return uint256 Normalized token ID
   */
  function normalizedTokenId(uint256 tokenId) external view returns (uint256);

}
```

### CODE REVIEW

**Comment by xinbenlv** [comment]
Thank you for the EIP. Please fix the linter errors and flip it back to ready to review

**Comment by sullof** [comment]
@xinbenlv I fixed all the issues.

**Review by jskelly84 — DISMISSED** [review]
Love it. Thank you

**Review by jskelly84 — DISMISSED** [review]
Good work

**Comment by sullof** [comment]
@jskelly84 You approved the changes, but I can't merge them. Is there any other step I should take?

**Comment by ekc9399** [comment]
> 您批准了更改，但我无法合并它们。我应该采取任何其他步骤吗？

100

**Comment by jskelly84** [comment]
Dude I'm lost and in dire need of calibration.

**Comment by ekc9399** [comment]
B

**Comment by ekc9399** [comment]
> The commit 03bf336c6abd367656fddbf7b214ea42132c6e2a (as a parent of fe561f4c4689a1cafb1b87daa33e55c3503de5c9) contains errors.
> Please inspect the [Run Summary](https://github.com/ethereum/EIPs/pull/7108/files) for details.
>

**Review by jskelly84 — APPROVED** [review]

**Review by jskelly84 — APPROVED** [review]

**Comment by sullof** [comment]
Is there any hope to have someone reviewing this proposal?

**Comment by sullof** [comment]
Since the community has not shown interest in this proposal, I am closing it to reduce the entropy of the repo

**Pull request closed without merging**
