### PR TITLE
EIP-3675 to Last Call

### PR DESCRIPTION
**Pull request by mkalinin**

### CODE REVIEW

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
CI errors need fixing.

**Comment by timbeiko** [comment]
@Pandapip1 is it possible to force-merge this? The CI is complaining of a circular dependency: it can't link 4399 because it's not in last call, and a similar issue happens when we want to move that EIP to last call (https://github.com/ethereum/EIPs/pull/5472). If we merge this, then 4399 should be unblocked.

**Comment by Pandapip1** [comment]
I'm okay with that. CC @SamWilsn for manual merge.

**Comment by mkalinin** [comment]
@Pandapip1 I hope this can be merged despite of the validator complaining that 4399 linked in one of the notes has inappropriate status. It is a circular dependency that should be manually resolved

**Comment by xinbenlv** [comment]
[editorial] this PR seems to me a high priority and urgent need of merge. Can someone in the timezone to help-out soon?
@lightclient  @SamWilsn @axic @gcolvin

**Review by Pandapip1 — APPROVED** [review]
@SamWilsn please manually merge

**Comment by xinbenlv** [comment]
Thank you @SamWilsn and @Pandapip1

**Pull request merged**
