### PR TITLE
Update EIP-1: Adds @xinbenlv as an EIP Editor

### PR DESCRIPTION
**Pull request by Pandapip1**
CC'ing all editors: @lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1

### CODE REVIEW

**Comment by xinbenlv** [comment]
Thanks for the invitation @Pandapip1 . 
I love to contribute to this group and am honored to be invited. I humbly accept the invitation if you and other editors also think my editorial contributions has been helpful than harmful.

Side note: your encouragement means a lot to me. I particularly admire this invitation from you because you and I usually hold very orthogonal views.

**Review by xinbenlv — APPROVED** [review]

**Comment by xinbenlv** [comment]
> Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):
> 
> ## (fail) .github/workflows/auto-review-bot.yml
> classification
> `ambiguous`
> * '.github/workflows/auto-review-bot.yml' must be in eip-###.md format; this error will be overwritten upon relevant editor approval

It seems the eip-bot says it has to be `eip-###.md format`, is this intended? @Pandapip1

**Comment by poojaranjan** [comment]
Having a good number of EIP Editors to review proposals  to bring the number of open pull requests under 10 is a dream that I hope will become true one day. 

This PR was brought up in EIPIP meeting 63, but we didn't get enough time to discuss. Though, this will be a decision of present EIP editors, I just want to share info documented in  [EIP editor “apprentice” handbook](https://hackmd.io/@poojaranjan/EIP-ERC-Editor-handbook) which is a collection of summary of decisions of past EIPIP meetings. 

As per [How can an apprentice make a request to be formally onboarded as an EIP editior?](https://hackmd.io/@poojaranjan/EIP-ERC-Editor-handbook#How-can-an-apprentice-make-a-request-to-be-formally-onboarded-as-an-EIP-editior), it appears to me that "tenure of active contribution" is an important criteria of consideration along with approval of present EIP Editors. 

> "The contribution of an apprentice will be monitored by all EIP editors during the internship period. After 6 months of reviewing the pull requests as apprentice, when the contributor feels comfortable enough with the process and would like to be added to the repository as an EIP editor, a pull request with [request to be listed as EIP editor](https://github.com/ethereum/EIPs/blob/master/.github/workflows/auto-merge-bot.yml#L20-L26) has to be made."

IMHO, EIP Editor is a responsible position and building community trust will be helpful with contributions made over a period of time. 

I see the mention of "internship duration" or "active contribution tenure" is missing in [EIP-5069: EIP Editor Handbook](https://eips.ethereum.org/EIPS/eip-5069#application-and-onboarding-process). Probably it can be updated, if we consider engagement time as a valid consideration.

**Comment by Pandapip1** [comment]
> engagement time as a valid consideration

@xinbenlv has been engaged for at least the past month. That's close to (if not quite) how long I was engaged before I became an editor.

**Comment by xinbenlv** [comment]
Thanks for the support @Pandapip1.

If it helps, my reviews can be found as: https://github.com/ethereum/EIPs/pulls?q=+reviewed-by%3AXinbenlv

**Comment by Pandapip1** [comment]
> If it helps, my reviews can be found as: https://github.com/ethereum/EIPs/pulls?q=+reviewed-by%3AXinbenlv

That will definitely be helpful!

**Comment by lightclient** [comment]
I would personally like to see a longer history of consistent contributions, before adding as an editor.

**Comment by Pandapip1** [comment]
> I would personally like to see a longer history of consistent contributions, before adding as an editor.

Fair enough. I'll leave this open for now. @xinbenlv, just keep doing what you're doing for now.

**Review by SamWilsn — APPROVED** [review]

**Comment by SamWilsn** [comment]
Greg and myself were on today's EIPIP call, and were in favour. Panda previously expressed a positive sentiment. I believe we now have sufficient evidence that @xinbenlv will be a solid contributor.

**Pull request merged**
