### PR TITLE
ERC-1155 status update to Last Call

### PR DESCRIPTION
**Pull request by coinfork**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1155 state from Draft to Last Call

**Comment by coinfork** [comment]
Hi @Arachnid - could you please help us with merging this status change to Last Call?

**Comment by fulldecent** [comment]
Please update the review end date when merging please. I’d like the full two weeks on this one. Good job on moving this along.

**Comment by coinfork** [comment]
@Arachnid @fulldecent added another implementation link along with some comment tweaks and updated the review date to Jan 3.

**Comment by fulldecent** [comment]
Note to self: discussions to: https://github.com/ethereum/EIPs/issues/1155

**Pull request merged**
