### PR TITLE
Update EIP-4824: Move to Review

### PR DESCRIPTION
**Pull request by thelastjosh**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by xinbenlv — COMMENTED** [review]
I couldn't comment on exact lines, hence the overall comment: can you move anything that are deemed reference implementations into its section rather than in the specification section?

**Comment by thelastjosh** [comment]
Hi @xinbenlv there are no reference implementations in the current specification; the solidity code gives the precise specification for the expected registration & indexing contracts on all EVM chains.

**Review by SamWilsn — COMMENTED** [review]
Couple things I can't comment directly on:

 - You have `IERC-4824` in your solidity block. I bet this was a find-and-replace error.
 - I'd recommend removing the `ERC-4824Registration` contract because it contains implementation details. EIPs shouldn't place any restrictions on the internals of implementations.
 - In fact, I'd suggest removing _all_ implementations outside the reference implementation for the same reason.

**Review by SamWilsn — COMMENTED** [review]
Still a few weirdly named identifiers (eg. `ERC-4824RegistrationSummoner`).

It looks like there's still a bunch of implementation code in the specification section (like `ERC-4824Registration`). If this isn't implementation, but something else, the preceding text needs to do a better job of introducing it as an example. If they are examples, they should be moved to the reference implementation section.

**Comment by SamWilsn** [comment]
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

**Pull request closed without merging**
