### PR TITLE
Added @seibelj as contributor to EIP-2981

### PR DESCRIPTION
**Pull request by seibelj**
@VexyCats, please add me as author. Thank you!

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2981 requires approval from one of (@jamesmorgan, @vexycats)

**Comment by VexyCats** [comment]
@MicahZoltu  whats the proper procedure here? Should @seibelj make a PR on my github for the EIP and then I merge that and make a PR myself? Or do you just approve this on your end?

**Comment by MicahZoltu** [comment]
@VexyCats You just need to do a GitHub review of this PR and choose "Approve" from the 3 options.

**Comment by seibelj** [comment]
I fixed the merge conflict @VexyCats

**Comment by seibelj** [comment]
this is superseded by https://github.com/ethereum/EIPs/pull/3407

**Pull request closed without merging**
