### PR TITLE
Update EIP-1380: fix typo in EIP 1380

### PR DESCRIPTION
**Pull request by WillXing**
fix typo in EIP 1380

### CODE REVIEW

**Review by g11tech — DISMISSED** [review]

**Comment by g11tech** [comment]
@WillXing there are some linter errors that would also need to be addressed

**Review by g11tech — DISMISSED** [review]

**Comment by WillXing** [comment]
@g11tech the failure in htmlproofer seems unrelated to this PR.

**Review by g11tech — APPROVED** [review]

**Comment by g11tech** [comment]
seems to require approval from original authors

**Review by alanaladd21 — APPROVED** [review]

**Comment by WillXing** [comment]
Can you kindly approve this PR please. @axic @jacqueswww

**Pull request merged**
