### PR TITLE
Update EIP-7691: Move to Review

### PR DESCRIPTION
**Pull request by timbeiko**
Currently blocking https://github.com/ethereum/EIPs/pull/9094

### CODE REVIEW

**Review by SamWilsn — CHANGES_REQUESTED** [review]
You'll want to replace the `<!-- todo -->` comments with the actual values before moving into Review.

**Comment by timbeiko** [comment]
@SamWilsn that comment was for the fork block, which we don't include until it gets set in ACD. Is the PR now OK to merge? Want to make sure we can properly reflect the Pectra scope in https://github.com/ethereum/EIPs/pull/9094

**Review by g11tech — DISMISSED** [review]
i think we need to have another tag to track things to be filled before moving to final 

may be <-- TBA --> or <-- TBF --> can be used to move to review

**Review by SamWilsn — DISMISSED** [review]

**Review by SamWilsn — APPROVED** [review]
I guess `PECTRA_FORK_EPOCH` can stay undefined :rofl:

**Pull request merged**
