### PR TITLE
Fix email formatting in EIP-2028

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2028 requires approval from one of (eli@starkware.co, @alexeyakhunov, tom@starkware.co, avihu@starkware.co)

**Comment by axic** [comment]
This fixes formatting on eips.ethereum.org and hopefully also fixes the review capability for the automerger. Merging this because I think it is not a material change against the author of the EIP.

**Comment by axic** [comment]
Actually, @TomStarkWare it seems the automerger didn't pick your Github username, because the email in the EIP is not linked to it (or perhaps the automerger is not sophisticated enough).

However, using your github username would allow you making changes to it without the need for an editor.

**Comment by TomStarkWare** [comment]
Yes, no problem, let's change to the github username

**Comment by axic** [comment]
Since you were able to approve it seems there's no need to change anything.

**Pull request merged**
