### PR TITLE
Update EIP-3475: Reference Implementation Typo Fixes

### PR DESCRIPTION
**Pull request by Pandapip1**
Fixes two typos found in the EIP-3475 reference implementation.

### CODE REVIEW

**Comment by SamWilsn** [comment]
The Specification section uses `_amount` in the `Redeem` event, so I'm inclined to not make this change.

**Comment by Pandapip1** [comment]
> The Specification section uses _amount in the Redeem event, so I'm inclined to not make this change.

Not sure what that has to do with the current change here - if anything, this fixes that.

> Also _amount is used in the Transaction struct in the Rationale section 🤷

Again, I'm pretty sure that you're confusing the lines that changed. This PR changes `amount` to `_amount`, not vice versa.

**Review by dr-chain — APPROVED** [review]

**Comment by dhruvmalik007** [comment]
https://github.com/ethereum/EIPs/pull/5547#issuecomment-1243238141

thanks for changing this and my bad that this issue got through the check,  it was named initially `amount` but we changed to the `_amount` just to differentiate it as the private variable..

**Comment by SamWilsn** [comment]
> Again, I'm pretty sure that you're confusing the lines that changed. This PR changes `amount` to `_amount`, not vice versa.

That's what I get for reviewing in the wee hours of the morning :rofl:

**Pull request merged**
