### PR TITLE
Add RFC3986(URI) to assets/RFCs

### PR DESCRIPTION
**Pull request by xinbenlv**
License: `Distribution of this memo is unlimited.`
This is a follow up of @Pandapip1 's proposal #5272 

Temporarily checking in the text version. Will update if the decision to include html as required format is made

### CODE REVIEW

**Comment by xinbenlv** [comment]
Bot assessment was not relevant. It seems only supporting EIP updates.

**Comment by MicahZoltu** [comment]
There was a desire to include the HTML version, rather than the TXT version I believe.

**Comment by xinbenlv** [comment]
> There was a desire to include the HTML version, rather than the TXT version I believe.

@MicahZoltu yes, acknowledged. I mention this in the body of PR per

> Temporarily checking in the text version. Will update if the decision to include html as required format is made

**Comment by Pandapip1** [comment]
The decision to use unmodified HTML was made.

**Comment by xinbenlv** [comment]
Done

**Comment by xinbenlv** [comment]
EIPW complains
```
- 'assets/RFCs/rfc3986.html' must be in eip-###.md format; this error will be overwritten upon relevant editor approval
```

Could one of the Editors give an overriding approval?

**Comment by Pandapip1** [comment]
No, not yet. The PR making the relevant change has not yet been merged.

**Comment by xinbenlv** [comment]
The depending https://github.com/ethereum/EIPs/pull/5272 is now merged. 
Please consider merging this PR

**Comment by xinbenlv** [comment]
Actually, this is no-longer needed.

**Pull request closed without merging**
