### PR TITLE
Update EIP-2535: fix typos (unnecessary/incorrect words)

### PR DESCRIPTION
**Pull request by mudgen**
Removed incorrect words that describe Loupe functions.

### CODE REVIEW

**Review by Pandapip1 — APPROVED** [review]
This does not functionally change the spec, so :+1: from me.

**Comment by mudgen** [comment]
> This does not functionally change the spec, so +1 from me.

Yes, correct.  Thanks.

**Comment by mudgen** [comment]
@SamWilsn Can you please merge this pull request?

**Comment by Pandapip1** [comment]
EIP Bot didn't trigger. Rerunning CI.

(Markdownlint is not a required check and does not automatically block PRs)

**Comment by mudgen** [comment]
> EIP Bot didn't trigger. Rerunning CI.
> 
> (Markdownlint is not a required check and does not automatically block PRs)

Okay,  the merge still failed.

**Pull request merged**
