### PR TITLE
Introduce eth_getBlockReceiptsByHash and eth_getBlockReceiptsByNumber JSON RPC methods

### PR DESCRIPTION
**Pull request by jakublipinski**
This proposal provides the clients with an ability to easily get the receipts for all the transactions from a particular block.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
You can fetch multiple receipts in a single call by batching requests (which I believe both Geth and Parity support).  There still may be value in this due to the way clients process batch requests, though it feels like they could just optimize for batched requests of this nature?

**Comment by jakublipinski** [comment]
As per @MicahZoltu answer and [my analysis](https://github.com/ethereum/web3.py/issues/832#issuecomment-412280055), it seems that batching is the way to go. Closing the PR.

**Comment by medvedev1088** [comment]
Linking these related pull requests and issues:
https://github.com/paritytech/parity-ethereum/issues/9075
https://github.com/ethereum/go-ethereum/issues/17044
https://github.com/paritytech/parity-ethereum/pull/9126

Even with JSON RPC batching, retrieving receipts is very slow. I guess the issue is that the raw block needs to be read from disk (not sure caching helps here) and parsed for every receipt in the batch. This adds significant overhead. 

In my tests, exporting 6k blocks with transactions takes 2 minutes. Exporting all the receipts from those blocks in batches of 100 takes 20 minutes.

**Comment by MicahZoltu** [comment]
My comment wasn't intended to suggest this isn't a good idea, just to provide a temporary workaround.  :)  I recently started doing some work that requires this functionality and fetching all of the receipts individually is painfully slow.  😢

**Comment by jakublipinski** [comment]
@MicahZoltu you may like [my comparison](https://github.com/ethereum/web3.py/issues/832#issuecomment-414591573). I'm happy to exchange experiences and ideas. I suffer from the same issue.

**Comment by tjayrush** [comment]
@jakublipinski and @micahZoltu For my (and other's) education, why exactly did you want to pull those receipts? What piece of data were you looking for exactly? I'm curious about the comment above about caching. With QuickBlocks, I've found significant performance speed-ups with caching depending on what exactly I'm looking for and how I cache the data.

**Comment by jakublipinski** [comment]
@tjayrush For each Ethereum address I want to know how many particular ERC20 tokens it owns. In order to do that, I scan all the receipts for each block and look for the [`Transfer` event](https://theethereum.wiki/w/index.php/ERC20_Token_Standard#The_ERC20_Token_Standard_Interface) there.

**Comment by medvedev1088** [comment]
@jakublipinski have you tried [eth_getfilterlogs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterlogs)? It's really fast. You can try this simple script that relies on eth_getFilterLogs to export all ERC20 transfers: https://github.com/medvedev1088/ethereum-etl#export_token_transferspy

**Comment by medvedev1088** [comment]
@tjayrush another piece of data I found useful in receipts is `gasUsed` (useful for gas analysis) and `contractAddress` (useful for extracting most of the contracts) fields.

**Comment by jakublipinski** [comment]
@medvedev1088 You made my day! I've just sped up my script 5x by using `eth_getFilterLogs` instead of async `get_TransactionReceipt. Thank you for your suggestion!

Do you have a suggestion on how to speed up querying the ERC20 tokens for the balance of a particular address? I currently asynchronously execute `eth_call` with `balanceOf(address)` as a parameter.

**Comment by medvedev1088** [comment]
One way of doing it is to dump the transfers to an SQL database then run a query to get all the balances. An example query is in this article https://medium.com/@medvedev1088/ethereum-blockchain-on-google-bigquery-283fb300f579 This approach works only for tokens that emit the Transfer event on everything that changes balance including token minting and burning. Can't think of anything else other than what you're doing.

**Pull request closed without merging**
