### PR TITLE
Update EIP-3076: Update eip-3076.md

### PR DESCRIPTION
**Pull request by nalepae**
Fix ordered list rendering issue

Adding blank line after `4. Refuse to sign...` to comply with the markdown linter seems to reset the HTML ordered list...
image

This PR removes the blank line. (The markdown linter will complain, but at least the HTML rendering will be OK.)

### CODE REVIEW

**Comment by SamWilsn** [comment]
If you indent the fenced code block, I think you can get it to be a part of the `<li>`. There's an [example in EIP-1](https://github.com/ethereum/EIPs/blob/082834fed2556b1eb83729d35c2ecb3c7926f243/EIPS/eip-1.md?plain=1#L371-L396).

**Review by michaelsproul — APPROVED** [review]
Let's try it

**Comment by michaelsproul** [comment]
Dang, it didn't work. Sorry, I didn't actually try compiling locally because I have 0 in the way of Ruby stuff installed.

Will re-visit in a bit unless you feel like tackling it @nalepae

**Comment by nalepae** [comment]
Actually I tried to build it locally but did not achieve to do it because Ruby stuffs seem to have trouble with Mac M1.
(Tried on docker as well but did not achieve as well.)

==> I'll build it on a linux machine today and will try to both have ordered list AND markdown linter to be happy.

**Comment by nalepae** [comment]
To reproduce the bug in local:

```
docker run -it ruby:2.6 bash
git clone https://github.com/ethereum/EIPs.git
cd EIPs
bundle install
bundle exec jekyll doctor
bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-opengraph --report-missing-names --log-level=:debug --assume-extension --empty-alt-ignore --timeframe=6w --disable-external
```

==> HTML file is here: `_site/EIPS/eip-3076.html`

Bug reproduced, let's fix it :)

**Pull request merged**
