### PR TITLE
Update EIP-7432: Move to Review

### PR DESCRIPTION
**Pull request by ernanirst**
We already have enough comments on Eth Magicians, and maturity of the interface to request review from the broader ethereum community. Looking forward for feedback!

### CODE REVIEW

**Review by ProphetZX — COMMENTED** [review]
@ernanirst and @karacurt:

Please be aware that this is definitely not a feature requested by the ethereum community, rather the opposite. Please ensure that you have the community’s backing, before you suggest such changes.

Kind regards

ProphetXZ

**Comment by ernanirst** [comment]
Hi @ProphetZX,

Have you checked the Eth Magicians post? You are not giving a lot of context over why this shouldn't be moving forward. but so far we received overwhelming support from other developers in the space.

**Review by SamWilsn — APPROVED** [review]

**Comment by ernanirst** [comment]
@ProphetZX you might be reading the wrong post. We have 10+ comments from 7 users

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 7432 state from Draft to Review

**Comment by weixiao-tiao** [comment]
> 

Yeah I have also seen this ERC and there has been discussion and questions around it on the FEM, you may raise your question and discuss with us there. It's not in final but in review state. And I think the author is welcome for feedback.

**Comment by Pandapip1** [comment]
Whether or not the feature is desired is not a consideration. What matters is a clearly-defined problem and an airtight solution that doesn't stray outside of its scope; this EIP has both. Let adoption dictate comnunity desires.

**Pull request merged**
