### PR TITLE
Update the link to the latest ERC20 from OpenZeppelin

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by axic** [comment]
I actually think hashes are better because they can't be changed. Tags can be changed the repository owners (deleting the tag and creating a new one pointing to a different hash).

**Comment by elopio** [comment]
That's a very good point @axic. I've replaced the tag with the commit hash.

**Comment by axic** [comment]
Ping @frozeman @vbuterin

**Comment by axic** [comment]
@nicksavers @Arachnid any ideas? Should this be merged?

**Comment by Arachnid** [comment]
We can't keep updating a finalized EIP every time a popular library updates its implementation of the EIP. We should either link to 'master', or remove it entirely.

**Comment by axic** [comment]
Having looked at the change, it updates the example from being compatible with Solidity 0.4.x to 0.5.x.

I think standards usually have to contain relevant links at the point of publication. Later maybe we can consider an addendum to EIPs, but I wouldn't consider this change crucial.

**Comment by elopio** [comment]
Fair enough. Maybe, we could post somewhere a list of EIPs implementations.
We can annotate each implementation with links to their audits (if any), to the list of users of each library in production, and some other information that might be relevant when choosing which implementation to import.

**Comment by axic** [comment]
@elopio are you still pursuing this? If not, please close the PR.

**Comment by elopio** [comment]
Hello @axic! I will close it. 
I think this list can grow to include EIP implementations: https://forum.openzeppelin.com/t/list-of-solidity-libraries-in-the-wild/2250

**Pull request closed without merging**
