### PR TITLE
Change EIP-2929 status from "Draft" to "Review"

### PR DESCRIPTION
**Pull request by poojaranjan**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 2929 state from Draft to Review
 - EIP 2929 requires approval from one of (@holiman, @vbuterin)

**Review by holiman — APPROVED** [review]
LGTM, thanks @poojaranjan !

**Comment by MicahZoltu** [comment]
Kicking this a few times.  @Arachnid claims that the bot failing to merge is a race condition, and I'm putting that to the test.

**Review by lightclient — APPROVED** [review]
Passing CI now, will merge.

**Pull request merged**
