### PR TITLE
Ping editors with write permissions when they are needed

### PR DESCRIPTION
**Pull request by Pandapip1**
CCs @MicahZoltu and @lightclient when a PR is in need of manual merging.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Those pings are meant for people who are actually working on the bot as sort of "unexpected error occurred, investigate and fix the bug".  They aren't meant for "needs manual merge".

**Comment by Pandapip1** [comment]
They do happen to coincide 100% of the time, however.

**Comment by MicahZoltu** [comment]
Only because the current maintainers are no longer maintaining, so bugs aren't getting fixed and we are manually overriding instead of fixing bot bugs.  😬 What *should* be happening is the maintainers get notified, they investigate while the PR is open, eventually fix the bug, and then the PR gets automerged correctly without Micah or Lightclient getting involved.

**Comment by Pandapip1** [comment]
> What should be happening is the maintainers get notified, they investigate while the PR is open, eventually fix the bug, and then the PR gets automerged correctly without Micah or Lightclient getting involved.

But that isn't what is happening.

**Comment by MicahZoltu** [comment]
> But that isn't what is happening.

Yeah, definitely, and we should fix that root problem rather than repurposing this mechanism for something else.  Currently, I *believe* I see/address every instance of these bugs happening so I don't think we are in dire need of a mechanism to further surface the problem.  Are you aware of a pattern of some of these slipping through the cracks and not getting caught at the moment?

**Comment by Pandapip1** [comment]
No.

**Pull request closed without merging**
