### PR TITLE
hard per-block cap in EIP1559

### PR DESCRIPTION
**Pull request by aliatiia**
This [recent FAQ](https://notes.ethereum.org/Wjr1SnW-QaST7phX9C5wkg?view) says the hard cap is 20M

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1559 requires approval from one of (@i-norden, @mslipper, @afdudley, @vbuterin, @econoar)

**Comment by i-norden** [comment]
Hey @aliatiia thanks for patching this. I think we should hold off on these changes until there is a decision on https://github.com/ethereum/EIPs/pull/2635

**Comment by i-norden** [comment]
Hi @aliatiia this change has been made unnecessary by #2654 so I think we can go ahead and close it

**Comment by axic** [comment]
The author of the EIP (@i-norden) indicated this is not needed anymore. @aliatiia if you think that is not true, please reopen the PR.

**Pull request closed without merging**
