### PR TITLE
Update EIP-5496: Move to review

### PR DESCRIPTION
**Pull request by wnft**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Please fix the codespell errors

**Comment by wnft** [comment]
Updated files for the codespell errors

**Review by Pandapip1 — APPROVED** [review]
LGTM :shipit:

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 5496 state from Draft to Review
 - File assets/eip-5496/test/test.js is not an EIP
 - File assets/eip-5496/test/testCloneable.js is not an EIP

**Pull request merged**
