### PR TITLE
Add EIP-1474 as a requirement to RPC ERCs

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1102 requires approval from one of (@bitpshr)
 - EIP 1186 requires approval from one of (simon.jentzsch@slock.it, christoph.jentzsch@slock.it)
 - EIP 1898 requires approval from one of (@charles-cooper)
 - EIP 234 requires approval from one of (@micahzoltu)
 - EIP 695 requires approval from one of (isaac.ardis@gmail.com, @tcz001, hi@that.world)
 - EIP 758 requires approval from one of (@tinybike)

**Comment by axic** [comment]
@bitpshr @CJentzsch @charles-cooper @MicahZoltu @tcz001 @sorpaas @tinybike can you please approve?

**Comment by MicahZoltu** [comment]
FYI: The markdown for https://eips.ethereum.org/EIPS/eip-1474 is broken at the bottom of the page, at least on Windows Firefox.  The little expanding sections of `Methods` section aren't working properly.

**Comment by axic** [comment]
@MicahZoltu I know, that is being addressed in #2059.

**Comment by axic** [comment]
@sorpaas it seems your email is not recognised, do you want to change ERC-695 to use your username?

**Comment by charles-cooper** [comment]
@axic I'm not really following the purpose of this PR. What does it mean for an EIP to depend on a later EIP?

**Comment by axic** [comment]
Please have a look at EIP-1474. It specifies the Ethereum JSON-RPC protocol. 

Your EIP-1898 extends the Ethereum JSON-RPC protocol, hence it makes sense to refer to the specification being extended/changed.

**Comment by axic** [comment]
@CJentzsch @simon-jentzsch can you please approve?

**Pull request merged**
