### PR TITLE
ERC-1376 Service-Friendly Token Standard

### PR DESCRIPTION
**Pull request by kumanoko24**
This is first PR for Service-Friendly Token Standard. Please check, thanks!

### CODE REVIEW

**Comment by kumanoko24** [comment]
Fixed header information from "Standard" to "Standards Track"

**Comment by kumanoko24** [comment]
The Travis always says:

```
Files found with invalid names:
+echo eip-service_friendly_token.md
```
But according to the eip-x.md, this file name should be valid

**Comment by kumanoko24** [comment]
Finally fixed the file name problems. Please check, thanks!

**Comment by Arachnid** [comment]
Please submit your PR as a new file, not as a change to eip-X.

**Comment by kumanoko24** [comment]
Re-submit done. Please check! Thanks

**Comment by axic** [comment]
Can you please rebase over `master`?

**Comment by axic** [comment]
Ping @kumanoko24

**Pull request closed without merging**
