### PR TITLE
Update EIP-6492: Move to Last Call

### PR DESCRIPTION
**Pull request by Ivshti**
* No further usable feedback has been provided since May ([see here](https://ethereum-magicians.org/t/eip-6492-signature-validation-for-pre-deploy-contracts/12903))
* It has been implemented in signature-validator, SIWE and others

### CODE REVIEW

**Comment by Ivshti** [comment]
closing due to #7284

**Comment by Ivshti** [comment]
oops, last call is still an ok status to make that change, hence reopening
@axic @SamWilsn @Pandapip1 @xinbenlv would appreciate if this gets merged :pray:

**Comment by Ivshti** [comment]
@axic @SamWilsn @Pandapip1 @xinbenlv would be great to get this merged

**Review by xinbenlv — APPROVED** [review]
Congrats on Move to Last Call

**Pull request merged**
