### PR TITLE
Add implementation section to EIP

### PR DESCRIPTION
**Pull request by atoulme**
Adding an implementation section to the EIP EIP-778, per request from @fulldecent:
https://github.com/ethereum/devp2p/issues/43#issuecomment-841483159

### CODE REVIEW

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - eip-778.md requires approval from one of (fjl)
 @fjl

**Comment by MicahZoltu** [comment]
Sorry for the confusion, but `Implementation` section is no longer part of the template and we (editors) generally recommend against external links like this as they are often not relevant to *future* readers.  Someone *should* fix

**Comment by atoulme** [comment]
OK, let me know - close this or rewrite with no links?

**Comment by MicahZoltu** [comment]
> OK, let me know - close this or rewrite with no links?

My recommendation is to close.  This isn't final because either no one has submitted a PR to move it to final or the authors haven't approved any such PRs.  This EIP doesn't align with our current policies, but it is "grandfathered in" due to its age (policies were different back when it was created).

**Comment by fulldecent** [comment]
I appreciate this, thank you￼

**Comment by lightclient** [comment]
Now that EIP-778 is final, I'm going to close this PR. Thanks.

**Pull request closed without merging**
