### PR TITLE
Update EIP-2135 DRAFT

### PR DESCRIPTION
**Pull request by xinbenlv**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by lightclient — CHANGES_REQUESTED** [review]
`Simple Summary` has been deprecated in favor of the `description` field in the preamble. Please update to this format.

`Reference` is also not a valid section per EIP-1. Please remove.

**Comment by xinbenlv** [comment]
Sstill working on this

**Comment by MicahZoltu** [comment]
Please address the feedback above so we can move forward with this.

**Comment by xinbenlv** [comment]
Yes, will do

**Comment by xinbenlv** [comment]
Still working on it

**Comment by xinbenlv** [comment]
Still working on it

**Comment by xinbenlv** [comment]
Still working on it

**Comment by xinbenlv** [comment]
WIP

**Comment by Pandapip1** [comment]
@xinbenlv I'm going to turn this PR into a draft.

**Comment by xinbenlv** [comment]
Agreed

**Comment by xinbenlv** [comment]
Closed in favor of #5693

**Pull request closed without merging**
