### PR TITLE
Fix typos in EIP 918

### PR DESCRIPTION
**Pull request by arosh**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 918 requires approval from one of (mgs33@cornell.edu, @jlogelin, admin@0xbitcoin.org)

**Comment by axic** [comment]
@jlogelin @0xbitcoin can you please review (and approve) this?

**Comment by jlogelin** [comment]
These look fine to me - thank you @arosh. @axic Is there an approval process to follow?

**Comment by axic** [comment]
@jlogelin I think if you do a github approve and @arosh clicks on the "update branch" button then it will be auto merged

**Pull request merged**
