### PR TITLE
EIP-1679: Add EIP-1344 as proposed to Istanbul

### PR DESCRIPTION
**Pull request by fubuloubu**
Fixes: #1935

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1679 requires approval from one of (@5chdn, @axic)

**Comment by bmann** [comment]
Changes got merged in, so you could potentially be the first one to propose @fubuloubu

**Comment by axic** [comment]
This needs to be rebased though.

**Comment by fubuloubu** [comment]
Hold on, there's something weird with an additional file that doesn't show up in my local branch...

**Comment by fubuloubu** [comment]
Okay, fixed it!

**Comment by fubuloubu** [comment]
@axic @bmann what is the next step for this process? Is there an ACD/other call scheduled that this proposed will be discussed for inclusion into Istanbul?

**Comment by bmann** [comment]
@fubuloubu you need to put on agenda for ACD if you want it approved. Go ahead and move forward with implementation and discussion now. 

Also, I am assuming you are the “champion” for this EIP? It’s a new term @axic came up with and we might amend EIP233 to include it. 

Means you are point of contact and are actively working on / PMing to get this in.

**Comment by fubuloubu** [comment]
@rmeissner and myself are both involved, but I suppose as the loudest mouth I am acting as "champion" for this proposal. I am certainly happy to fill that role.

It was discussed on https://github.com/ethereum/pm/issues/93#issuecomment-481010167 already, but I am unsure if that met the requirements of discussion for consideration into Istanbul. In any case, I don't think it's very clear when ACD discussion is required, or if something is successful coming out of the discussion. I would appreciate your guidance here.

For implementation, I have a branch for py-evm/trinity implemented [here](https://github.com/fubuloubu/py-evm/tree/eip1344-chain-id). Do I need to create implementations for geth/parity? Do I need to create a test case in the https://github.com/ethereum/tests repo? What are the requirements for acceptance into the hard fork EIP? EIP-233 only says that "[o]nce the EIP has been accepted by Core Devs, the EIP should be moved to the _Accepted_ EIPs section", which isn't terribly descriptive.

**Comment by bmann** [comment]
Let’s do this here https://ethereum-magicians.org/t/process-of-getting-eips-getting-accepted-into-a-hardfork/3191

**Pull request merged**
