### PR TITLE
Update eip-615.md

### PR DESCRIPTION
**Pull request by sriharikapu**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 615 requires approval from one of (@gcolvin)

**Comment by axic** [comment]
@gcolvin can you please review?

**Comment by axic** [comment]
@gcolvin @expede can you please review?

**Comment by expede** [comment]
This branch is out of date. I'm not listed as an author on this branch, having been added fairly recently.

**Comment by expede** [comment]
> on Oct 20, 2018

I actually think that these changes have been superceded by the current version 🤔 Most of these changes are on `master`, and have been updated further.

I recommend closing this PR without merging 🙅

**Comment by nicksavers** [comment]
Closing this since EIP-615 has had several similar updates since this PR was opened.
@sriharikapu If you feel like some of your suggested changes would still be useful, please open a new PR

**Pull request closed without merging**
