### PR TITLE
Update EIP-5252: Move to review

### PR DESCRIPTION
**Pull request by hskang9**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by hskang9** [comment]
@SamWilsn  could you approve eip again as I forgot to put review status in previous PR?

**Review by SamWilsn — COMMENTED** [review]
I'm not sure what the triple colon notation is, but it isn't supported by our markdown renderer.

**Comment by hskang9** [comment]
That was for centering text in pandoc markdown syntax.

**Comment by hskang9** [comment]
If I use <center> HTML, `eipw` flags it.

**Comment by SamWilsn** [comment]
> That was for centering text in pandoc markdown syntax.

Ah, okay!



> If I use `<center>` HTML, `eipw` flags it. @SamWilsn is it ok to add HTML?

We avoid HTML for the most part, although you _should_ be able to use `<center>`. The "Markdown Linter" check will complain about it, but it should still merge just fine. Again though, we'd prefer not using HTML at all.

**Comment by hskang9** [comment]
Ok I just added center html

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
