### PR TITLE
Minor proofreading of EIP-1559

### PR DESCRIPTION
**Pull request by lrettig**
Fix a couple of typos, make some language slightly clearer

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1559 requires approval from one of (@mslipper, @afdudley, @econoar, @i-norden, @abdelhamidbakhta, @vbuterin)

**Review by lightclient — APPROVED** [review]
Looks good to me.

**Review by MicahZoltu — APPROVED** [review]

**Comment by lightclient** [comment]
Bumping for approval from someone: @mslipper, @AFDudley, @econoar, @i-norden, @abdelhamidbakhta, @vbuterin.

**Review by abdelhamidbakhta — APPROVED** [review]
Looks good to me.

**Comment by MicahZoltu** [comment]
@lrettig Looks like you'll have to resolve some conflicts, unfortunately.

**Comment by lrettig** [comment]
Conflicts resolved

**Pull request merged**
