### PR TITLE
Update EIP-2537: Editorial updates eip-2537.md

### PR DESCRIPTION
**Pull request by GottfriedHerold**
Editorial updates, mostly.
The wording for (0,0) acting as encoding of the point at infinity was changed to saying that 0x000..0 encodes the point at infinity.

**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by ralexstokes — COMMENTED** [review]
thanks for taking a look! added a few more minor things on top, but then lets get this merged

**Comment by asanso** [comment]
lgtm @ralexstokes  let's merge ?

**Comment by ralexstokes** [comment]
@asanso ideally @GottfriedHerold can make the additional updates I suggested and then we can merge!

**Comment by GottfriedHerold** [comment]
> @asanso ideally @GottfriedHerold can make the additional updates I suggested and then we can merge!

included your changes.

**Review by asanso — APPROVED** [review]

**Pull request merged**
