### PR TITLE
Gemfile: add missing dependencies

### PR DESCRIPTION
**Pull request by pinkiebell**
This fixes some errors I encountered during running jekyll locally by following the steps in README.

### CODE REVIEW

**Comment by czhc** [comment]
@pinkiebell what version of ruby are you using?

**Comment by pinkiebell** [comment]
> @pinkiebell what version of ruby are you using?

`ruby 2.7.3p183 (2021-04-05 revision 6847ee089d)`

**Comment by czhc** [comment]
@pinkiebell thanks - i tried a clean install in ruby `2.7.3p183` as well and it seems to work fine without the dependencies added in this PR. e.g.

- webrick is included with [ruby 2.7 stdlib](https://ruby-doc.org/stdlib-2.7.3/), but there are issues for ruby 3.0 installs: https://github.com/jekyll/jekyll/issues/8523
- i'm not sure where the modules for `BigDecimal`, `JSON`, `Etc`. are invoked, so checking why they are added.

Do let me know if it is still not possible to install from scratch with `2.7.3` - happy to get into details

**Comment by pinkiebell** [comment]
> @pinkiebell thanks - i tried a clean install in ruby `2.7.3p183` as well and it seems to work fine without the dependencies added in this PR. e.g.
> 
> * webrick is included with [ruby 2.7 stdlib](https://ruby-doc.org/stdlib-2.7.3/), but there are issues for ruby 3.0 installs: [jekyll/jekyll#8523](https://github.com/jekyll/jekyll/issues/8523)
> * i'm not sure where the modules for `BigDecimal`, `JSON`, `Etc`. are invoked, so checking why they are added.
> 
> Do let me know if it is still not possible to install from scratch with `2.7.3` - happy to get into details

I used a temporary docker/alpine image and after installing ruby, bundler and deps I get the following:

```
/app # bundle exec jekyll serve
bundler: failed to load command: jekyll (/usr/bin/jekyll)
LoadError: cannot load such file -- json
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll.rb:29:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll.rb:29:in `<top (required)>'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/exe/jekyll:8:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/exe/jekyll:8:in `<top (required)>'
  /usr/bin/jekyll:23:in `load'
  /usr/bin/jekyll:23:in `<top (required)>'
```

**Pull request closed without merging**
