### PR TITLE
EIP-2657: Update OpenEthereum status

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Comment by su45fg** [comment]
What's link to the screen shot?
        Please. Help me.                                          
                             Thanks you

**Comment by lightclient** [comment]
@su45fg what screenshot?

**Comment by su45fg** [comment]
[](url)www. arcgis. com/apps/opsdashboard/index. html/85320e2ea5424dfaaa75ae62e5c06e61.               
      Dashboard :by my phone

**Comment by lightclient** [comment]
Thank you for sharing.

**Comment by MicahZoltu** [comment]
I'm not sure why CI is stuck on this.  I'm ready to merge it if CI ever gets unstuck.  Maybe I broke things by deleting the spam comments on this PR?

**Comment by MicahZoltu** [comment]
Kicking CI.

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2657 requires approval from one of (@madeoftin)

**Comment by MicahZoltu** [comment]
@MadeofTin Can you approve or deny this please?  You are the author of this EIP and the change is very small, should only take a minute.

**Pull request closed without merging**
