### PR TITLE
EIP-2341: Hardfork Meta: Kunming

### PR DESCRIPTION
**Pull request by sorpaas**
This protocol upgrade provides a backward compatibility foundation to
enable future protocol upgrades to be applied with significantly lower
chance of breaking existing contracts.

### CODE REVIEW

**Comment by sorpaas** [comment]
Note that I'm keeping the license currently as Apache-2.0, because IMO it's much better than public domain and offers patent protection for users. I'm okay to change this to public domain *if we agreed on the account versioning solution*.

**Comment by bobsummerwill** [comment]
Apache 2.0 is best, Wei.  Thumbs up.

**Comment by MicahZoltu** [comment]
CC0 is defacto standard license for all EIPs (it may also be an actual standard, but I'm not as confident in that).  If you don't like CC0, I recommend lobbying to get that defacto standard changed outside of this EIP.  As it is, I would lobby to block inclusion of this EIP due to the license since it feels like you are trying to bypass the proper process for "changing the rules" by authoring an otherwise good EIP that doesn't follow the standard.

**Comment by sorpaas** [comment]
As said before I have stopped "championing" account versioning for Ethereum. Most efforts, I believe, are now going on in Ethereum Classic. If you have been following along, this EIP is a copy of ECIP-1065 (https://ecips.ethereumclassic.org/ECIPs/ecip-1065).

I care about Ethereum community, but to say things straight, block inclusion of EIP due to nothing but "something is not licensed under CC0 but Apache2" does not affect me at all, and will only hurt Ethereum community. To say one or two things about politics, this actually gives Ethereum Classic a positional advantage because EIPs can be adopted as ECIPs, but it would be harder to do vice versa (you can relicense CC0 to Apache2 freely, but you cannot relicense Apache-2 to CC0).

You comment has made me think again of licensing any of the things I write as CC0 -- I'll probably just say no to any of the request for now.

**Comment by bobsummerwill** [comment]
I think your position is absolutely correct here, @sorpaas.
Much respect.

**Comment by bobsummerwill** [comment]
@MicahZoltu "since it feels like you are trying to bypass the proper process for "changing the rules"

No - what is actually happening (and the IP protection efforts which I am driving for ETC are the same) is that some of us are saying "We are not happy to participate within the EIP process any more while it has no IP protections".

ETC will set a higher bar, and as Wei says, is the Ethereum community who will suffer, because they will be unable to adopt ECIPs, which ETC will be able to adopt EIPs.

My ideal scenario sees the EIP process follow our lead and raise the bar there too.

The cynic side of my brain says that the Ethereum Core Developers and EIP editors neither understand the IP issues enough nor care enough to actually make that change.   Too bad.

@Souptacular, @MadeofTin and @chaals are all slated to attend a call this Friday 22nd with https://en.wikipedia.org/wiki/Mishi_Choudhary and maybe https://en.wikipedia.org/wiki/Eben_Moglen too, in which we can review both EIP and ECIP processes in terms of IP protections.

Specifically I want to validate my assumptions about my proposed "Apache 2.0 + DCOs" plan for ECIPs.  Which is very aligned with @sorpaas from what I can determine.

See also https://github.com/ethereumclassic/ECIPs/issues/165.

Simplest approach is Apache 2.0 for whole ECIP repo, plus DCOs (not real name) both retroactively and forward looking.   If we do that then we will need to get consent from all prior contributors.   We will have a process to go through, but that is my proposal.

**Pull request closed without merging**
