### PR TITLE
Update EIP-4907: Cleanup trailing whitespaces

### PR DESCRIPTION
**Pull request by TimDaub**
Hey,

when I tried using your implementation, my editor showed me lots of occurrences with trailing whitespace and I thought I'd fix it once and for all at the source. This doesn't really change any functionality so I hope it can get merged despite the standard being marked as final.

### CODE REVIEW

**Comment by Pandapip1** [comment]
You must make some sort of change to the EIP too so that the automerger bot can merge this.

**Comment by SamWilsn** [comment]
Since this is a final EIP, and some of the changes are more than just pure whitespace (changing quote style and adding parentheses), I am going to err on the side of caution and recommend that we don't apply these changes.

**Comment by Pandapip1** [comment]
I disagree. If it doesn't change anything functional, it's fine.

**Review by Pandapip1 — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]

**Comment by 0xanders** [comment]
Thank you  @TimDaub .

**Review by 0xanders — APPROVED** [review]

**Pull request merged**
