### PR TITLE
Update EIP-2315

### PR DESCRIPTION
**Pull request by gcolvin**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by Pandapip1** [comment]
@gcolvin I think you made this PR by mistake.

**Comment by gcolvin** [comment]
I was trying to create an empty directly waiting for an asset to be copied into it.

**Comment by gcolvin** [comment]
Now I find that the asset - an image of an old document - is being displayed by a PHP script that won't let me copy the image itself.  Unless I hack past that there will be no asset anyway.

**Comment by Pandapip1** [comment]
Take a trick out of the NFT book: screenshot it :)

**Comment by gcolvin** [comment]
I might - it's several pages, so a pain.  Probably not worth the bother.  If so I'll just close this.  What is the right way to add a new asset?

**Comment by Pandapip1** [comment]
Create a folder at `assets/eip-{number}/` and stick whatever in it

**Comment by MicahZoltu** [comment]
If you are using the GitHub web UI, I think you have to first create a text file of some kind at `assets/eip-{number}/whatever` to get the folder created, then you can upload a file into that folder.  You could, in theory, then go delete the text file.  Alternatively, you can clone the repository and use normal filesystem tools for creating a new folder.

**Comment by gcolvin** [comment]
Makes sense, thanks @MicahZoltu .  I've removed the offending URLs and retained only a proper citation to an academic journal as a source for the quote from Turing.  Satisfies the bot for now.

**Pull request closed without merging**
