### PR TITLE
Promote 2228 to Last Call

### PR DESCRIPTION
**Pull request by fulldecent**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I have asked the other editors to give their take on the Trademark section, which is really the only section that I have a problem with for the sake of merging this to Last Call.  Will update this PR once I get an answer (hopefully later today).

**Comment by fulldecent** [comment]
The trademark section has since been changed to limit the discussion to only points that an implementer will need to know.

Either way this is something that can be discussed in the Last Call status. Because the EIP will be fatally deficient if that section is removed.

I cannot in good conscience publish a paper that says "go do X" without also telling people "you are liable to get sued if you do X, by people that have standing, and who are telling you not to do X, and I know about it, and I am telling you a reasonable workaround to protect yourself."

**Comment by MicahZoltu** [comment]
The EIP editors discussed this and the weak consensus seems to be that the EIPs repository isn't the right place to discuss trademark/copyright claims.  I believe the trademark is owned solely so that it can be used to combat scammers (e.g., for YouTube video takedowns), and there isn't any meaningful expectation that people include the ®.

If you are uncomfortable being author on this PR, I'm sure someone else wouldn't mind replacing you as the Author so you can absolve yourself of responsibility on this front.

**Comment by fulldecent** [comment]
It is my understanding that the EIP editors do not speak for Ethereum Foundation.

So on what authority can you say "I believe the trademark is owned solely so that it can be used to combat scammers"?

The statement "you must not use [this mark] without the prior written permission of the Foundation" as published directly on the Foundation website must surely be more authoritative than your "I believe" statement.

If there is any confusion, this concern has a long-standing issue open at https://github.com/ethereum/ethereum-org/issues/841. The lack of any response there, and the published policy on the Foundation website can only lead us to know that this is in fact their policy. Pray tell how there can be any other interpretation?

---

If this EIP will be denied a broader community review (i.e. Last Call status) then please state the reason. In open source projects it is better to state reasons publicly rather than to only cite "discussion" with people that have (commit) power. Please state these plainly. And I volunteer to wordsmith these into EIP-1 proper as a PR.

At current, my plain interpretation of what is happening, and the PR I would make today would be:

> EIP-1
> ...
> ADD LINE:
>
> EIP editors speak for Ethereum Foundation and may interpret any of their policies, even in a manner directly contradicting to statements published by EF, and left unclarified for many years in open Issues, as justification to prevent wide community review of any EIP.

If this line sounds cynical, it is only showing my lack of understanding of your "discussions" above and my not knowing your thoughtful "pray tell" response above.

---

Regarding taking my paper, removing my name, weaponizing it to hurt people (i.e. removing the trademark note), and then publishing it. No I do not authorize that.

**Comment by fulldecent** [comment]
@lightclient If this EIP becomes final that means only that it is published and no changes will be expected.

There is no requirement for anybody to confirm to the specification. The Ethereum Foundation does not endorse that it is correct. And nobody is prevented from creating (and finalizing) a competing EIP that says the network with ID 1 and chainId 1 shall be named Snigglepucks. This is confirmed by the legendary "you should be allowed to publish an EIP on how to make a sandwich" statement I believe everyone is familiar with.

If people have not signed up for the RSS feed and are not watching the Last Call process then that's their fault. I stole the Last Call idea from the Swift Evolution process, brought it here, and believe it is a very reasonable process for the Ethereum community. I have studied many community consensus mechanisms and will be happy to recommend a new one if Last Call has outlived its usefulness. :-p

This EIP is informational. And it is written in a imperative tone. I advocate that all EIPs be written in a strong imperative tone to reduce confusion. There should be no confusion among two people on the matter of "does X PRODUCT support Y EIP" for any EIP.

Therefore I am requesting to have this EIP enter Last Call because:

1. It's crisp—Everyone knows what it means.
2. It's helpful—Without this document, people will make confusing and inconsistent products.
3. It's loving—I am taking the time to research and fight for the inclusion of some words that might really, really save somebody's day.
4. It doesn't matter—All EIPs that say a thing clearly can get published. This does say a thing. And nobody can be harmed.

---

Regarding the meta. No apologies! I am very happy to "derail" anything I am working on into a discussion of meta. Meta discussions are useless if you can't articulate a concrete thing they would effect. In law, this is sometimes called "closing a case because it is academic." So the fact that my issues (since ERC-721 on) are shaking the tree is an honor that I am getting to participate in the process, and that people like you take your time to show up and debate/learn/make consensus with me.

**Comment by MicahZoltu** [comment]
The question I'm struggling with in my head is: What if someone submitted an EIP that made copyright/trademark claims that were false.  As editors, I don't think it is our job to curate right/wrong legal claims, but at the same time it sure would be nice if stuff that was wrong didn't clutter up the EIPs repository.

If we think that wrong legal claims should be merged because we are not in the business of validating legal claims, then I think this EIP should be merged.

If we think that wrong legal claims should not be merged, then I think we should choose to simply avoid *any* legal claims in *any* EIP because we do not have the staff to evaluate them.

**Comment by fulldecent** [comment]
More generally, legal claims are claims in the same way that technical claims are claims.

For example, *reaching into the basked of https://eips.ethereum.org/all#last-call...*, EIP-191 [DRAFT] includes a Solidity example implementation.

Of course that standard doesn't mean anything if that example doesn't compile.

It is not reasonable that EIP editors will compile all code they see, verify all explicit claims, and then verify all logical conclusions of all explicit claims see to check for inconsistencies. Instead, we rely on the community to provide feedback, and the author on their honor should withdraw a paper which does stand against a fair argument of their peers.

The EIP editors is merely a referee here to ensure that protocol is followed. And they MAY also be a mentor, recognizing that many people publishing EIPs have zero experience with academic experience. And many barely have any experience with the content matter.

---

**SUMMARY**: EIP editors don't validate claims. Therefore any claims should be eligible to publish.

---

Separate thread: there may be an argument EIP-2228 does not make a legal claim. The wording in question is:

> it may be necessary for your application to

and

> For more information... see:

If that argument is accepted then it is possible to accept this EIP without rendering an opinion on the above (lol, is this the worst outcome?).

---

P.P.S. The example actually doesn't compile. It's my job as a reviewer (i.e. Last Call lurker) to find this stuff, I'll go leave a note on that.

**Comment by timbeiko** [comment]
FYI I've asked the EF legal team if they want to comment on this and they said that they might. It may be worth holding back merging 1-2 weeks to see if they do.

**Comment by fulldecent** [comment]
@timbeiko Thank you for reaching out. Very related topic requesting clarification of EF's position on its trademark usage is at https://github.com/ethereum/ethereum-org/issues/841. I wish those could be answered too.

---

Thank you, I am happy to sit on this another two weeks.

**Comment by lightclient** [comment]
@timbeiko any updates on this?

**Comment by timbeiko** [comment]
Just asked!

**Review by youtacrsbyvars — APPROVED** [review]

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - EIP 2228 state was changed from review to last call
 @fulldecent

**Comment by fulldecent** [comment]
It appears that EF legal will not be responding any time soon.

---

This PR does not make any commitments on behalf of EF and it merely points to publicly available information that is relevant to people that want to make an implementation.

Therefore I respectfully request that this PR be MERGED with no further contingency.

**Comment by MicahZoltu** [comment]
Merging because I have decided that it isn't my place to gauge the accuracy of information included in an EIP.  If the information here is wrong, that is OK as far as editing matters are concerned.

**Pull request merged**
