### PR TITLE
Updates EIP-5573: Reflect changes in CACAO and UCAN specs

### PR DESCRIPTION
**Pull request by skgbafa**
This PR updates EIP-5573 to enable easier integration with CACAO and UCAN by:
- replacing the `tar` and `ext` fields with `att` and `prf`
  - `att` containing URIs as keys and objects as values
    - each of these objects contains `<namespace>/<name>` ability strings as keys and an array of note-bene/restriction objects as values
      - ability strings are restricted to alphanumeric characters + `.+*-_`
    - note-bene objects can contain any JSON
  - `prf` containing an array of CIDs representing prior authorisations
- requiring maps within the `recap-object` to have lexicographically ordered keys
- updating the statement generation to segregate by resource and namespace
- requiring that there be only one `recap-uri` per SIWE message that must appear as the final entry in the resource list
- removing the namespace from the `recap-uri`

By matching the `recap-object` to the `att` and `prf` structure of ucan/cacao, interoperability between them becomes possible by treating a SIWE-recap as just one way of representing the same information, for signature verification purposes.

### CODE REVIEW

**Review by awoie — DISMISSED** [review]
thanks, lgtm!

**Review by Pandapip1 — DISMISSED** [review]
Fix the walidator issues.

**Comment by awoie** [comment]
@Pandapip1 I believe walidator issues have been fixed. Please approve.

**Comment by obstropolos** [comment]
> Fix the walidator issues.

Noting completion here, thanks @chunningham / @skgbafa !

**Pull request merged**
