### PR TITLE
EIP4907: Change Status to Final

### PR DESCRIPTION
**Pull request by emojidao**
EIP4907: Change Status to Final

### CODE REVIEW

**Review by 0xanders — APPROVED** [review]

**Comment by MicahZoltu** [comment]
I'm not a fan of including non-CC0 code in this repository (the LICENSE in the root says CC0).  Are you the author/owner of that code and if so, are you willing to release it as CC0 instead of MIT licensed?

**Comment by 0xanders** [comment]
> I'm not a fan of including non-CC0 code in this repository (the LICENSE in the root says CC0). Are you the author/owner of that code and if so, are you willing to release it as CC0 instead of MIT licensed?

Yes, I am the author of the code, I am willing to release it as CCO.

**Comment by Pandapip1** [comment]
> Yes, I am the author of the code, I am willing to release it as CC0.

**Comment by 0xanders** [comment]
> > Yes, I am the author of the code, I am willing to release it as CC0.
> 
> Would you mind adding an SPDX identifier then?

Thanks for reminding, the LICENSE has been changed to CC0.

**Comment by Pandapip1** [comment]
> Thanks for reminding, the LICENSE has been changed to CC0.

The correct SPDX identifier is actually `CC0-1.0`. Sorry for the confusion!

**Review by SamWilsn — COMMENTED** [review]
`package.json` still uses the `ISC` license. Best to clean that up to avoid any issues.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
On line 16 of `EIPS/eip-4907.md`, `ERC-721` should be replaced with `[EIP-721](./eip-721.md)`
On line 75 of `EIPS/eip-4907.md`, I would recommend putting a colon at the end of the sentence.

**Comment by Noosom** [comment]
> On line 16 of `EIPS/eip-4907.md`, `ERC-721` should be replaced with `[EIP-721](./eip-721.md)` On line 75 of `EIPS/eip-4907.md`, I would recommend putting a colon at the end of the sentence.

**Review by JESSENIA1983 — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]
LGTM!

**Pull request merged**
