### PR TITLE
Update EIP-1767: Move to Draft

### PR DESCRIPTION
**Pull request by xinbenlv**
Resume the ERC-1767 drafting. Context: https://x.com/nicksdjohnson/status/1705476652124217748?s=20

### CODE REVIEW

**Comment by lightclient** [comment]
We don't track the API changes by the EIP anymore and so this is now out-of-date. You can see the latest here: https://github.com/ethereum/execution-apis/blob/main/graphql.json

**Comment by xinbenlv** [comment]
Thank! In that case, what's the best way to propose change for API?

**Comment by lightclient** [comment]
I would make a PR to `execution-apis`. Here is a document outlining the process: https://github.com/ethereum/execution-apis/blob/main/docs/making-changes.md

**Comment by xinbenlv** [comment]
Got it. 

- I checked the file for the right way to do it, it seems the last update was https://github.com/ethereum/execution-apis/pull/400/files#diff-a44507d2ad2482bb3ed863208b9e1e0393069edfdbd686593bac598901f36770R2169
which still cites an EIP (EIP-4895)?
- it seems EIP-1767 presents the rule change, and is being cited by https://geth.ethereum.org/docs/interacting-with-geth/rpc/graphql and a few other places which is why I was trying to move this to final to reflect the status, can we allow this EIP which is already adopted?
- At the end of the day, the current EIP-1 has still accept proposal about Interface, if the rule to propose change has recently it's been updated, and we don't want to finalize this EIP, maybe we shall update EIP-1 first?

**Comment by lightclient** [comment]
> which still cites an EIP (EIP-4895)?

it's just referring to the eip where withdrawals were introduced to the protocol, same is done for tx types

> can we allow this EIP which is already adopted?

What exactly do you want to allow? You're free to try to update this, bring it to final, etc. But it won't change the "spec" for graphql. A better use of time is probably removing references to this EIP wherever you see it.

> maybe we shall update EIP-1 first?

What would the update be? I'd rather go ahead and deprecate this category all together and note that we've moved to `execution-apis` for these types of things, as we're discussing in the other PR.

**Comment by xinbenlv** [comment]
Thanks for answering. Just to give a bit context: the reason that I am interested in help championing this EIP is because onto of that I like to further promote JSONRPC / GraphQL interface for native support of querying ERC-20 or ERC-721 transfer graph. In that direction, since it's not necessary that GraphQL interface provider needs to be EL clients, they could be pure indexer as well, I am wondering whether `execution-apis` is the best place for such proposal. 

For that EIP (JSONRPC/GraphQL for ERC-20/721 transfer graph) to move forward, it's easier if we have EIP-1767 finalized first and use it as a baseline and precedents to further propose

**Pull request closed without merging**
