### PR TITLE
Mark EIP5 as Superseded

### LINKED ISSUE #8: EIP 5: Gas costs for return values
## Proposal

Change memory gas costs for return values of a call to be applied depending on the size of the written memory area, not the reserved memory area.
## Current Situation

In a call, the caller has to provide an area where the returned data from a call is written to. Only reserving it already changes gas costs for memory.
## Advantage

This makes it possible to read a return value whose size is not known to the caller prior to the call: The caller just reserves a huge amount of memory.
## Possible Extension

The `CALL` opcode (and its friends) may even return the actual size of memory written to, so that the data can be used (e.g. forwarded) even if nothing is known about its structure.
## Implementation

The implementation might be a bit tricky: The `CALL` opcode has to be charged some gas upfront, then the call is performed without allocating memory for the return value. At the point, the return value is available, gas costs are computed and if some gas is still available, memory is allocated and written to.

### PR DESCRIPTION
**Pull request by axic**
Closes #8.

[EIP211](https://eips.ethereum.org/EIPS/eip-211) states "replaces: 5".

[EIP1](https://eips.ethereum.org/EIPS/eip-1) mandates:
> Superseded – An EIP which was previously final but is no longer considered state-of-the-art. Another EIP will be in Final status and reference the Superseded EIP.

### CODE REVIEW

**Comment by axic** [comment]
@Souptacular @Arachnid @nicksavers @gcolvin @cdetrio I think this makes sense, but it is the first example of applying these rules from EIP1.

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 5 state from Draft to Superseded
 - EIP 5 requires approval from one of (c@ethdev.com)

**Comment by MicahZoltu** [comment]
I thought there was discussion about getting rid of the Superseded state?  If you want a new EIP, publish a new EIP.  The old one is still a valid standard even if no one uses it anymore. e.g., HTTP 1 is still a valid standard even if virtually no one uses it and everyone uses HTTP 1.2.

**Comment by MicahZoltu** [comment]
Note, this does get into the conversation about "where do we document what any given Ethereum chain implements in terms of core protocols.  ETH and ETC implement a different set of EIPs, so I think putting this information in the EIP is the wrong place.  However, there _is_ value in making it easy for someone to identify what standards are implemented in any given chain.

**Comment by axic** [comment]
EIP5 was merged at the time processes were entirely different. I don't think it was well discussed or peer reviewed. I'm not sure what would be the benefit not superseding it.

**Comment by Souptacular** [comment]
I agree with @axic that at the time EIP5 was merged the processes were different and we need to make it known that it is superseded.

**Pull request merged**
