### PR TITLE
Update word choice

### PR DESCRIPTION
**Pull request by fulldecent**
++

### CODE REVIEW

**Comment by lightclient** [comment]
@fulldecent thoughts on `denylist` instead of `blocklist`?

**Comment by fulldecent** [comment]
Both are 100% fine. Probably blocklist is more popular lately. And that is not a definitive reason to choose one word over another.

**Comment by tjayrush** [comment]
`blockList` is a really bad choice in my opinion. It sounds pretty much like a list of `blocks`. `block` is already quite heavily laden with meaning, so I would suggest against piling on yet one more.

**Comment by fulldecent** [comment]
This PR is proposing "blocklist" as a normal English word which, along with allowlist, are trading to become words of the year.

"blockList" (with a capital "L") and `blocklist` (as the name of a variable) are not proposed.

---

And of course there is no discussion necessary to agree that "blacklist" is not a term we want to use to refer to contracts that are being "[refused] to serve transactions" and "malicious users in their system".

**Comment by tjayrush** [comment]
> And of course there is no discussion necessary to agree that "blacklist" is not a term we want to use to refer to contracts that are being "[refused] to serve transactions" and "malicious users in their system".

I agree with this, of course.

I was only suggesting that the word 'block' is already quite laden with meaning in a BLOCKchain, and perhaps adding additional connotations is ill-advised.

**Comment by fulldecent** [comment]
"Chain reaction" is also a term that includes the word "chain". This term could cause confusion in the context of blockchains. However, because "chain reaction" has such a well-known meaning in chemistry, everyone will immediately recognize this chemistry usage over any more specific context-dependent interpretation.

Likewise, "blocklist" is quickly being recognized to mean "a list of bad things". (And we are all certain that this momentum will continue.) If QuickBlocks or any other project is using a variable named `blockList` to refer to something other than "a list of bad things", then it would be prudent to rename _those_ cases to "listOfBlocks", "blockArray", "blocks" or similar.

And besides, the style guide written by the author of C++ [recommends against this usage](https://www.stroustrup.com/bs_faq2.html?#Hungarian) where the variable type (e.g. "list") is included in the variable name (e.g. `blockList`), this is called Hungarian notation.

**Comment by ricky-sb** [comment]
I propose `denylist`. `denylist` reduces the cognitive complexity in identifying the functionality.
- The antonym of `allow` is `deny` 
- `deny` has a single lexical category, and a single meaning, making it more explicit
- `block` has 2 lexical categories, and a total of 11 meanings (according to Google)

**Comment by lightclient** [comment]
I also prefer `denylist` to `blocklist`.

**Comment by axic** [comment]
@yoav-tabookey @drortirosh @forshtat can you approve?

**Comment by MicahZoltu** [comment]
To be clear (and hopefully unbiased) you can also deny.  As the authors of the spec you have deciding power over the chosen terminology.  Regardless of how you decide it would be nice to close out this PR one way or another.

**Comment by axic** [comment]
Yes, I meant to write "review", but got lazy.

**Pull request closed without merging**
