### PR TITLE
Website: fix index.html issues

### PR DESCRIPTION
**Pull request by Pandapip1**

### CODE REVIEW

**Review by SamWilsn — COMMENTED** [review]
Why are we changing the relative links? Aren't both styles equivalent?

Why are we changing the example EIPs?

**Comment by SamWilsn** [comment]
> > Why are we changing the relative links? Aren't both styles equivalent?
> 
> If index.html gets renamed or used as a template, then the links will break.

I believe that unless the first character is a slash, both `./index.html` and `index.html` are resolved relative to the current base URL. I could entirely be mistaken. I think [this](https://url.spec.whatwg.org/#relative-state) is the relevant section of the spec.

**Comment by Pandapip1** [comment]
>  resolved relative to the current base URL

That's the problem. If `index.html` gets copied to `foo.html`, then `foo.html` will need to change all its links, due to the way that jekyll paths work (`foo.html` -> `/foo`).

**Review by SamWilsn — APPROVED** [review]
:shrug:

**Pull request merged**
