### PR TITLE
feat: add eip-2233

### PR DESCRIPTION
**Pull request by falstack**
This pull request for EIP-2233 is still in the idea stage. I hope everyone can participate in the discussion.

### CODE REVIEW

**Comment by foxkites** [comment]
For the idea stage of an EIP, the EIP-1 guideline recommends creating a topic on the Ethereum Magician's Forum (https://ethereum-magicians.org/) or Ethereum Gitter chat rooms (https://gitter.im/ethereum/home) or the Ethereum subreddit (https://www.reddit.com/r/ethereum/), besides the issues section of this repository, to create community dialogue that can help improve the EIP (https://eips.ethereum.org/EIPS/eip-1). Adding more sections from the guidelines (eg Security Considerations, Reference Implementation, Copyright Waiver) can improve your chance of success as well.

**Comment by MicahZoltu** [comment]
Someone should submit a PR to EIP-1 that recommends all "Idea" phase discussions go into https://ethereum-magicians.org.  At the least, Gitter should be removed as that room was long ago deprecated.

**Comment by foxkites** [comment]
> Someone should submit a PR to EIP-1 that recommends all "Idea" phase discussions go into https://ethereum-magicians.org. At the least, Gitter should be removed as that room was long ago deprecated.

So the Ethereum Subreddit is not as active re EIPs either?

**Comment by falstack** [comment]
@MicahZoltu thanks ！

**Pull request closed without merging**
