### PR TITLE
Update EIP-6357: Move to Review

### PR DESCRIPTION
**Pull request by Pandapip1**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by SamWilsn — COMMENTED** [review]
Should the rationale be fleshed out?

**Comment by Pandapip1** [comment]
Fixed. https://github.com/ethereum/EIPs/pull/6655

**Comment by Pandapip1** [comment]
> The security considerations section is still "Needs discussion."

No it isn't. The branch isn't up-to-date.

**Comment by Pandapip1** [comment]
Fixed with https://github.com/ethereum/EIPs/pull/6738

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
