### PR TITLE
EIP-1559 Improves clarity on the new transaction format.

### PR DESCRIPTION
**Pull request by MicahZoltu**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1559 requires approval from one of (@i-norden, @mslipper, @afdudley, @vbuterin, @econoar)

**Comment by KaycoinsInc** [comment]
Very good, thanks.

**Comment by i-norden** [comment]
Looks good, should we go ahead and get rid of that 10 mil reference here?

**Comment by MicahZoltu** [comment]
@i-norden Yes we should fix the 10 million thing, but in a separate PR I think.  I don't know when I or someone else will get around to fixing the 10 million thing and I don't want to hold this PR up waiting for that.

**Pull request merged**
