### PR TITLE
Add an optional Reference section.

### PR DESCRIPTION
**Pull request by gcolvin**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by axic** [comment]
@alita-moore merging changes to this file should have the same rules as `eips/EIP-1.md`.

cc @MicahZoltu @lightclient

**Comment by axic** [comment]
Opened a PR to revert this change under #4725.

After that is merged, @gcolvin feel free to open this again as a **draft** so it is not auto-merged and it can be discussed.

**Comment by axic** [comment]
> file eip-template.md is not a valid filename, but this error has been ignored due to editor approvals

@alita-moore probably the issue was this assumed "auditor approval" given it was created by auditors

**Comment by alita-moore** [comment]
Ya that seems likely @axic but we do have filters in place for this. I'll address this. btw @poojaranjan if you create a GitHub group with the volunteer / future echo engineers I can cc them onto stuff like this. I can also add their names to the bot as maintainers so that they get notified if an error occurs.

**Comment by poojaranjan** [comment]
Thanks @alita-moore 
I will add the link to the ECH Engineering Discord for contributors to refer. But, it would be nice to have @mryalamanchi added as maintainer so he gets notified if an error occurs.

**Comment by alita-moore** [comment]
Got it, okay ya, I can add this feature as well (dynamic maintainers)

**Comment by gcolvin** [comment]
Thanks, @axic et al.  I was not intending for this to just merge without discussion and approval.

**Pull request merged**
