### PR TITLE
draft EIP for a DGCL compliant Token standard.

### PR DESCRIPTION
**Pull request by davesag**
An `ERC20` compatible Token that conforms to [Delaware State Senate, 149th General Assembly, Senate Bill No. 69: An act to Amend Title 8 of the Delaware Code Relating to the General Corporation Law](https://legis.delaware.gov/json/BillDetail/GenerateHtmlDocument?legislationId=25730&legislationTypeId=1&docTypeId=2&legislationName=SB69).

*updated*

After discussion with lawyers they have advised that the Token, with some minor alts, would be compatible with Delaware General Corporation Law (DGCL) and not just Regulation A+.  References to Reg A+ are therefore being removed.

### CODE REVIEW

**Comment by davesag** [comment]
Thanks @janning and @harrisonperl — I'll make some adjustments to the wording and re-push.

**Comment by davesag** [comment]
The [reference implementation](https://github.com/davesag/ERC884-reference-implementation) has been updated to suit the latest changes.

**Comment by Arachnid** [comment]
This is a courtesy notice to let you know that the format for EIPs has been modified slightly. If you want your draft merged, you will need to make some small changes to how your EIP is formatted:

 - Frontmatter is now contained between lines with only a triple dash ('---')
 - Headers in the frontmatter are now lowercase.

If your PR is editing an existing EIP rather than creating a new one, this has already been done for you, and you need only rebase your PR.

In addition, a continuous build has been setup, which will check your PR against the rules for EIP formatting automatically once you update your PR. This build ensures all required headers are present, as well as performing a number of other checks.

Please rebase your PR against the latest master, and edit your PR to use the above format for frontmatter. For convenience, here's a sample header you can copy and adapt:

```
---
eip: <num>
title: <title>
author: <author>
type: [Standards Track|Informational|Meta]
category: [Core|Networking|Interface|ERC] (for type: Standards Track only)
status: Draft
created: <date>
---
```

**Comment by Arachnid** [comment]
Is this ready to be merged as a draft?

**Comment by davesag** [comment]
@Arachnid I believe so, unless anyone has any strong objections

**Comment by jllaw** [comment]
Take a look at this article: https://www-forbes-com.cdn.ampproject.org/c/s/www.forbes.com/sites/andreatinianow/2018/07/04/tokenized-securities-are-not-secured-by-delaware-blockchain-amendments/amp/

**Comment by davesag** [comment]
@jllaw interesting article, thanks. I very deliberately chose to keep personally identifiable information off-chain due to

1. storage costs and consequent gas fees, and
2. privacy.

So the article is correct in that ERC-884 represents transfers rather than ownership specifically, though ownership by an Ethereum Address is covered of course.

The Delaware Amendments do not _require_ a blockchain, merely _allow_ a blockchain based solution.  So the article is a bit disingenuous there in my view.

In addition I never used the word 'authorized' (or for that matter 'authorised') anywhere in ERC-884 aside from to mention that "A traditional share registry is typically managed by a Transfer Agent who is authorised to maintain the register accurately, and to handle shareholder enquiries.". I certainly never claimed that "a certain tokenized share is “authorized” by the Delaware Blockchain Amendments" as the Forbes article states.

What is clear however is you can't have company shares partly covered by ERC-884, and partly not covered by ERC-884.  It's a one-in;all-in (1iAi) model. The article touches on this (and paints it as a negative) but really that's just commons sense in my opinion.

Cheers

Dave

**Comment by jllaw** [comment]
@davesag, thanks for the response. Do you mind posting it as a response to this [post](https://www.linkedin.com/groups/13589178/13589178-6420656697337094144) in the LinkedIn "Tokenization of Securities" group and the equivalent post in the Facebook "Tokenization" [group](https://www.facebook.com/groups/tokenization)?  Would be good for people to see your response to the article because you make very good points, and people in those groups are very interested in the tokenization of all securities, especially equity securities (which will mostly be DE based).

**Comment by davesag** [comment]
Sure. Will do. Actually am on holiday right now so will do it tomorrow.

**Comment by davesag** [comment]
@jllaw I've requested membership of the groups you suggested.

**Pull request merged**
