### PR TITLE
Generalize the language of ERC-5005 and remove external references.

### PR DESCRIPTION
**Pull request by auryn-macmillan**
This PR generalizes the language of ERC-5005 and removes external references to the Gnosis Safe and other DAO tools.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Something is wrong with this PR, perhaps you are working off of an old version of master or something?  There is already an EIP-5005, but this PR appears to be trying to create a new one.

**Comment by auryn-macmillan** [comment]
> Something is wrong with this PR, perhaps you are working off of an old version of master or something? There is already an EIP-5005, but this PR appears to be trying to create a new one.

Weird. Had to rebase my fork, should be resolved now, but the commit history in the PR makes it look like it does way more than it actually does. :sweat_smile:

**Comment by MicahZoltu** [comment]
CI Failure:
```
./EIPS/eip-5005.md:18: programable ==> programmable
```

**Comment by TimDaub** [comment]
@auryn-macmillan 

"EnabledModule(address module)" isn't defined as an event anywhere.

**Comment by auryn-macmillan** [comment]
Thanks for catching this, @TimDaub. I've created a [new PR](https://github.com/ethereum/EIPs/pull/5208) to add the events, since this one was already merged.

**Pull request merged**
