### PR TITLE
Mark EIP 627 final

### PR DESCRIPTION
**Pull request by atoulme**
EIP 627 has been effectively final for a bit. The status of Draft confuses people (including, maybe exclusively, me). Propose to move to Final.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 627 state from Draft to Final
 - EIP 627 requires approval from one of (gluk256@gmail.com)

**Comment by axic** [comment]
@gluk256 can you approve/decline this? Would it also make sense to include @gballet as a co-author to approve such changes?

**Comment by gballet** [comment]
@axic there is one last thing for me to finish before this can be marked as done.

**Comment by gballet** [comment]
this being said, if making me a co-author lets me approve changes to that EIP, then yes please.

**Comment by axic** [comment]
> this being said, if making me a co-author lets me approve changes to that EIP, then yes please.

It does.

@gballet The best way to achieve that without invoking the mighty EIP editors is by creating a new PR which adds you to the author list with your github username **and** getting @gluk256 to Github approve that PR :)

**Pull request merged**
