### PR TITLE
Update word choice

### PR DESCRIPTION
**Pull request by fulldecent**
++

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1462 requires approval from one of (mk@atlant.io, js@atlant.io)

**Comment by axic** [comment]
@xlab can you approve?

**Comment by xlab** [comment]
@axic I don't have that email anymore. Sorry.

**Comment by axic** [comment]
@xlab you could also reject this change, if you disagree.

If you are still pursuing the EIP, you can submit an EIP to change your email or add your github username. If you are not pursuing it anymore, perhaps marking it Abandoned would be appropriate.

**Review by xlab — APPROVED** [review]

**Comment by xlab** [comment]
@axic sorry for delay. I thought the email was required.

Let's not abandon the draft, but I approved your PR just now. Hope that helps.

**Comment by MicahZoltu** [comment]
@xlab Can you please update this line in this PR:
```
author: Maxim Kupriianov <mk@atlant.io>, Julian Svirsky <js@atlant.io>
```
to
```
author: Maxim Kupriianov (@xlab), Julian Svirsky <js@atlant.io>
```

That will make it so when you approve in the future, the bot will auto-merge.

**Pull request closed without merging**
