### PR TITLE
Update EIP-2294: Move to Review

### PR DESCRIPTION
**Pull request by xinbenlv**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by xinbenlv** [comment]
@Pandapip1 could you help approve the merge?

**Comment by xinbenlv** [comment]
It seems @Pandapip1 is overwhelmed capacity. Can any other editors approve the review. I think thid EIP is better to go Shanghai.

**Review by lightclient — COMMENTED** [review]
Please remove the mention of EIP-1344's discussion-to. Otherwise looks good to me.

**Comment by xinbenlv** [comment]
Thanks, @lightclient, removed mentioning of the discussion-to. This PR is ready for merge.

**Review by Pandapip1 — APPROVED** [review]

**Pull request merged**
