### PR TITLE
Remove old EIP-20 file

### PR DESCRIPTION
**Pull request by Pandapip1**
Bye!

### CODE REVIEW

**Comment by Pandapip1** [comment]
(I will need either @MicahZoltu or @lightclient to manually merge this once someone else approves)

**Comment by MicahZoltu** [comment]
We had this here so that people who had links to it would not get a 404.  We never decided on an EOL strategy at the time, so it has sat here ever since.  It is not clear to me what the right deprecation strategy is here, whether now or sometime in the future.

**Comment by Pandapip1** [comment]
Why not remove it then, and if people complain we re-add it?

**Comment by MicahZoltu** [comment]
I'm not against that strategy.  It *has* been quite a while since we renamed this EIP.  Would like to hear thoughts from other editors.

**Comment by Pandapip1** [comment]
Other Editor CC: @lightclient @axic @SamWilsn @gcolvin

**Comment by Pandapip1** [comment]
@MicahZoltu everyone was okay with removing this file. Please *manually* merge.

**Pull request merged**
