### PR TITLE
Revert "Update Stale Bot"

### PR DESCRIPTION
**Pull request by MicahZoltu**
Reverts ethereum/EIPs#5342
Reverting since the PR in question didn't go through the multi-editor approval process and contained functional changes.

### CODE REVIEW

**Comment by Pandapip1** [comment]
> Contained functional changes.

Which changes were those?

**Comment by Pandapip1** [comment]
> I think the cleanup PR (assuming it changes no behavior, just cleans stuff up) can be merged almost immediately

From #5342

**Comment by MicahZoltu** [comment]
It changed the number of days before the bot acts and the messages that are given to users.

I didn't mean to imply that I approved the PR in that comment, I just meant that we could probably go forward with 2 editor approval on a cleanup-only version of the PR (e.g., formatting, layout).

**Comment by Pandapip1** [comment]
> It changed the number of days before the bot acts

Did it? I thought I had made those changes in https://github.com/ethereum/EIPs/pull/5342/commits/2c6751b42d8337936f6dbd41757bf7dd3e94a836

> I just meant that we could probably go forward with 2 editor approval on a cleanup-only version of the PR

Oops. Sorry!

**Comment by MicahZoltu** [comment]
> Did it? I thought I had made those changes in [2c6751b](https://github.com/ethereum/EIPs/commit/2c6751b42d8337936f6dbd41757bf7dd3e94a836)

That doesn't appear to revert it to the original.  Check out the Files tab of your PR and/or the revert PR and notice the durations and text changed in the diff.

**Comment by Pandapip1** [comment]
> That doesn't appear to revert it to the original. Check out the Files tab of your PR and/or the revert PR and notice the durations and text changed in the diff.

You're right. My bad.

**Pull request merged**
