### PR TITLE
Unify author header values

### PR DESCRIPTION
**Pull request by ligi**
I am currently extending the DIP-Checker to also check EIPs and will submit a PR soon that adds it as a github action.
So far most things are very clean in here (so the github action will only replace the manual work of checking it for future PRs) - but there have been some inconsistencies in the author header. This PR is fixing them.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 196 is in state Final, not Draft or Last Call
 - EIP 2645 requires approval from one of (@bbrandtom, louis@starkware.co)
 - EIP 2678 requires approval from one of (@gnidan, @chriseth, @iamdefinitelyahuman, @fubuloubu, @pipermerriam, @njgheorghita)
 - EIP 2680 requires approval from one of (@mcdee)
 - EIP 615 requires approval from one of (@chfast, @gcolvin, @expede, @chriseth)

**Comment by lightclient** [comment]
The EIP checker should catch these :(

**Review by lightclient — APPROVED** [review]
This PR looks good though, I will go ahead and merge.

**Comment by ligi** [comment]
> The EIP checker should catch these :(

where does the EIP checker live? I fail to find it in this repo

**Pull request merged**
