### PR TITLE
Website: Rewrite index with filters

### PR DESCRIPTION
**Pull request by fulldecent**
New features:

- Clear presentation
- Focus on the content
- Filters

out

https://youtu.be/gzZqgACuULQ

### CODE REVIEW

**Review by SamWilsn — CHANGES_REQUESTED** [review]
I haven't gone over this yet, but I would like to before it's merged.

**Comment by fulldecent** [comment]
Hi @SamWilsn thank you for checking in

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
This should be split into two PRs. One to add the RSS feeds, the other to add filters.

**Comment by fulldecent** [comment]
I agree there are two concerns in this PR. Maybe they are related maybe they are not.

Don't anybody have feedback yet on the PR as-is? And either part of it?

**Comment by Pandapip1** [comment]
> Don't anybody have feedback yet on the PR as-is? And either part of it?

As previously mentionned, the RSS feeds should be a separate PR. I like the idea of filters in concept, but I would prefer it to be a separate page, instead of overriding the readme.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Please fix the CI errors

**Review by Pandapip1 — APPROVED** [review]
+0. I like the filters, but I'd rather it not replace the main index.

**Comment by Pandapip1** [comment]
> @Pandapip1 Is your branch up-to-date? Can I take your index (the rendered static HTML version) and use that in this PR as the homepage? Then I'll move what is currently the homepage here to all.html.

I'm +1 to that.

**Comment by fulldecent** [comment]
May I have the deployed link again please

**Comment by Pandapip1** [comment]
Just use the one here:

https://github.com/ethereum/EIPs/blob/master/index.html

**Comment by fulldecent** [comment]
@Pandapip1 got it

You asked me to separate out this part https://github.com/ethereum/EIPs/pull/6579 is that ready to merge now?

**Comment by Pandapip1** [comment]
> You asked me to separate out this part #6579 is that ready to merge now?

No. It needs one more review.

**Comment by SamWilsn** [comment]
Will this hurt what little SEO we have?

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Keep the all.html page, since removing it would make the EIPs website significantly harder to index.

**Comment by fulldecent** [comment]
I already committed to restore the index.html here. No need to consider that point in this thread. 

However I won't continue on this PR until #6579 merges or somebody tells me "I will support #6483 for merge if you xxxx"

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Please fix the CI errors.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
If you're going to replace the all.html page with the filter page, then I request that you re-add the category-specific pages.

Also, there is some linking to those pages that would break, which would also be bad for SEO.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Also, the RSS feeds are still in this PR.

**Review by Mahmoudhpp — APPROVED** [review]

**Review by FELLIX000 — APPROVED** [review]

**Review by Beautifulme8 — APPROVED** [review]

**Pull request closed without merging**
