### PR TITLE
Update EIP-2335: Remove superfluous use of "verifies"

### PR DESCRIPTION
**Pull request by padresmurfa**
minor language correction

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Stagnant EIPs shouldn't be receiving updates.  If you are the author and want to pick this EIP back up and move it through the process toward review then please create a PR to move it out of stagnant and into Draft or Review.  If you are not the author but you want to champion this idea, you can either try to contact the author to get them to add you to the authors list or you can create a new EIP (feel free to copy the contents).

**Comment by Pandapip1** [comment]
Even though 3 months haven't passed, I'm going to close this PR anyway. @padresmurfa please add a comment mentioning me if you would like this re-opened.

**Comment by padresmurfa** [comment]
Fixing what was effectively a typo should probably not require the kind of heavy-weight process that struck down this pull-request. Not to mention that this is an indication that the original EIP was not sufficiently proof-read.

I'd personally suggest re-opening the pull-request and using it as a tracer-bullet to fix the overall processes of the organisation, but I'm not going to champion this. Mentioning @Pandapip1 in case that feedback would be of interest to you, but to be clear, I'm quite happy with you doing nothing further on the issue.

**Review by Pandapip1 — APPROVED** [review]
The process has changed a bit since this was last updated. I think this change would now be considered acceptable now that there's a system for overriding the bot.

CC @SamWilsn

**Review by lightclient — APPROVED** [review]

**Pull request merged**
