### PR TITLE
EIP 1901 - Add OpenRPC Tooling Implementations

### PR DESCRIPTION
**Pull request by shanejonas**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - File assets/eip-1901/eth-generated-client-openrpc.gif is not an EIP
 - File assets/eip-1901/eth-playground-openrpc.gif is not an EIP
 - File assets/eip-1901/inspector-mock-server-openrpc.png is not an EIP

**Comment by shanejonas** [comment]
bump

**Comment by shanejonas** [comment]
bump.

**Comment by axic** [comment]
Can you rebase and/or merge in master to trigger the CI again?

**Pull request merged**
