### PR TITLE
Creates EIP-2718: Typed Transaction Envelope

### PR DESCRIPTION
**Pull request by MicahZoltu**

### CODE REVIEW

**Comment by vbuterin** [comment]
I tried to do something similar before!

https://github.com/ethereum/EIPs/issues/232

Definitely support such initiatives.

**Comment by luoyhang003** [comment]
What is the impact on receipt root hash calculation caused by this EIP?

I found I cannot calculate the correct `receiptsRoot` of block 2358629 (Ethereum Mainnet) because there is a transaction `0xd1a7f9562e58ac9a911eac197f6ef0460edd20b560253be7ada6991f2188c01e` with transaction type `0x1`

**Comment by MicahZoltu** [comment]
https://eips.ethereum.org/EIPS/eip-2711#new-transaction-receipt

**Comment by luoyhang003** [comment]
> https://eips.ethereum.org/EIPS/eip-2711#new-transaction-receipt

thx, already figured it out.

**Pull request merged**
