### PR TITLE
Create erc-draft-ens.md, a proposal for an Ethereum Name Service standard

### PR DESCRIPTION
**Pull request by Arachnid**

### CODE REVIEW

**Comment by Arachnid** [comment]
Ping?

**Comment by wanderer** [comment]
@Arachnid can you change the file name to eip-XXX.md? thanks!

**Comment by Arachnid** [comment]
Sure - should I use a number for XXX?

**Comment by Arachnid** [comment]
@wanderer Done.

**Comment by Arachnid** [comment]
Ping?

**Review by Brandylee24 — APPROVED** [review]

**Pull request merged**
