### PR TITLE
Fix to be sortable on GitHub from EIP-X to EIP-XXXX

### PR DESCRIPTION
**Pull request by zaq1tomo**
I think https://github.com/bitcoin/bips/ would be good.

### CODE REVIEW

**Comment by nicksavers** [comment]
Many of these documents are directly linked to. Both within EIPs and on the internet. This could break documentation in various places.

**Comment by zaq1tomo** [comment]
This pull request corresponds to direct links in this repository.

**Comment by zaq1tomo** [comment]
In my expectation, if the link breaks, I think that you can easily find the target page in the sorted repository.

**Comment by zaq1tomo** [comment]
solve conflict

**Comment by zaq1tomo** [comment]
fix all link

**Pull request closed without merging**
