### PR TITLE
classify Standard EIPs - adapted from BIP123

### PR DESCRIPTION
**Pull request by ethers**

### CODE REVIEW

**Comment by wanderer** [comment]
needs to be cleaned up a bit. It still mentions Bitcoin. And Networking is already specified to track seperatly in EIP-1

**Comment by ethers** [comment]
thanks for the feedback.  Before this EIP, I did see EIP-1 did mention Networking separately.  But it didn't seem as clean as BIP123.  So it sounds like there's 2 approaches.  We either remove the "Peer Services" in this EIP, or remove Networking in EIP-1 and let this EIP manage it/Networking under "Peer Services".
Which would you prefer?

**Comment by wanderer** [comment]
ok lets change "Peer Services" to "Networking". Core networking; things that affect RLPx will continue to track separately.  But things like eth wire protocol changes would fit nicely here. Lastly what do you think about adding another category for standardizing contracts?  This would take care of things like #20  and #22

**Comment by ethers** [comment]
done changed to Networking.
At this stage, I think it's early to sub-categorize Informational EIPs.  But I'll open it up for discussion separately, since this is classifying Standard EIPs.

**Pull request merged**
