### PR TITLE
EIP:2981 Update to grammar and clarity around ecosystem conversation 🖋️

### PR DESCRIPTION
**Pull request by blmalone**
@VexyCats @jamesmorgan @seibelj can I get an approval?

### CODE REVIEW

**Comment by VexyCats** [comment]
Yes this is fine to merge

**Comment by MicahZoltu** [comment]
Why did you disable automerge?

**Comment by blmalone** [comment]
@MicahZoltu me being overly cautious. Who can we merge this?

**Comment by MicahZoltu** [comment]
In the future, I recommend setting it to be a DRAFT PR if you don't want it merged.  The normal process is that any PR by an author that doesn't change the status will auto-merge once CI passes, which is why it is best to not disable auto-merge on a PR.  😄

**Comment by alita-moore** [comment]
alternatively you can close / reopen the PR and it should enable it again

**Pull request merged**
