### PR TITLE
Announce hard forks and allow discussion before top-down decision making

### PR DESCRIPTION
**Pull request by fulldecent**
This adds a specification that hard forks will be announced as EIPs BEFORE they are decided or scheduled.

Why I am first learning about London hard fork on Reuters? I am subscribed to EIPs, I created the Last Call process and the RSS feeds, we got everybody to agree to them. And still, last-minute upgrades are happening with Ethereum for EIPs that are not even in Final status (https://eips.ethereum.org/EIPS/eip-1559).

And this is the same thing that happened last upgrade.

If Ethereum will maintain the appearance that decisions include community input, can we please respect the processes we have for change management at least sometimes?

ping @Souptacular

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Hardfork coordination is now done on https://github.com/ethereum/eth1.0-specs/

EIPs repository is only for standardization, not for coordinating hardforks.

**Comment by MicahZoltu** [comment]
Core EIPs become Last Call during public testnet phase, and final after the hardfork.  This allows us to change them right up to the last minute if necessary.

**Comment by fulldecent** [comment]
Aha, got it!

No more hardfork EIPs, they are separate. Thanks for sharing the link.

Created a PR for index to link that https://github.com/ethereum/EIPs/pull/3696

**Comment by poojaranjan** [comment]
Upgrade related files are available here  - https://github.com/ethereum/eth1.0-specs/tree/master/network-upgrades/mainnet-upgrades

**Comment by MicahZoltu** [comment]
@fulldecent Is it OK to close this PR now?  I think #3696 is generally reasonable, though I did have a couple notes of feedback.

**Comment by lightclient** [comment]
Please reopen if you decide to continue pursuing.

**Comment by fulldecent** [comment]
Yes, thank you. The other PR entirely supersedes this one.

**Pull request closed without merging**
