### PR TITLE
1193: Finalize

### PR DESCRIPTION
**Pull request by rekmarks**
### Changes

- `Status: Last Call` -> `Status: Final`
- Additional changes
  - Add `ethers` to Implementations section
  - Update links in Implementations section
  - Add `eth-provider` to Implementations section

Review period ended on 2020-06-04.

### Extent of Support/Implementations

So far, the following projects support or have implemented this EIP:
- ethers.io (@ricmoo)
- eth-provider (@floating)
- buidler.dev (@alcuadrado)
- MetaMask (@rekmarks)
- web3.js (@ryanio @frozeman)
- WalletConnect (@pedrouid)
- rainbow.me (@brunobar79)

cc: @axic @Arachnid

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1193 state from Last Call to Final

**Comment by alcuadrado** [comment]
LGTM. Thanks for your work @rekmarks and @ryanio

**Comment by axic** [comment]
Please consider my comment on the discussion URL before merging.

**Comment by axic** [comment]
Also somehow this text does not seem to follow the section layout prescribed by EIP-1.

**Comment by rekmarks** [comment]
Converting this to draft until I've fixed the sections.

**Comment by adrianmcli** [comment]
Really happy to see this finalized. Good stuff @rekmarks. It's been a long time coming.

**Comment by rekmarks** [comment]
@axic sections updated per EIP-1

**Comment by frozeman** [comment]
Thanks for @rekmarks and @ryanio  to finally make that happen! Took us only 4 years 🙌

Though for the record I want to add again, I do think making this Provider multi chain possible without switching chains  should be the default. 
A simple `chainId` in the request object solves that. Dapps in the near future will want to talk to multiple chains at the same time, without switching chains all the time on the provider object. 

With the current way we set the path for a single chain provider, which doesn’t need to be the case.

**Comment by rekmarks** [comment]
Thank you, @frozeman!

Re: `chainId`, I also want to see people add `chainId` as a parameter to RPC requests. @ryanio and I decided against doing it because (1) we're trying to codify an existing pattern, and (2) the standard already implicitly allows `chainId` to be added for anyone that wants to implement that behavior!

I think we can let people play around with it in the wild first, then we can write a multi-chain provider spec somewhere down the line ;)

**Comment by ryanio** [comment]
@frozeman for sure, a provider can accept `chainId` as a parameter to `RequestArguments` and reject with [Error 4901 - The Provider is not connected to the requested chain](https://github.com/ethereum/EIPs/blob/c76b5c23d8b2f75ff7196b8346d8300d1f44600f/EIPS/eip-1193.md#provider-errors).

**Comment by frozeman** [comment]
Good points.
Though I know how long those standardizations can take ;)

**Comment by ryanio** [comment]
@frozeman yeah 😄 there is some language under [`request`](https://github.com/ethereum/EIPs/blob/c76b5c23d8b2f75ff7196b8346d8300d1f44600f/EIPS/eip-1193.md#request):

> The returned Promise **SHOULD** reject if any of the following conditions are met:
> - The Provider is disconnected.
>   - If rejecting for this reason, the Promise rejection error `code` **MUST** be `4900`.
> - The RPC request is directed at a specific chain, and the Provider is not connected to that chain, but is connected to at least one other chain.
>   - If rejecting for this reason, the Promise rejection error `code` **MUST** be `4901`.

As @rekmarks mentioned we did try to implement it into the specification however down the rabbit hole of writing it we found a lot more questions than answers. Therefore we thought it would be better for a future EIP to describe it with learnings from an implementation.

We didn't want to add any more complexity to this EIP in particular, but the interface of `RequestArguments` is open for future params like this to customize the request.

**Comment by rekmarks** [comment]
Update on community support for this EIP:

- [We solicited feedback from other significant wallet projects](https://twitter.com/rekmarks/status/1269183369885220864?s=20)
  - Those projects did not respond, but we did hear from [rainbow.me](https://github.com/ethereum/EIPs/issues/2319#issuecomment-639946445)
- @pedrouid made [a Twitter announcement that received significant attention](https://twitter.com/pedrouid/status/1269236483900276739?s=20)
  - That is to say, it likely showed up in the feeds of people working at the aforementioned wallets

cc: @axic

**Comment by alcuadrado** [comment]
@ricmoo also expressed his support for this proposal and already [implemented it in ethers](https://github.com/ethers-io/ethers.js/commit/56af4413b1dd1787db68985e0b612b63d86fdf7c#diff-b371b7f810d3e25fc390d0eb93f65c29)

**Comment by rekmarks** [comment]
@axic @Arachnid @Souptacular This PR is almost 3 weeks old, and the spec is moving into production at an alarming rate. The Ethereum provider and wallet community would greatly appreciate your help in getting it finalized as soon as possible.

**Comment by MicahZoltu** [comment]
@rekmarks Do you want to merge in the `readonly` proposed change prior to marking this as final?  Once it is final you can't make normative changes.  I'm now an editor so I can merge this as soon as you are ready, just give me the word.

**Comment by axic** [comment]
Oh wow, I am not sure how this got neglected for so long. I believe the only real concern was to give more time for ecosystem to respond (https://github.com/ethereum/EIPs/issues/2319#issuecomment-639101802). I believe that time has passed several times over by now.

I'd definitely suggest to merge this.

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@Souptacular @MicahZoltu unless there's an objection, I'll merge this in the morning.

**Comment by MicahZoltu** [comment]
EIPs [2696](https://eips.ethereum.org/EIPS/eip-2696), [2700](https://eips.ethereum.org/EIPS/eip-2700), and [2786](https://eips.ethereum.org/EIPS/eip-2786) are essentially duplicates of this EIP but broken up into smaller standards.  I still maintain my position that this EIP is too monolithic and should be abandoned, and when I spoke with some of the authors on Discord a while back it sounded like they may not want to pursue this in the face of the smaller EIPs.

Ultimately, deciding whether to merge this is up to @frozeman, @ryanio, @MaiaVictor, @marcgarreau, and @rekmarks.  If none of them respond then I propose we mark this as Abandoned rather than Final, especially since the standard represented here exists in the aforementioned EIPs.

**Comment by ryanio** [comment]
This EIP is already in production and should be finalized.

**Comment by MicahZoltu** [comment]
@ryanio Just to be clear, and EIP can't be in production, but the things specified by this EIP can be in production.  The things specified by this EIP are *also* specified by EIPs 2696, 2700, 2786.  The question here isn't whether the stuff specified by this EIP are in production or not, the question is whether the authors think there is value in merging this EIP despite it being a monolithic duplicate of 2696, 2700, 2786.

**Comment by ryanio** [comment]
Yes we do think there is value in moving this EIP to final.

**Review by frozeman — APPROVED** [review]

**Comment by ryanio** [comment]
Thanks Micah :)

**Comment by axic** [comment]
Huh, this got solved finally! 😅

**Pull request merged**
