### PR TITLE
Update EIP-3712: Multiple Fungible-Tokens

### PR DESCRIPTION
**Pull request by 1999321**
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by abcoathup** [comment]
@1999321 the ERC & EIP repos have been split.  
As this is an application layer standard it should be created as a PR in the ERCs repo.

**Comment by 1999321** [comment]
Ok, how should I continue using 3712 to continue the discussion？

**Comment by poojaranjan** [comment]
The [discussion-to](https://ethereum-magicians.org/t/eip-3712-standard-for-multiple-types-of-fungible-tokens/6912) link will be the same. 

To update or advance the proposal, all PRs must be created at https://github.com/ethereum/ERCs/pulls and this PR should be closed.

**Comment by SamWilsn** [comment]
This definitely looks like an ERC, and so should be moved to the [ethereum/ERCs](https://github.com/ethereum/ERCs/) repository. Unfortunately, we cannot move the pull request automatically, so we ask you to please reopen it there.

**Pull request closed without merging**
