### PR TITLE
Fix table in EIP-665

### PR DESCRIPTION
**Pull request by lucasvo**
Just a small fix to eip-665 to make the table render well in github. No content changed.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 665 requires approval from one of (tobias.oberstein@crossbario.com)

**Comment by lucasvo** [comment]
@oberstet Could you approve?

**Comment by oberstet** [comment]
@lucasvo sorry, not quick enough: sure, I approve, what should I do (also now the branch is out of sync)?

**Comment by lucasvo** [comment]
@oberstet not quite sure, I was just tagging you because the bot said you need to approve. I will see how to get this PR merged!

**Comment by oberstet** [comment]
no clue either .. and why does the bot have to post my email address here? hello @eip-automerger , you suck! ;)

**Comment by lucasvo** [comment]
I'm pretty sure the email address actually comes from the original commit of that added the EIP. And it's also listed here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-665.md

**Comment by Arachnid** [comment]
The bot gets your email address from the EIP - and it can only understand your approval if that email address is publicly associated with your GitHub account.

**Comment by axic** [comment]
@lucasvo can you click the update branch button, it should automerge then.

**Pull request merged**
