### PR TITLE
EIP-1276: Eliminate Difficulty Bomb and Adjust Block Reward on Constantinople Shift

### PR DESCRIPTION
**Pull request by eosclassicteam**
```
eip: 1276
title: Eliminate Difficulty Bomb and Adjust Block Reward on Constantinople Shift
author: EOS Classic (@eosclassicteam)
discussions-to: https://ethereum-magicians.org/t/eip-1276-eliminate-difficulty-bomb-and-adjust-block-reward-on-constantinople-shift/908
type: Standards Track
category: Core
status: Draft
created: 2018-07-31
```

**Abstract**: Starting with `CNSTNTNPL_FORK_BLKNUM` the client will calculate the difficulty without considering the current block number. Furthermore, block rewards will be adjusted to a base of 2 ETH, uncle and nephew rewards will be adjusted accordingly.

Read the draft here: [eip-1276.md](https://github.com/eosclassicteam/EIPs/blob/master/EIPS/eip-1276.md)

Orthogonal intention and not compatible with #1234 .

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Same comment as all of the others.  This should be two separate EIPs, not one EIP.  Everyone seems to want the block reward to be a function of time, and if that is your intent then create at EIP that proposes changing the block reward to be a function of time rather than bundling reward changes with ice age changes.

**Comment by MicahZoltu** [comment]
Just because we (community) made a mistake in the past doesn't mean we should repeat that mistake over and over again.  😉

**Comment by eosclassicteam** [comment]
@MicahZoltu Like we did a bomb delay and we are doing again? :smile:

**Comment by MicahZoltu** [comment]
I'm not sure what you are arguing.  If you believe that combining the ice age changes and the block reward in the same EIP is a good idea, that is fine but I think you'll get more traction if your argument is more than "it is what we did last time".

There is an EIP that removes the difficulty bomb entirely already, https://eips.ethereum.org/EIPS/eip-1240.  My recommendation is that if you want to adjust the block reward you create an EIP that does _just_ that and propose it.  You could even (optionally) write the EIP such that if EIP-1240 is implemented then the block reward formula is `blockReward = 3 ether` and if EIP-1240 is not implemented then the block reward is `blockReward = f(currentBlockTimeTarget, 3)` (you'll need to flesh out a bit what `f` is of course).

**Comment by MicahZoltu** [comment]
I have created a PR for [a new EIP](#1277) that sets the block reward to 2 ETH.  If the intent is to not merge 1240 in some particular chain, then I recommend against using #1277.  However, that is up to the dev team for that chain.

**Comment by 5chdn** [comment]
#1240 is pretty much rejected, Micah, did you follow the last dev call? Nobody shared your opinion to remove the difficulty bomb completely. If you still want to advocate it, I'd recommend you join the next call and and maybe explain your thoughts, maybe in combination with #1277?

**Comment by eosclassicteam** [comment]
@5chdn Yes, it is now

EIP-1128 = EIP-1240 + EIP-1277

What a combination :joy:

**Comment by 5chdn** [comment]
Please use #1276

**Comment by MicahZoltu** [comment]
@5chdn I have neither the time nor inclination to sit through 1.5 hours of discussion that I don't care about just so I can participate in the 5 minutes of discussion I do care about.  Also, the meeting is quite late in the day for me (22:00) which makes it somewhat inconvenient to attend.  This is why I very much prefer discussion happen on forums (Ethereum Magicians, ETH Research, GitHub issues, etc.).

I'll post commentary based on my reading of the Core Devs meeting elsewhere (in a more appropriate place to hold discussion).

**Pull request merged**
