### PR TITLE
Update EIP-4910: Move to Final

### PR DESCRIPTION
**Pull request by Therecanbeonlyone1969**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by lightclient — DISMISSED** [review]
Please fix the markdown lint errors.

**Comment by Therecanbeonlyone1969** [comment]
> Please fix the markdown lint errors.

@lightclient 

The Jekyll bot fails due to a missing HTML file. That is on the github side though, I think.

I have a question: If I cannot use inline HTML how can I make a requirement externally referencable through a URL? If I use e.g. `#### **[R1]**` then some of the required checks fail. What to do to make requirements still externally referenceable?

**Review by SamWilsn — APPROVED** [review]
@lightclient I'm okay with the inline HTML in this proposal, but I don't want to clear your review in case you strongly object.

**Review by SamWilsn — APPROVED** [review]

**Review by SamWilsn — CHANGES_REQUESTED** [review]
Misapproved, brb.

**Review by SamWilsn — DISMISSED** [review]

**Pull request merged**
