### PR TITLE
Update eip-1577.md

### PR DESCRIPTION
**Pull request by pldespaigne**
:christmas_tree: Hi, I'm a huge fan of ENS ! I think this EIP can help people adopting it. So to make adoption even easier I have :
:snowflake:  Added address of an EIP 1577 compliant resolver deployed on Ropsten
:snowflake:  Added a link to a js lib I made to encode / decode content hashes
Thanks a lot for your work ! May the block be with you and happy holidays :santa:

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1577 requires approval from one of (nick@ens.domains, dean@ens.domains)

**Comment by axic** [comment]
@Arachnid @decanus can you approve/decline this?

**Comment by decanus** [comment]
@pldespaigne is the JS implementation up to date with the latest version of the spec?

**Comment by pldespaigne** [comment]
Hello guys ! [content-hash](https://github.com/pldespaigne/content-hash) is up to date now, will be really thankful if you could merge this PR !

**Comment by axic** [comment]
Ping @decanus @Arachnid

**Comment by pldespaigne** [comment]
re ping @decanus @Arachnid

**Comment by axic** [comment]
Ping @decanus @Arachnid

**Comment by Solexplorer** [comment]
@pldespaigne Can this EIP work with some other providers like Arweave which are similar to IPFS ?

**Comment by pldespaigne** [comment]
Yes @Solexplorer , the EIP only specify an encoding. Virtually it can be use for every codec defined in [multicodec](https://github.com/multiformats/multicodec). If you need more info, or a specific thing please open an issue/PR on the [lib repo](https://github.com/pldespaigne/content-hash)

**Pull request merged**
