### PR TITLE
Config: Add @abcoathup as ERC/Meta/Informational editor

### PR DESCRIPTION
**Pull request by Pandapip1**
Context: https://github.com/ethereum-cat-herders/EIPIP/issues/217#issuecomment-1442665320

### CODE REVIEW

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@abcoathup would you be interested in becoming a trial editor?

**Comment by Pandapip1** [comment]
Great! CC @SamWilsn @axic @lightclient @gcolvin

**Comment by xinbenlv** [comment]
What's our plan for bot-assigning numbers?

**Comment by SamWilsn** [comment]
@abcoathup we'd be happy to have you at that level of commitment! I guess our informal process is to have you start reviewing/commenting on PRs in the same way as an editor, and after some time we can add you to the editors list.

**Comment by abcoathup** [comment]
I've mostly assigned EIP/ERC numbers and some minor suggestions to draft EIP/ERCs.  Happy to stay in this role.

**Comment by Pandapip1** [comment]
Bump.

**Comment by abcoathup** [comment]
I'm still happy assigning EIP/ERC numbers (assigned 9 of the last 13 sequential numbers).  
Meetings are generally whilst I am asleep so I won't be attending.

**Comment by SamWilsn** [comment]
Closing because of https://github.com/ethereum/EIPs/pull/6575#issuecomment-1707537033. If you'd like to apply for editorship, @abcoathup, please open a new pull request (or get someone to re-open this one.)

**Pull request closed without merging**
