### PR TITLE
Updated EIP-2565

### PR DESCRIPTION
**Pull request by ineffectualproperty**
Updating EIP-2565 to incorporate feedback from ACD and client implementation teams. Updating status to 'Last Call' as this EIP is now EFI per ACD discussion.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 2565 state from Draft to Last Call
 - File assets/eip-2565/GQuad_Change.png is not an EIP

**Comment by ineffectualproperty** [comment]
The meeting minutes documenting EIP-2565 as EFI (decision 89.2): https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2089.md

**Comment by ineffectualproperty** [comment]
Awesome, thanks for the tip. Added a `review-period-end`. Let me know if there are any other issues.

**Comment by ineffectualproperty** [comment]
@lightclient - just wanted to see if there are any additional issues - thanks!

**Comment by lightclient** [comment]
Hi @ineffectualproperty, this EIP appears to be structurally sound. I noticed that the discussion thread is rather quiet, I think it would be nice if there were some comments there from core devs (or a link to an ACD call / client team discussions where this EIP receives positive feedback), I think that would make it easier for an EIP editor to decide if this should be moved to Final Call. I've requested (again) in the gitter chat for this PR to be reviewed by an editor.

**Comment by MicahZoltu** [comment]
Really, Core Devs shouldn't be wasting time looking at EIPs before Last Call.  Last Call is perhaps a poor name, really it means "the author and select interested parties no longer are actively iterating on the EIP and it is ready for broader exposure.

I have updated the date to be 2 weeks from today, as soon as CI passes I'll merge this.

**Pull request merged**
