### PR TITLE
Add another reference implementation for ERC-900

### PR DESCRIPTION
**Pull request by johnhforrest**
Adding another reference implementation to ERC-900.

The reference includes:
- A basic implementation
- A credits implementation where staking rewards integer-based credits
- A weighted implementation where stakes can gain weight over time by accruing interest

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 900 requires approval from one of (dean@tokenate.io, jorge@aragon.one)

**Comment by johnhforrest** [comment]
@decanus Please review when you have time.

**Comment by axic** [comment]
@decanus @izqui can you please review this?

**Comment by decanus** [comment]
lgtm, other than the fact that this assumption is wrong https://github.com/codex-protocol/contract.erc-900/blob/master/contracts/ERC900/ERC900BasicStakeContract.sol#L175

**Pull request merged**
