### PR TITLE
EIP-3436: fix specification variable definitions and improve syntax

### PR DESCRIPTION
**Pull request by meowsbits**

### CODE REVIEW

**Comment by MicahZoltu** [comment]
@shemnon can you please review this (approve if it looks good).

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - eip-3436.md requires approval from one of (shemnon)
 @shemnon

**Comment by alita-moore** [comment]
sorry about the closes / reopens @meowsbits I'm developing the bot so while not strictly necessary is easiest to test this way

**Comment by meowsbits** [comment]
Wait, you're a robot developing another robot?! I've been waiting for this moment...  Congratulations!

**Review by shemnon — APPROVED** [review]

**Comment by shemnon** [comment]
:shrug:  Merge bot is complaining about lack of auth tokens.  I'm ok with merging.

**Comment by alita-moore** [comment]
thank you for pointing this out @shemnon

**Pull request merged**
