### PR TITLE
Demote EIP-150 from a dependency to a reference in EIP-1884

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1884 requires approval from one of (@holiman)

**Comment by axic** [comment]
I don't agree with this. The specification shows repricing from EIP-150.

**Comment by fulldecent** [comment]
If another chain did not have EIP-150 pricing currently in effect then the analysis and prescriptions of this new EIP would still work. This is why I think it is not a dependency.

**Comment by axic** [comment]
The `Specification` section explicitly says repricing from "The SLOAD (0x54) operation changes from 200 to 800 gas" which means changing price based on EIP-150.

**Comment by axic** [comment]
I see your point trying to make this independent, but I have a feeling the analysis presented in the EIP only makes sense with a known set of gas costs for other instructions. Specifying EIP-150 (and perhaps even Constantinople would be better) makes the analysis more sound. Imagine a case where costs are entirely different, then EIP-1884 is applied, and instead of the intended effect, it just opens a large attack vector due to mispricing.

**Comment by holiman** [comment]
I... really don't know... I think the analysis is closely tied to the mainnet happenings, (so, petersburg), and also 150. Whether it's a requirement or not... I'd prefer to just leave it in, but don't have any strong opinions either way..

**Comment by holiman** [comment]
So I'd prefer to go with whatever @axic prefers

**Comment by fulldecent** [comment]
Fair point. Thanks for reviewing. No need to consider this further.

**Pull request closed without merging**
