### PR TITLE
3675: refactor the rationale

### PR DESCRIPTION
**Pull request by ralexstokes**
Addressing PR feedback from this PR https://github.com/ethereum/EIPs/pull/4415 that was auto-merged a bit too early

### CODE REVIEW

**Comment by ralexstokes** [comment]
cc @axic

**Comment by MicahZoltu** [comment]
This needs approval from the authors, not an editor.

**Review by mkalinin — APPROVED** [review]
Approving this PR but we should revisit a part of specification that covers EIP-2124 logic, see my concern [here](https://github.com/ethereum/EIPs/pull/4415/files#r745337814)

**Comment by axic** [comment]
> Approving this PR but we should revisit a part of specification that covers EIP-2124 logic, see my concern here

@mkalinin I think this should be moved to the discussion URL as now this question has been chased through 3 PRs without resolution :(

**Comment by mkalinin** [comment]
> > Approving this PR but we should revisit a part of specification that covers EIP-2124 logic, see my concern here
> 
> @mkalinin I think this should be moved to the discussion URL as now this question has been chased through 3 PRs without resolution :(

Done! https://ethereum-magicians.org/t/eip-3675-upgrade-consensus-to-proof-of-stake/6706/7

**Comment by axic** [comment]
@mkalinin thanks!

**Pull request merged**
