### PR TITLE
EIP XXX: Smart Contract Development Guidelines

### PR DESCRIPTION
**Pull request by fubuloubu**
---
eip: <to be assigned>
title: Smart Contract Development Guidelines
author: Rex Hygate (@RexShinka), Bryant Eisenbach (@fubuloubu), Roman Pavlovskyi (@rpavlovs)
type: Informational
status: Draft
created: 2018-02-17
---

# Simple Summary
Develop a comprehensive set of standards and methodologies formalizing security-conscious analysis and design of Ethereum smart contracts.

# Abstract
There are many competing "best practices" in the Ethereum ecosystem describing security concerns when designing smart contract code. There has been some effort to standardize these practices, but "security best practices" is not a strong solution to the underlying problem. This EIP defines that underlying problem as a lack of a robust software engineering process for smart contract design that takes into account the unique characteristics of smart contracts.

# Motivation
Software developed for Aerospace, Medical, Telecom, and Embedded Devices typically follows a more robust software design process due to the critical nature of the software being developed. The standards used for the software design process in these industries arise from a need to quantify and mitigate risk in software that has the potential to significantly impact human life and property. Smart Contracts are similar development items, since poor behavior of these software items can have a significant financial impact to users; therefore, it should be developed to a similar level of rigor.

This EIP aims to adopt some of these standards, particularly [DO-178](https://en.wikipedia.org/wiki/DO-178B), to create a common framework tailored specifically to Smart Contract design and development practices. This includes formalizing certain software engineering guidelines (of which "security best practices" are a major component) and tool development processes to organize the efforts for the larger Ethereum ecosystem.

# Specification
The core of this standard is a model of understanding risk inherant to software development items. We will leverage the [OWASP](https://www.owasp.org/index.php/OWASP_Risk_Rating_Methodology) model, a common framework in software security, to develop this model.

The OWASP model specifies that `Risk = Likelihood x Impact`. In order to quantify an identified risk and communicate it to interested parties, it is necessary to quantify the `Likelihood` that an issue with occur and the `Impact` it will have on the platform or network.

OWASP

We will perform this analysis at the method level of each smart contract, which will provide a comphrehensive analysis of all the possible calls.

Specifically, we define `Likelihood` as the access control level (ACL) of a given method, and `Impact` as the ability of that method to affect the use or ownership of valuable assets  held in the state of Ethereum.

Once the level of risk is understood, a level of rigor needed to verify the software can be objectively determined, which is defined as a the Design Assurance Level (DAL). This can inform a variety of techniques to verify software development items (including testing, simulation, formal verification, etc.) as well as the level of documentation required to be able to conclusively determine adequete testing has been performed.

# Rationale
This EIP only serves to establish an industry standards body, of which the community is encouraged to actively contribute to. This standards body develops guidelines through consensus of the community,
and as such does not endorse a particular design approach or perspective, only the underlying goal of producing robust, security-critical smart contract code through robust, security-conscious processes and toolsets.

# Backwards Compatibility
This informational EIP suggests a new set of standards that will be fully compatible with existing efforts.

# Implementation
A first draft of a subset of these guidelines and examples of their use is included in our [GitHub](https://github.com/SecurEth) repositories. We invite you to help contribute on the formation of this standards body through colloboration.

# Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

# Special Thanks!
This project was developed at ETH Denver!
We'd like to thank the following people for helping us in designing this EIP!
* Manuel Aráoz (@maraoz)
* Hudson Jameson (@Souptacular)
* Jorge Izquierdo (@izqui)
* Phillip Goldberg (@djphillyg)

### CODE REVIEW

**Comment by ethers** [comment]
How about creating page/s on the Ethereum wiki for these materials?  cc @Souptacular

**Comment by fubuloubu** [comment]
Sure. Attempting to corral all the fragmented standards together back into an Ethereum wiki is certainly an option. What would you propose the process is for maintaining them and ensuring they stay state of the art as our community grows? How do we ensure a comprehensive and simple organization of all these wiki pages in one place for easy access? Who is going to do the research into best practices to make sure we pick and choose from the best?

A standard is only as strong as the people and organizations that support it and ensure it remains cohesive and concise. Let's discuss how this organization is formed and funded.

This is how we become proactive about security issues, instead of reactive. This is how people trust us when we go mainstream with their money.

**Comment by fubuloubu** [comment]
"... how they design their code for an environment where mistakes are extremely costly. This is no longer the era of “agile” development and failing forward; foresight and accuracy are key."

https://venturebeat.com/2018/02/18/as-smart-contracts-get-smarter-the-rules-of-development-will-change/

**Comment by maurelian** [comment]
This is a good idea. 
We are currently in the process of more rigorously defining our audit process, and will be happy to funnel them over here when they are ready.

**Comment by Arachnid** [comment]
This is a courtesy notice to let you know that the format for EIPs has been modified slightly. If you want your draft merged, you will need to make some small changes to how your EIP is formatted:

 - Frontmatter is now contained between lines with only a triple dash ('---')
 - Headers in the frontmatter are now lowercase.

If your PR is editing an existing EIP rather than creating a new one, this has already been done for you, and you need only rebase your PR.

In addition, a continuous build has been setup, which will check your PR against the rules for EIP formatting automatically once you update your PR. This build ensures all required headers are present, as well as performing a number of other checks.

Please rebase your PR against the latest master, and edit your PR to use the above format for frontmatter. For convenience, here's a sample header you can copy and adapt:

```
---
eip: <num>
title: <title>
author: <author>
type: [Standards Track|Informational|Meta]
category: [Core|Networking|Interface|ERC] (for type: Standards Track only)
status: Draft
created: <date>
---
```

**Comment by fubuloubu** [comment]
Closing this request as it is not appropriate as an EIP. Guidelines are community documents, and smart contract development does not need standardization through an EIP.

It is still however being worked on via the ETHSecurity initiative. Check out guidelines.secureth.org to see the latest version of these guidelines.

**Pull request closed without merging**
