### PR TITLE
Add EIP-5987: Permissionless Transfer With Authorization

### PR DESCRIPTION
**Pull request by grantmike**
An EIP for permissionlessTransferWithAuthorization, extending [EIP-3009](https://github.com/ethereum/EIPs/pull/3009)

### CODE REVIEW

**Review by Pandapip1 — COMMENTED** [review]
Please fix the walidator errors

**Comment by Pandapip1** [comment]
FYI - when creating new EIPs, it's highly recommended to use the template, as it follows the most up-to-date sections and their content (minus the external links, which are gradually being re-added).

**Review by Pandapip1 — COMMENTED** [review]
Here's my partial review

**Comment by juli** [comment]
@grantmike As we discussed before, economic incentives make relayers attacking relayers a more likely scenario than relayers abusing users. Part of a design that protects relayers and incentivizes participation in the system is using unique nonces for each relayer. The user's wallet selects a relayer with a timeout; if the relayer fails, the user tx is delayed, and the relayer's reputation is affected, but the risk is reduced for both.I can share more details by email.

**Pull request closed without merging**
