### PR TITLE
change `o` to `0`

### PR DESCRIPTION
**Pull request by RatanRSur**

### CODE REVIEW

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - eip-2481.md requires approval from one of (christoph@ethereum.org)
 christoph@ethereum.org

**Comment by axic** [comment]
@cburgdorf can you please review and accept/reject?

**Review by cburgdorf — APPROVED** [review]

**Comment by MicahZoltu** [comment]
@RatanRSur Can you fixup this PR?  It appears to be out of date with master.

**Review by holiman — APPROVED** [review]

**Comment by RatanRSur** [comment]
@cburgdorf @axic , tried changing the author but it still failed.

**Comment by holiman** [comment]
>  tried changing the author but it still failed.

Guess it would be flawed if the author-change required approval from the _new_ author, instead of the old one, so that's probably fine. I'll just merge this as it's approved.

**Comment by axic** [comment]
Thanks, looks nice, auto-merge should work from now-on 😉

**Comment by MicahZoltu** [comment]
Sorry I didn't merge this sooner.  I didn't realize that `christoph@ethereum.org == cburgdorf`.

**Pull request merged**
