### PR TITLE
EIP-634: Add peepeth and made it more DRY

### PR DESCRIPTION
**Pull request by ligi**
If we have twitter mentioned here -so we should also mention peepeth which is more native to Ethereum

paging @ricmoo 

also wondering as the implementations section is empty yet if I should do a PR to add https://github.com/komputing/KEthereum/tree/master/ens / https://github.com/komputing/KEthereum/tree/master/erc634 
Or should this section just be about smart-contract implementations of this EIP?

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 634 requires approval from one of (me@ricmoo.com)

**Comment by ricmoo** [comment]
Oh, at the time there was not implementation. I was planning to link to the ethers.js and the contract, but can add the above links too.

**Comment by axic** [comment]
@ricmoo do you approve this?

**Comment by axic** [comment]
Ping @ricmoo

**Comment by ricmoo** [comment]
Maybe one quick change, add a blank line between the basic and the vendor types, and alphabetized the vendor types? So peepeth should be above twitter, GitHub at the top?

**Comment by ligi** [comment]
@ricmoo thanks for the suggestion - changed as requested

**Pull request merged**
