### PR TITLE
EIP-210: Fixes for blockhash contracts

### PR DESCRIPTION
**Pull request by chfast**
1. Fix blockhash contract for block number 1 
   This fixes the issue in the contract when executed from SYSTEM account at block 1. Then the number of the previous block is 0 and the contract executes the loop forever.

2. Correctly handle argument with negative value 
   Fix fixes the issue in the blockhash contract where the negative value of the argument is not properly handled.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 210 requires approval from one of (@vbuterin)

**Comment by chfast** [comment]
I'm not sure I extract runtime code correctly. @chriseth @axic can you take a look?

**Comment by holiman** [comment]
That blocknum 1 issue is actually very important, because otherwise it'll produce very weird results in most test scenarios

**Comment by gumb0** [comment]
We still don't have any tests for the contract code itself, do we?

**Comment by chfast** [comment]
We do, but for old version of the contract: https://github.com/ethereum/EIPs/pull/641. When migrating to new code I discovered this block 1 bug.

**Comment by chfast** [comment]
Because these 2 bugs are quite obvious, I'd like to fix them first before progressing with tests.

**Comment by axic** [comment]
> I'm not sure I extracted runtime code correctly. @chriseth @axic can you take a look?

This seems to be Vyper so I am not sure, but it looks okay.

Can this be merged?

**Pull request merged**
