### PR TITLE
EIP-1108: Add gas cost clarification + copyright assignment

### PR DESCRIPTION
**Pull request by Shadowfiend**
Per https://github.com/ethereum/EIPs/pull/1987#discussion_r282513653, added more details on the proposed gas cost for EC precompilesl Per https://github.com/ethereum/EIPs/pull/1987#issuecomment-494968355, added the copyright statement.

Not sure if we need an approval from @zac-williamson as well here since this adds a copyright statement on work that's already been written.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Opened this in draft as I'm not sure if the automerger would hit this, and I didn't want that to happen until I knew if we needed @zac-williamson's response.

**Comment by zac-williamson** [comment]
> Opened this in draft as I'm not sure if the automerger would hit this, and I didn't want that to happen until I knew if we needed @zac-williamson's response.

Heya, no problems on my end, feel free to merge

**Comment by Shadowfiend** [comment]
Looks like this guy may need a manual trigger for the Travis CI build.

**Comment by axic** [comment]
Need to click "Ready for review".

**Comment by Shadowfiend** [comment]
Yeah, I marked it ready and waited a minute to see if it would get picked up:

Screen Shot 2019-05-24 at 11 09 54

Might just take a few to pick up, though.

**Pull request merged**
