### PR TITLE
EIP-1014: Use keccak256 name instead of sha3

### PR DESCRIPTION
**Pull request by chfast**
Do not refer to the hash function as `sha3` because it is SHA3. Use more precise `keccak256` name.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1014 requires approval from one of (@vbuterin)

**Comment by chfast** [comment]
@djrtwo you promised me your intervention here.

**Comment by djrtwo** [comment]
Gave a nudge to @vbuterin for a merge in another channel. Trying again _here_.

Hey @vbuterin, please merge this tiny modification to your PR. It changes `sha` to `keccak256` for clarity.

**Comment by djrtwo** [comment]
Got the go ahead from Vitalik to merge. @chfast @Arachnid 
screen shot 2018-08-31 at 11 35 26 am

**Comment by MicahZoltu** [comment]
If @vbuterin isn't going to maintain this PR in GitHub, or at least drop a note in this PR then I recommend just creating a new PR where you are the primary author and we can get that merged.  I dislike the idea of using Telegram/Whatsapp screenshots as a means of PR merge approvals.

EIPs are all CC-0 licensed, so you can freely just copy/paste the EIP with a new number and your name as the author without violating any silly copyright rules.

**Comment by axic** [comment]
> EIPs are all CC-0 licensed

Well, except this one :)

**Comment by chfast** [comment]
> > EIPs are all CC-0 licensed
> 
> Well, except this one :)

And this one: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1355.md.

**Comment by holiman** [comment]
yolo

**Pull request merged**
