### PR TITLE
EIP-3675: Move to Review

### PR DESCRIPTION
**Pull request by mkalinin**
Change EIP-3675 status to Review

### CODE REVIEW

**Review by axic — CHANGES_REQUESTED** [review]
Please make sure this follows the latest EIP-1 rules. Two things to note at a glance: lack of `description` preamble and deprecated `Simple Summary` section.

**Review by axic — COMMENTED** [review]
This is okay for `Review` from perspective, but there is a big outstanding question regarding the relation to EIP-2982 and the external links to the devp2p spec.

**Comment by mkalinin** [comment]
> This is okay for `Review` from perspective, but there is a big outstanding question regarding the relation to EIP-2982 and the external links to the devp2p spec.

I was thinking about whether it makes sense if an EIP `require` an informational EIP. Technically EIP-3675 implicitly depends on all consensus specs and on `bellatrix` upgrade in particular. Not sure what would be the best way to reflect this dependency. Currently, it's mentioning the beacon chain as the new consensus driver and have a link to consensus specs. I'd leave it as it is if it's appropriate.

Network section could be in a separate EIP that depends on EIP-3675. But the changes to the networking stack are tightly coupled to the transition process; not sure if it would read better if they were placed in a separate document. Though, I don't have strong arguments against doing so.

**Review by lightclient — APPROVED** [review]
LGTM

**Pull request merged**
