### PR TITLE
Update EIP-5679: Move to Final

### PR DESCRIPTION
**Pull request by xinbenlv**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by Pandapip1 — APPROVED** [review]

**Comment by xinbenlv** [comment]
Thank you! Will wait until deadline meets

**Comment by xinbenlv** [comment]
Do you know how to prevent auto submission?

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Deadline

**Comment by xinbenlv** [comment]
Converting to draft temporarily to avoid auto-merge before deadline. Will resume once deadline reaches

**Review by Pandapip1 — APPROVED** [review]
Great - if you unmark this as draft tomorrow, it'll automerge

**Comment by xinbenlv** [comment]
Will do!

**Pull request merged**
