### PR TITLE
Manager Token Standard

### PR DESCRIPTION
**Pull request by leohio**
proposed Manager Token Standard which is a practical usage of NFT with PaaS.
A demo is also linked. pls check.

### CODE REVIEW

**Comment by leohio** [comment]
ERC721 token to idenfing --> ERC721 token to identify

**Comment by Arachnid** [comment]
Please renumber to EIP-1152, and revert the changes to EIP-x.

**Comment by leohio** [comment]
Thank you. I've renumbered eip-X to eip-1152.
Is there any problem to use "git revert" ?
Or is this done with my "rename to eip-1152" commit?

**Comment by Arachnid** [comment]
Your PR deletes `eip-X.md`, and adds a new file `.eip-X.md.swp`. Please revert these changes.

**Comment by leohio** [comment]
renamed and deleted .eip-X.md.swp

**Comment by Arachnid** [comment]
Your PR now changes eip-x.md, instead.

Your PR needs to submit a new PR, not change the template file.

**Comment by leohio** [comment]
new PR
https://github.com/ethereum/EIPs/pull/1511

**Comment by axic** [comment]
Closing this in favour of #1511 as it seems to be the wish of the author.

**Pull request closed without merging**
