### PR TITLE
update 1967 status to Review

### PR DESCRIPTION
**Pull request by wschwab**

### CODE REVIEW

**Comment by chee-chyuan** [comment]
hi. it do seems like Simple Summary is no longer in used in favor for description in the preamble according to the latest eip1

**Comment by spalladino** [comment]
> it do seems like Simple Summary is no longer in used in favor for description in the preamble according to the latest eip1

Updated that on https://github.com/ethereum/EIPs/pull/4461

**Comment by MicahZoltu** [comment]
Hmm, why does this PR not reflect that?  The diff should show against current master.

**Comment by spalladino** [comment]
> Hmm, why does this PR not reflect that? The diff should show against current master.

Dunno. Opened #4495 as a fresh PR to see if it helps.

**Comment by MicahZoltu** [comment]
Closing in favor of #4495

**Pull request closed without merging**
