### PR TITLE
Finalize ERC-1271

### PR DESCRIPTION
**Pull request by PhABC**
Well beyond the last-call deadline. Time to cement this and make it final.

### CODE REVIEW

**Review by MicahZoltu — COMMENTED** [review]
Simple Summary has been deprecated in favor of a `description` metadata field.  In this case, you should also shorten it down to about a sentence, consider something like this:
```
description: A standard way for contracts to verify if a provided signature is valid when the account is a smart contract.
```

----
EIP links should be relative, change 
```
[EIP-712](https://eips.ethereum.org/EIPS/eip-712)
```
to
```
[EIP-712](./eip-712.md)
```

**Comment by PhABC** [comment]
@MicahZoltu thanks! Updated both

**Comment by lightclient** [comment]
@PhABC could you please move "Security Considerations" below "Reference Implementation"? Other than that, I think it looks good on my end.

**Comment by PhABC** [comment]
@lightclient Done and rebased PR branch off master

**Review by lightclient — APPROVED** [review]
LGTM! Glad to see this finalized.

**Comment by PhABC** [comment]
Any reason why this isn’t getting merged? Looks like CI is stuck.

**Pull request merged**
