### PR TITLE
EIP5006: Change Status to Last Call

### PR DESCRIPTION
**Pull request by emojidao**
EIP5006: Change Status to Last Call

### CODE REVIEW

**Review by 0xanders — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]
LGTM

**Review by Pandapip1 — APPROVED** [review]
Come on @eth-bot...

**Comment by luyishisi** [comment]
Hello, 
I found that this part of the contract has certain risks. SetUser lacks permission management, so that any user can modify any relationship. The user must override it before using it with peace of mind. Why is this part of the restriction no longer in the standard?

**Comment by Pandapip1** [comment]
> Hello,
> I found that this part of the contract has certain risks. SetUser lacks permission management, so that any user can modify any relationship. The user must override it before using it with peace of mind. Why is this part of the restriction no longer in the standard?

Please submit a PR that fixes this.

**Comment by 0xanders** [comment]
> > Hello,
> > I found that this part of the contract has certain risks. SetUser lacks permission management, so that any user can modify any relationship. The user must override it before using it with peace of mind. Why is this part of the restriction no longer in the standard?
> 
> Please submit a PR that fixes this.

Thanks  @Pandapip1 ,   just submitted a PR : https://github.com/ethereum/EIPs/pull/5304#pullrequestreview-1046808441

**Comment by 0xanders** [comment]
> 

> Hello,
> I found that this part of the contract has certain risks. SetUser lacks permission management, so that any user can modify any relationship. The user must override it before using it with peace of mind. Why is this part of the restriction no longer in the standard?

Thanks @luyishisi  , we submitted a PR to fix this bug.

**Pull request merged**
