### PR TITLE
Update eip-712.md

### PR DESCRIPTION
**Pull request by moodysalem**
correct the byte length of the return data from `eth_signTypedData`

### CODE REVIEW

**Comment by lightclient** [comment]
cc @recmo

**Comment by wschwab** [comment]
I've got a PR open for moving 712 to Last Call: #4383 , would it be okay with you @moodysalem if I include this change there so that there's just that PR for it?

**Comment by SamWilsn** [comment]
@wschwab Not sure if you saw the reaction, but you got a :+1: from moodysalem to move the changes into your other PR.

**Comment by wschwab** [comment]
> @wschwab Not sure if you saw the reaction, but you got a +1 from moodysalem to move the changes into your other PR.

I didn't, thanks for flagging - I don't know exactly when I'll get around to it, will try to make it today

**Comment by SamWilsn** [comment]
No rush! I've just been going through the EIPs from oldest to newest, so you'll probably get pings from me periodically ;)

**Comment by wschwab** [comment]
I've made the changes and will push them to #4383 , but would like some confirmation that numbers proposed here are definitely correct (and that isn't just a difference of two-digit words vs single or something like that)

**Comment by lightclient** [comment]
closing in favor of #4383

**Pull request closed without merging**
