### PR TITLE
Proposal to add numPackageIds() and numReleaseIds()

### PR DESCRIPTION
**Pull request by njgheorghita**
### Proposal to add `numPackageIds()` and `numReleaseIds()` to the standard Read API.

```solidity
// Returns the total number of unique packages in a registry.
function numPackageIds() public view returns (uint totalCount);

 // Returns the total number of unique releases belonging to the given packageName in a registry.
function numReleaseIds(string packageName) public view returns (uint totalCount);
```

This data can be typically found somewhere in a registry implementation (i.e. `ReleaseDB.getNumReleasesForNameHash()` in the [Solidity reference implementation](https://github.com/ethpm/escape-truffle/blob/master/contracts/ReleaseDB.sol)). However, it's quite useful to standardize how this data can be accessed via the primary registry interface since the `totalCount` is used in the pagination scheme of other standard interface functions (`getAllPackageIds()` and `getAllReleaseIds()`).

This pr also corrects a small typo, `getAllPackageIds()` should return an `packageIds` as an array of `bytes32` rather than a single `bytes32` value. And adds myself as an author.

Also included in this PR is an event spec `VersionRelease` to be triggered with every new version that is released.

### CODE REVIEW

**Comment by njgheorghita** [comment]
ping @gnidan @pipermerriam @cgewecke for thoughts

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1319 requires approval from one of (@cgewecke, nick.dandrea@consensys.net, piper@ethereum.org)

**Comment by njgheorghita** [comment]
Thanks @gnidan @pipermerriam! From what I can tell, there's nothing I can do to get this merged. It seems as though one of you two need to merge it yourself.

**Comment by pipermerriam** [comment]
I do not have merge permissions.  Paging @Arachnid

**Comment by njgheorghita** [comment]
ping @pipermerriam @gnidan - Added an event to this pr. 
#### VersionRelease
MUST be triggered when `release` is successfully called.
 ```solidity
event VersionRelease(string packageName, string versino, string manifestURI)
```

If approved, updates are needed in both the solidity & vyper reference implementations, but imo this is a pretty useful event and is needed.

**Comment by pipermerriam** [comment]
STRONG :+1: on adding this.

**Comment by pipermerriam** [comment]
@njgheorghita spelling: `s/versino/version`

**Comment by njgheorghita** [comment]
Ping @Arachnid if you can help get this merged, that would be great! Let me know if there's anything I can do to make that happen

**Comment by nicksavers** [comment]
@pipermerriam You do have merge permissions on this EIP. All you have to do is give the Approval
Next time on a PR, just go to `Files changed > Review changes > Approve > Submit`. And the @eip-automerger will just merge it for you.

**Comment by pipermerriam** [comment]
Thanks @nicksavers , will do next time.

**Pull request merged**
