### PR TITLE
The issue was in the YAML syntax with multi-line strings.

### PR DESCRIPTION
**Pull request by mryalamanchi**
YAML syntax suggests using multiline string with pipe character (|).
It will be best to NOT use single/double quotes, especially when it's multi-line and Markdown string.

More about multi-line string value in YAML: https://yaml-multiline.info

Try it out here: https://yamlvalidator.com/ with example:
```
issue-message: |
  Since this is your first issue, we kindly remind you to check out [EIP-1](https://eips.ethereum.org/EIPS/eip-1) for guidance.
  
  If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/).
pr-message: |
  Since this is your first pull request, we kindly remind you to check out [EIP-1](https://eips.ethereum.org/EIPS/eip-1) for guidance.
  
  If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/).
```

Links to the source on what's going during the parsing of the YAML string value in [first-interaction@v1](https://github.com/actions/first-interaction/blob/55b296e9321d46e20743dcc8c51de4ef6507d338/src/main.ts#L6) and the [getInput()](https://github.com/actions/toolkit/blob/88062ec4731967e1d4d835dee48b663379430edc/packages/core/src/core.ts#L128) function.  

cc: @alita-moore

### CODE REVIEW

**Review by MicahZoltu — APPROVED** [review]

**Comment by MicahZoltu** [comment]
Will wait for @alita-moore to review and merge, but this looks good to me.

**Review by alita-moore — APPROVED** [review]

**Comment by mryalamanchi** [comment]
@alita-moore is there any way to test whether the output is correctly formatted with the new commit?

**Comment by MicahZoltu** [comment]
Create a new GitHub account and create an issue in this repository and see how the bot responds.

**Comment by MicahZoltu** [comment]
Alternatively, you could add the greeter script to some other repository and test there.

**Comment by alita-moore** [comment]
@mryalamanchi easiest is to fork the repo and run the bot under circumstances that would run it like that. In cases like these though I sometimes just assume it's fine and let others tell me it's not because it would take more effort than it's worth to verify

**Comment by mryalamanchi** [comment]
@alita-moore sure. I will keep that in mind.

**Pull request merged**
