### PR TITLE
Update Constantinople Meta-EIP 1013

### PR DESCRIPTION
**Pull request by 5chdn**
- Remove EIP-210 from list
- Replace EIP-1087 with EIP-1283
- Add EIP-1234

As discussed at https://github.com/ethereum/pm/issues/55; see also https://github.com/ethereum/pm/issues/53

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1013 requires approval from one of (@nicksavers)

**Comment by axic** [comment]
@nicksavers @holiman can you review?

**Comment by holiman** [comment]
I'm not an eip editor, not sure who usually does this @Arachnid  ?

**Comment by axic** [comment]
Nobody I guess.

But by review I meant if this matches that of the agreement on AllCoreDevs.

**Pull request merged**
