### PR TITLE
update 2309 to last call

### PR DESCRIPTION
**Pull request by pizza-r0b**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 2309 state from Draft to Last Call
 - EIP 2309 requires approval from one of (@pizza_r0b)

**Comment by pizza-r0b** [comment]
@axic makes sense. How long are EIPs typically in draft status?

**Comment by axic** [comment]
> How long are EIPs typically in draft status?

To clarify this is my personal opinion as we don't seem to have written rules about this. But the point of last call is to gather a last round of reviews before it is final. It would make sense gathering review and feedback from the ecosystems before that.

**Comment by pizza-r0b** [comment]
@axic That makes sense. I will close this for now.

**Pull request closed without merging**
