### PR TITLE
Move EIP-3525 to last call

### PR DESCRIPTION
**Pull request by will-edge**
Last call dead line set to 2022-09-03

### CODE REVIEW

**Comment by will-edge** [comment]
> Please fix the Codespell error.

Done, thanks for that.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
There are a few things that need changing. I'll submit a PR to your fork with those changes.

**Comment by will-edge** [comment]
> There are a few things that need changing. I'll submit a PR to your fork with those changes.

Thanks for that, looking forward to the co-operation!

**Comment by will-edge** [comment]
All modifications merged, thanks to @Pandapip1 for those great revises and corrections!

**Review by Pandapip1 — APPROVED** [review]
LGTM

**Pull request merged**
