### PR TITLE
Configuration: Add "furter" to whitelist

### PR DESCRIPTION
**Pull request by Pandapip1**
Add someone else's name to CodeSpell

### CODE REVIEW

**Review by xinbenlv — APPROVED** [review]
LGTM for this change. 
If I may suggest, consider just exclude the author names instead.

**Comment by Pandapip1** [comment]
> If I may suggest, consider just exclude the author names instead.

This has already been suggested. Sadly, this is not possible.

**Comment by xinbenlv** [comment]
> 

I think it can be archived by markdown linter plus suppress marker `markdownlint-disable` ish, have we considered look into it?

**Comment by Pandapip1** [comment]
Markdownlint doesn't check spelling. This is the current situation.

Admittedly, I have added a bypass so that codespell doesn't actually error right now, so finding a fix is not top priority.

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
