### PR TITLE
Move EIP-1283 status to last call

### PR DESCRIPTION
**Pull request by sorpaas**
The spec is finalized, covered with test cases, and had an [informal proof](https://gist.github.com/sorpaas/27b8026c40e4777ede889c40e3824a04). See discussion on https://github.com/ethereum/pm/issues/55

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1283 state from Draft to Accepted

**Comment by axic** [comment]
@gumb0 @holiman @5chdn I am not sure what the process is regarding moving this from Draft to Accepted, but I think it is mostly down to the client implementers doing the hard fork changes.

**Comment by 5chdn** [comment]
It's accepted as decided in the constantinople session 1, see also meta eip, e.g., https://github.com/ethereum/EIPs/pull/1366

**Comment by axic** [comment]
Actually it seems according to the EIP-1 this should go through a `Last Call` step first:
>  Accepted (Core EIPs only) -- A successful Last Call without material changes or unaddressed technical complaints will become Accepted.

**Comment by sorpaas** [comment]
@axic That looks like a new change in the EIP process after I made this PR -- I don't remember previously Core EIPs had "Last Call" status.

Anyway, just changed!

**Comment by axic** [comment]
@sorpaas also it seems that the Last Call would require an additional field: `review-period-end:`

Though perhaps for hard fork relates EIPs the last call process is not enforced.

**Pull request merged**
