### PR TITLE
Add EIP-5559: Cross Chain Write Deferral Protocol

### PR DESCRIPTION
**Pull request by 0xpaulio**
This EIP proposes a new mechanism in which smart contracts can defer various mutations to be handled off chain. Created in conjection with the ENS team, the purpose of this EIP is to standardize a method in which these deferred mutations can be authorized, verified, and executed. One core use case for the Cross Chain Write Deferral Protocol is adding decentralized write support to an off-chain ENS resolver.

### CODE REVIEW

**Comment by 0xpaulio** [comment]
Was I not supposed to assign it the number of the PR? I can revert that if needed

**Comment by Pandapip1** [comment]
> Was I not supposed to assign it the number of the PR? I can revert that if needed

You weren't, but it's fine. It's what I would have assigned anyways.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Anyways, first things first. Please fix the CI errors: https://github.com/ethereum/EIPs/pull/5559/files

**Comment by 0xpaulio** [comment]
@Pandapip1 let me know if anything else needs to be changed, looks like it is all clear on my end

**Review by Pandapip1 — APPROVED** [review]
LGTM - it's a bit bloated but this is fine for a draft

**Pull request merged**
