### PR TITLE
Clarify that drafts are drafts

### PR DESCRIPTION
**Pull request by fulldecent**
I am reviewing a NIST paper that will be citing a lot of our work here.

They, and nearly everyone, are confused by thinking that once something has an issue number here it is a final publication.

This PR helps to dispel that myth.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I'm not directly opposed to merging this, though I don't think it will solve the problem you want to solve.  Fundamentally, I suspect the problem is that people are not reading the readme at all, not that they are reading the readme and it isn't providing enough information.

For example, a mere 20 lines above the new lines is this:
> - [Draft](https://eips.ethereum.org/all#draft) proposals which intend to complete the EIP review process.

We could perhaps reword that to provide a bit more clarity that draft just means "someone formally submitted an idea for an EIP", but I feel like the authors of the papers you are reading simply didn't read that line (or any of the lines most likely) at all.

**Comment by fulldecent** [comment]
I agree.

Possible improvements for README.md:

1. Move Validation, Automerger, Local development to CONTRIBUTING.md
2. Summarize Draft, Last Call, Accepted, Final and Active as "The status page, tracking improvement proposals for the Ethereum platform [LINK]"
3. Remove duplicate "Browse all current...", "Once your first PR is merged..."

This will regain focus on the remaining more relevant parts.

**Comment by MicahZoltu** [comment]
@axic @MadeofTin @lightclient @gcolvin have any thoughts on this?

**Comment by lightclient** [comment]
I support this PR, but I also agree with Micah -- I don't think this will solve the fundamental issue. One potential approach that would help sift out lower quality EIPs would be to have a separate "draft" track (sort of like IETF "Internet Drafts" before RFCs). That way when some actually *became* an EIP, there may actually be more merit behind it.

**Review by lightclient — APPROVED** [review]

**Comment by fulldecent** [comment]
Please merge this PR and then tell me if you would like to see a PR for the above items.

**Comment by MicahZoltu** [comment]
While I'm not directly opposed to this being merged, I also do not think this change offers any value.  If another editor wants to merge it, I won't stand in the way, but I also won't merge it myself as-is.

Generally speaking, more text is worse than less text, and any addition of text should provide enough value to overcome that axiom.  In this case, I don't believe that this additional text is adding any meaningful value (for the reason I stated above) so I have a mild preference to not add it.

**Comment by Souptacular** [comment]
I have similar opinions to @MicahZoltu because I feel that your propsed text doesn't solve the core issue, but I'm not the type of person doing NIST paper reviews. If you feel it will truly help then I'm okay merging it. We can always undo it fairly easily once things improve and we merge other things from [this comment](https://github.com/ethereum/EIPs/pull/3065#issuecomment-713810591) (if we decide to merge any of them). I'll merge this issue now.

**Comment by fulldecent** [comment]
Thank you. Related item. Last chance, please tell me if you'd like to see a PR for:

https://github.com/ethereum/EIPs/pull/3065#issuecomment-713810591

I'm in a fixing things mood.

**Comment by MicahZoltu** [comment]
@fulldecent There is work being planned to consolidate/normalize multiple different pages that currently contain duplicate information, and including the README, EIP-1, eips.ethereum.org, and ethereum.org/eips.  I would recommend holding off on making substantive changes to any of those at the moment until stuff is consolidated as any changes you make may get lost or blown away in that process.

**Comment by fulldecent** [comment]
Got it. My plan *was* to nuke everything. Currently only 24 pages on the internet link to https://ethereum.org/en/eips/ versus 32k to eips.ethereum.org. So the former can be redirected.

For other pages as well I have arguments to remove most of everything.

**Comment by BrentAllsop** [comment]
Hi William  @fulldecent.  This is all exciting information about some critically important stuff that needs to be done.  What can I do to help with any of this?

**Comment by fulldecent** [comment]
Thank you. Please see https://github.com/apple/swift-evolution and https://apple.github.io/swift-evolution/

These are a great model of change management.

Then the only thing I need help with is getting some people to agree that is better than what we have. Once we have that I can make some PRs, they get merged, and then we all go back our schedulers for the next thing to work on.

**Comment by BrentAllsop** [comment]
Yea, that [swift evolution process](https://github.com/apple/swift-evolution/blob/main/process.md) looks like great stuff.

I would love to help with “Getting people to agree that is better.”  What, exactly are you referring to here?  Just the management of the canonical EIP URL information being talked about here, or more than that?  For example, there are states mentioned in the swift evolution process document are quite different than the states in EIP 1.

**Pull request merged**
