### PR TITLE
EIP 665 updates

### PR DESCRIPTION
**Pull request by oberstet**
this brings the text in line with the 3 PRs for clients, and improves the text rgd motivation

### CODE REVIEW

**Comment by nicksavers** [comment]
@oberstet As a draft this EIP seems ready to merge. If you want to tweak some things you can also update it with a PR afterwards.

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 665 requires approval from one of (tobias.oberstein@crossbario.com)

**Comment by oberstet** [comment]
@nicksavers yep, I added some last things, so ready for merge from my side. thanks!

**Comment by Arachnid** [comment]
In future, if you either change the author line to contain your github username in (parentheses), or make sure your email address is public on your GitHub profile, the bot will automatically merge your pr for you.

**Comment by oberstet** [comment]
@Arachnid aaah. thx for explaining;) I didn't get the blurbs from the bot ..

**Pull request merged**
