### PR TITLE
Re-order EIP categories

### PR DESCRIPTION
**Pull request by timbeiko**
Put Meta EIPs before Informational EIPs in EIP-1 given that Meta EIPs are more numerous/popular/common/etc. than Information EIPs

### CODE REVIEW

**Comment by timbeiko** [comment]
Not sure why the tests aren't passing here... the latest build shows them passing: https://travis-ci.org/ethereum/EIPs/builds/527883621

**Comment by nicksavers** [comment]
Seems fine to me
Don't forget https://github.com/ethereum/EIPs/blob/master/eip-X.md

**Comment by timbeiko** [comment]
@nicksavers good catch! Updated

**Comment by kris30pl** [comment]
I have Access to where you never been a create reputation which you never had and i destroy them they hacked long Time ago my account i lost money for a treatment my patient she die her name was Ewelina mother die father alcoholic she didint had anyone treatment was not refund in Poland think want do you want i do what this with you or without

**Pull request merged**
