### PR TITLE
Mark EIP-695 as Final

### PR DESCRIPTION
**Pull request by sorpaas**
https://github.com/ethereum/EIPs/pull/2356#issuecomment-563025007

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 695 state from Last Call to Final

**Comment by BelfordZ** [comment]
@sorpaas could you please include the following API specification?

```json
{ 
   "name": "eth_chainId", 
   "summary": "Returns the currently configured chain id", 
   "description": "Returns the currently configured chain id, a value used in replay-protected transaction signing as introduced by [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).", 
   "params": [], 
   "result": { 
     "name": "chainId", 
     "description": "hex format integer of the current chain id. Defaults are ETC=61, ETH=1, Morden=62.", 
     "schema": { 
       "title": "chainId", 
       "type": "string", 
       "pattern": "^0x[a-fA-F\\d]+$" 
     } 
   } 
 }
```

**Comment by sorpaas** [comment]
Ping editors as I got asked that there're other EIPs depending on this.

**Comment by axic** [comment]
I think there are still some unsolved comments on the discussion URL.

**Comment by rekmarks** [comment]
@axic Security considerations section added in: #2642

**Comment by rekmarks** [comment]
@axic, I believe that all outstanding items have been addressed as of this morning, Pacific Time.

**Comment by rekmarks** [comment]
@axic, do the editors need anything else from the authors before this can be merged?

**Comment by rekmarks** [comment]
## Summary of Last Call Issues

- The meaning of the "currently configured `CHAIN_ID`" should be further specified
  - Raised [here](https://ethereum-magicians.org/t/eip-695-create-eth-chainid-method-for-json-rpc/1845/20)
  - Addressed in #2625 
- The behavior in absence of `CHAIN_ID` should be specified
  - Raised [here](https://ethereum-magicians.org/t/eip-695-create-eth-chainid-method-for-json-rpc/1845/20)
  - Addressed in #2629
- A "Security Considerations" section should be added
  - Raised [here](https://ethereum-magicians.org/t/eip-695-create-eth-chainid-method-for-json-rpc/1845/23)
  - Addressed in #2642

In addition, formatting issues were fixed in:
  - #2627 
  - #2643 

To the best of my knowledge, those were the only issues flagged by editors, or considered necessary to address by the authors.

cc: @Arachnid

**Pull request merged**
