### PR TITLE
Update EIP-2255: Move to Last Call

### PR DESCRIPTION
**Pull request by Pandapip1**

### CODE REVIEW

**Review by SamWilsn — COMMENTED** [review]
The Security Considerations section is incomplete and should be completed before moving to last call.

**Comment by Pandapip1** [comment]
Thought I checked that. Oops.

**Comment by Pandapip1** [comment]
https://github.com/ethereum/EIPs/pull/6564 will be merged. Requesting re-review.

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
