### PR TITLE
Update EIP-7503: Move to Draft

### PR DESCRIPTION
**Pull request by 0xwormhole**
The changes proposed to EIP-7503 are as follows. I have omitted the cryptographic details, as I lack expertise in that field. However, my changes are meant to provide the Ethereum developer with a basic structure that they should consider when working on the full implementation.

🪱🕳️

### CODE REVIEW

**Comment by irnb** [comment]
@0xwormhole Thank you for your contribution ! 
I need some time to review and go through the suggestions you’ve provided. I’ll submit my review within three days.

**Review by keyvank — APPROVED** [review]
This is very cool, thanks!

**Comment by irnb** [comment]
@keyvank 

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4563364

I think it's something handled in offchain, people could provide it to prove they are not part specific mint transactions or etc (non inclusion proof)

@0xwormhole 
Please correct me if I’m mistaken.

**Comment by 0xwormhole** [comment]
@irnb @keyvank I added a reference to the EIP. Companies like 0xbow can maintain these roots, also there have been historically created lists of "known bad events" by ethereum ecosystem security teams, and we can use automated mechanisms to exclude coins related to these incidents.

This mechanism is entirely voluntary; a withdrawer could always create and use a "universal root" that includes all historical transactions. However, the goal of explicitly including the privacy pool root feature is to make it nearly cost-free for users to adopt a root that excludes hacks and other coins that they want to refuse to associate with. This is a show of good faith of the ecosystem's commitment to not supporting behavior universally considered criminal, and gives users tools to satisfy local compliance needs like convincing exchanges that their source of funds is not suspicious.

**Comment by keyvank** [comment]
@0xwormhole I like it! Let's have it.

**Review by irnb — APPROVED** [review]

**Review by g11tech — APPROVED** [review]
approving since approced by @keyvank one of the authors

**Comment by 0xwormhole** [comment]
@g11tech @eth-bot when running the GitHub workflow for this pull request, an issue is occurring. If there's anything wrong, could you investigate? It would be great if you could merge this pull request. Thank you!

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
