### PR TITLE
Change EIPs status based on ACD Call #67

### PR DESCRIPTION
**Pull request by timbeiko**
Agenda: https://github.com/ethereum/pm/issues/116
Livestream: link: https://www.youtube.com/watch?v=fJd_xYnYrUU1

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1679 requires approval from one of (@5chdn, @axic)

**Comment by timbeiko** [comment]
Updated the EIP to use `Istanbul 1` and `Istanbul 2` similarly to the geth tracker: https://github.com/ethereum/go-ethereum/issues/19919

**Comment by axic** [comment]
> Updated the EIP to use Istanbul 1 and Istanbul 2 similarly to the geth tracker:

Is this necessary? Can't see this reflected in the meeting notes under decision.

**Comment by timbeiko** [comment]
@axic it was to avoid confusion. I'm not sure what is least confusing at this point: a whole bunch of EIPs in "Tenatively Accepted", or having the breakdown. In the call, the consensus seemed to be that all the EIPs moved to Tentatively Accepted would be for a later fork, given how far we are in the process for the October one, but it wasn't clear cut and the notes don't reflect that. 

I'm fine with merging either commit, but IMO it's best to have the EIP reflect the latest information. If it's easier to link back to the notes and just bundle all the EIPs in Tentatively Accepted, then let's do that.

**Pull request merged**
