### PR TITLE
Revert EIP-2159 to draft

### PR DESCRIPTION
**Pull request by fulldecent**
Last call is long overdue

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 2159 state from Last Call to Draft
 - EIP 2159 requires approval from one of (@ajsutton)

**Comment by fulldecent** [comment]
@nicksavers requesting merge please

**Comment by axic** [comment]
It seems this turned into final since via #2829.

@fulldecent what was your reasoning?

@MicahZoltu @lightclient @Souptacular any opinions?

**Comment by ajsutton** [comment]
Why are we switching back to draft? It's been implemented and shipped for a long time now. I know there was some disagreement over how in detail the backwards compatibility section should be but since it's a completely optional EIP for clients to implement I struggle to see how more time in draft is going to help.  And since it's been shipped and stable for so long I don't see any benefit to making changes either because that will just introduce more backwards compatibility issues.

**Comment by axic** [comment]
This request was made 7 months before #2829.

**Comment by ajsutton** [comment]
True, but I'd have had the same disagreements then. And largely did on ETH Magicians.

**Comment by axic** [comment]
Could you leave a link to the discussion this disagreement was handled for reference?

**Comment by ajsutton** [comment]
To be clear, I completely missed seeing this PR when it came it so never directly addressed it. However in December the request to revert to draft was made in the discussion thread (https://ethereum-magicians.org/t/erc-2159-common-chain-metrics/3415/15) which I opposed.

**Comment by MicahZoltu** [comment]
My position remains the same as in my comment on the discussion-to thread.  Ultimately, it is up to the author whether to merge to final or not as long as the EIP is structurally sound and contains all of the basic required information.  While I encourage people to heed community feedback, I have a strong dislike of things getting stuck forever because the author disagrees with some feedback that was received.

**Comment by fulldecent** [comment]
And also my position remains that a two-week review should be restricted to two weeks. After that time it should be reverted to draft or marked as abandoned.

However I am a practical person and there is no benefit in debating a publication that has been marked as final. So closing this PR.

**Pull request closed without merging**
