### PR TITLE
EIP: I2P Integration (optional)

### PR DESCRIPTION
**Pull request by lght**
Add the optional ability for Ethereum clients to connect to, and communicate with, full nodes inside the I2P network.

### CODE REVIEW

**Comment by Silur** [comment]
this sounds like the violation of both philosophies, first you want to tunnel a p2p network on it's own into a darknet (which is I2P by design), then ovecome this isolated subnet problem with clearnet bridges which goes against common usecase (I know there ARE proxies but i2p was just not meant for this). Tor would seem a more logical choice here for it's not a full-featured separate darknet but rather an anon layer on top of an existing one

**Comment by lght** [comment]
@Silur that does make sense, and thanks for the feedback. 

I agree parts of this proposal felt kludge-y. Is the devp2p what your referring to when you say p2p doesn't make sense over a darknet? If so, I agree to a certain extent, but isn't Whisper attempting to build a "darknet" of sorts for Dapp comms? My thinking here is that i2p can handle the base networking stuff (discovery, relaying txes, syncing), and p2p-specific comms can use Whisper either over clearnet or over i2p.

I was mostly thinking of this being a way for clients to send transactions and sync without exposing their location via IP. Tor would be nice as an overlay network, unfortunately it does not support UDP communication. If discovery and other UDP comms could be tunneled through TCP that would solve the one issue, but Tor has notorious issues with networked apps using UDP (see bit torrents).

It would also be nice if there was a way for miners to interact anonymously. This would give them some extra protection against censorship (where and when it matters). I'm totally open to suggestions on how to achieve this, just that Tor is definitely a less suitable option than I2P.

Really the bridge nodes and full nodes could be the same box. So the node would sync and communicate normally over the clear, and any comms relayed from i2p SAM/BOB bridge get sent over i2p to a listening node on the other side. Then ethereum clients would just need to implement the SAM/BOB protocol to send the data/commands/messages they want anonymized over this encrypted channel. This seems (in part) to be exactly what the SAM/BOB protocols were meant to address.

Revisiting the clearnet bridges themselves, these are used fairly frequently in i2p, IIRC. There are jumper sites in the clear, and dual hosts that are clearnet and i2p addressable. Those jumper hosts themselves are not anonymous, but provide an entry into the i2p network. Bridges are not exactly necessary either, there just needs to be a way to keep the i2p full nodes in consensus. 

If i2p wasn't designed for supporting a p2p network, what are your opinions of the Kovri project from Monero?

Even if Tor was usable (it isn't without a ton of reworking Ethereum's networking to be solely over TCP), how would a Tor full node communicate anonymously with clearnet nodes to make sure the Tor full node is in consensus with the rest of the network?

**Comment by Silur** [comment]
I am familiar with kovri for I'm working with the monero research team too, and I'm against clearnet proxies on that line (you can read my proposal about verifiable shuffles on the IRC log).
Your point with UDP is valid, and if the two networks are "merged" by default this could work, but pesonally I rather prefer an orthogonal design like a tunnel tool instead of making it part of the client but let's hear other developer's opinion on this for I'm known to be user unfriendly :)

**Comment by lght** [comment]
> `<silur>` I'm working on a quantum-hard shuffle that can be used to construct PRNG-s
`<suraeNoether>` silur: freaking awesome.

100% ^^ w/ suraeNoether, this is freaking awesome. when can I read your paper?

**Comment by Silur** [comment]
in a month or two hopefully

**Comment by Arachnid** [comment]
This is a courtesy notice to let you know that the format for EIPs has been modified slightly. If you want your draft merged, you will need to make some small changes to how your EIP is formatted:

 - Frontmatter is now contained between lines with only a triple dash ('---')
 - Headers in the frontmatter are now lowercase.

If your PR is editing an existing EIP rather than creating a new one, this has already been done for you, and you need only rebase your PR.

In addition, a continuous build has been setup, which will check your PR against the rules for EIP formatting automatically once you update your PR. This build ensures all required headers are present, as well as performing a number of other checks.

Please rebase your PR against the latest master, and edit your PR to use the above format for frontmatter. For convenience, here's a sample header you can copy and adapt:

```
---
eip: <num>
title: <title>
author: <author>
type: [Standards Track|Informational|Meta]
category: [Core|Networking|Interface|ERC] (for type: Standards Track only)
status: Draft
created: <date>
---
```

**Comment by axic** [comment]
@lght are you still interested in this?

**Comment by nicksavers** [comment]
Closing for lack of activity. Ideas to improve networking are always welcome. Since this particular proposal didn't seem to get any proposal, I'm closing it for now. @lght Feel free to correct me and show me whether I missed any progress on this.

**Pull request closed without merging**
