### PR TITLE
Fix spelling mistakes detected by newer codespell

### LINKED ISSUE #2674: CI fails for all builds due to current state of master
CI currently fails for all builds due to the content of `master`. I say "content" because I don't believe that all things flagged as errors are in fact errors. This is preventing automatic approval and merging all otherwise eligible PRs, e.g.: https://github.com/ethereum/EIPs/pull/2673

Example: https://travis-ci.org/github/ethereum/EIPs/jobs/692012828
Relevant part of CI logs:
```
+codespell -q4 -I .codespell-whitelist eip-X.md EIPS/
EIPS/eip-1491.md:70: iam ==> i am, aim
EIPS/eip-1491.md:473: iam ==> i am, aim
EIPS/eip-1930.md:91: interepreting ==> interpreting
EIPS/eip-1753.md:143: ACN ==> CAN, ACNE
EIPS/eip-1155.md:573: Espace ==> Escape
EIPS/eip-1155.md:574: espace ==> escape
EIPS/eip-2333.md:71: stings ==> strings
EIPS/eip-1581.md:13: keypairs ==> key pairs
EIPS/eip-107.md:98: invisble ==> invisible
EIPS/eip-1613.md:89: keypair ==> key pair
EIPS/eip-758.md:72: notificaitons ==> notifications
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #2674.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - File .codespell-whitelist is not an EIP
 - EIP 107 requires approval from one of (@wighawag)
 - EIP 1581 requires approval from one of (@bitgamma)
 - EIP 1613 requires approval from one of (alex@tabookey.com, dror@tabookey.com, @yoav-tabookey)
 - EIP 1930 requires approval from one of (@wighawag)
 - EIP 2333 requires approval from one of (@carlbeek)
 - EIP 758 requires approval from one of (@tinybike)

**Comment by axic** [comment]
This is needed to bring `master` back to operational state.

@nicksavers @Arachnid @Souptacular @gcolvin anyone wants to approve/merge?

**Comment by rekmarks** [comment]
As an author of 1193, I want to second @axic's call for merging this. We're at the end of our review period and need to get a final set of changes merged ASAP.

**Comment by Arachnid** [comment]
Can we please disable spellcheck as a required part of the build? It's absurd that a spelling error in one EIP can break the whole build - and since spell checkers have false positives, it shouldn't be required.

**Comment by rekmarks** [comment]
I'll chime in to say that the `codespell` check seems fine to me on paper so long as it doesn't prevent the repo from functioning normally. I'd be willing to help write docs for contributors on how to deal with it, but I'm not sure where to put them.

Also, we unfortunately seem to have missed one failure: https://github.com/ethereum/EIPs/pull/2691

**Pull request merged**
