### PR TITLE
Turn EIPs repository into a Github Pages / Jekyll site

### PR DESCRIPTION
**Pull request by Arachnid**
This PR restructures the EIPs repository so merged EIPs can be parsed as Jekyll documents, and adds structure and configuration to render it as such. A preview of the generated site can be seen [here](http://arachnid.github.io/EIPs/).

Changes to the already-committed EIPs:
 - Add '---' on lines before and after the header data for each EIP, making them valid YAML prologues.
 - Change header names to be lower case.
 - Standardise names and values in EIPs that did not match conventions described by EIP-1.

In addition, this PR includes a few changes to EIP-1:
 - Changing header names to match the changes made to each EIP.
 - Incorporating new header entries that were specified in the template but not EIP-1.
 - Adding the requirement for '---' either side of header entries.

The template eip-X has also been updated to reflect these changes.

Next steps (after this PR):
 - Set up a CNAME for eips.ethereum.org
 - Link to the new page from the README, and direct people there for reference and for canonical URLs.
 - Add travis build to automatically check PRs for validity.
 - Open discussion about changes to the EIP draft/merge/update process.

### CODE REVIEW

**Comment by Arachnid** [comment]
@jamesray1 Should be fixed now, though I'll take it down again once it's up and running on its permanent URL.

**Comment by tjayrush** [comment]
Excellent. Categorize this as an Ethereum Improvement Proposal that helps everyone better understand what's going on.

**Comment by jamesray1** [comment]
@Arachnid awesome, the preview looks great!

**Comment by jamesray1** [comment]
Oh, the link to the template EIP doesn't work.

http://arachnid.github.io/EIPs/

https://github.com/ethereum/EIPs/blob/master/eip-X

**Comment by jamesray1** [comment]
It needs to have .md on the end of this, this works: 
https://github.com/ethereum/EIPs/blob/master/eip-X.md.

**Comment by Arachnid** [comment]
@jamesray1 Fixed in my outstanding PR, thanks for spotting it.

**Comment by jamesray1** [comment]
You're welcome Nick!

**Pull request merged**
