### PR TITLE
EIP status and content changes 

### PR DESCRIPTION
**Pull request by GrandGarcon**
I am co-author of the EIP-3475 (along with @dr-chain  , @yuliu-debond  , @drikssy  @Edoumou , @toufic ) and i wanted to first change the status to 'last call' with some rectification of mistakes along with integration of paragram describing the lmetadata of the bonds for the frontend .

### CODE REVIEW

**Comment by GrandGarcon** [comment]
Sorry i will be closing this due to the violation of the issue that PR's are to be done only via Origin:sideBranch and not directly from the master  branch

thus i  will recreate new one  , but keeping changes for same EIP.

**Comment by MicahZoltu** [comment]
You *should* be submitting a pull request against `master`, not against some branch.

**Comment by GrandGarcon** [comment]
yes i know  actually the merge will be  done in the order  ethereum:master <--  Username:username-patch-1 , not of the order 

ethereum:master <--  Username:master.

 and should this be incorporated as changes in the same EIP  in which we are doing changes ?

**Comment by MicahZoltu** [comment]
The branch management scheme on your fork can be whatever you want.  You can do `ethereum:master <-- <username>:master` or `ethereum:master <-- <username>:whatever-you-want`.

**Comment by MicahZoltu** [comment]
What you had here was fine.

**Comment by GrandGarcon** [comment]
thanks ,

Ok then for now we plan to add another commit after review from  the Author @yuliu-debond  and then finally will like to have reviews from the EIP team

**Pull request closed without merging**
