### PR TITLE
EIP2981 status changed to 'Final' ✍️

### PR DESCRIPTION
**Pull request by blmalone**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by MicahZoltu — CHANGES_REQUESTED** [review]
Please change the title of the Discussions To issue to "Discussion for EIP-2981: NFT Royalty Standard".

**Comment by blmalone** [comment]
Sure, I don't have permissions to do that. I've reached out to @VexyCats.

**Comment by VexyCats** [comment]
Changed the title! Thanks

**Comment by blmalone** [comment]
@MicahZoltu as requested the title has been changed. Can we get this merged?

**Comment by MicahZoltu** [comment]
I don't review ERCs, so you'll have to wait for one of the other editors to handle it.  I just noticed that discrepancy when glancing at it and thought I would mention it so you had a head start in case that was the only issue.  😄

**Review by lightclient — APPROVED** [review]

**Comment by alita-moore** [comment]
@MicahZoltu should we prevent the bot from passing because you didn't approve yet / requested changes before lightclient approved?

**Comment by MicahZoltu** [comment]
No, any editor reviewing should merge I think.  Editor review is "you need one editor to approve" not a voting system.  😄

**Review by Chucky-ux — COMMENTED** [review]
Send to windows C:

**Comment by alita-moore** [comment]
I think I've asked this before.. but that makes sense

**Pull request merged**
