### PR TITLE
Update EIP-7069: clarify EOF vs 7069 interactions

### PR DESCRIPTION
**Pull request by pdobacz**
Clarifications after feedback received on R&D discord

### CODE REVIEW

**Comment by chfast** [comment]
LGTM

**Review by shemnon — APPROVED** [review]

**Comment by KARINACAREPOTO** [comment]
> Clarifications after feedback received on R&D discord

Confirmo

**Review by KARINACAREPOTO — APPROVED** [review]

**Comment by KARINACAREPOTO** [comment]
> ✅ All reviewers have approved.

Confirma

**Comment by KARINACAREPOTO** [comment]
> LGTM

Confirma

**Comment by KARINACAREPOTO** [comment]
> ✅ All reviewers have approved.

Confirma

**Pull request merged**
