### PR TITLE
EIP-777: pngcrush assets

### PR DESCRIPTION
**Pull request by wchargin**
These simple PNG images were bafflingly big: like, 16.8 MB for a
single-color 2048p image. This patch shrinks the total repository size
from 152 MB to 45 MB.

Generated with:

    for f in assets/eip-777/logo/png/*.png; do pngcrush -ow "$f"; done

using pngcrush 1.8.13.

Passing each file through `convert - rgba:-` before and after this patch
shows that the raw pixel data is unchanged.

(The no-op change EIP-777 itself is to appease the automerge bot.)

wchargin-branch: eip-777-pngcrush

### CODE REVIEW

**Review by Pandapip1 — APPROVED** [review]

**Comment by Pandapip1** [comment]
@SamWilsn I request a manual merge.

**Comment by SamWilsn** [comment]
Unless you're doing a shallow clone, this won't change the size of the repository, right? What's the point of doing this without re-writing history?

**Comment by Pandapip1** [comment]
> Unless you're doing a shallow clone, this won't change the size of the repository, right? What's the point of doing this without re-writing history?

Oftentimes people do use shallow clones.

**Review by SamWilsn — APPROVED** [review]

**Comment by wchargin** [comment]
> Unless you're doing a shallow clone, this won't change the size of the repository, right?

Correct. (I guess to be more precise I might have said that it reduces
the total size of the *tree* rather than the repository.)

> What's the point of doing this without re-writing history?

Aside from shallow clones (which I'll use if cloning a repository is
taking a while and I just need to write a quick patch), the EIP-777 text
directs readers to use the assets in this directory. So, to the extent
that anyone does this, it seems nice to have reasonably sized images.

In any case, thanks for merging!

**Pull request merged**
