### PR TITLE
CI: Warn on extra sections

### PR DESCRIPTION
**Pull request by Pandapip1**
Uses the new deny/warn/allow system.

### CODE REVIEW

**Comment by SamWilsn** [comment]
May I ask why we're switching to warnings?

**Comment by Pandapip1** [comment]
> May I ask why we're switching to warnings?

* Some external links are now allowed
* EIP-1 doesn't say that you can't use sections not defined in EIP-1

**Comment by SamWilsn** [comment]
> * Some external links are now allowed

Those exceptions are already supported:

https://github.com/ethereum/eipw/blob/4e4bc7b50a094ea9b02551113780b380a096120d/eipw-lint/src/lib.rs#L360-L363

> * EIP-1 doesn't say that you can't use sections not defined in EIP-1

While true, I'm not convinced we should allow extra sections without specific editor approval?

**Comment by Pandapip1** [comment]
>  I'm not convinced we should allow extra sections without specific editor approval?

Agreed, but on the other hand I'm not convinced that we should require a manual merge to allow extra sections.

**Comment by Pandapip1** [comment]
@SamWilsn

**Review by SamWilsn — CHANGES_REQUESTED** [review]
If we want to allow extra sections, that's a whole discussion, but I'm firmly against allowing out-of-order sections.

**Comment by Pandapip1** [comment]
I too am firmly against out of order sections. Might it be possible to separate those two lints?

**Comment by Pandapip1** [comment]
@SamWilsn see my previous question

**Pull request closed without merging**
