### PR TITLE
EIP 721 : Metadata Signature Extension

### PR DESCRIPTION
**Pull request by claytantor**
Recently Tim Schneider, from Artnet posted a great story about how a whitehat hacker managed to trick the blockchain into forging tokens that would forge the Provenance of the originator of the NFT to look as though it was the originating artist.

[NFT Theft](https://news.artnet.com/opinion/sleepminting-nftheft-monsieur-personne-1960744)

I have added a proposal outlined in the article [Solving For Sleepminting](https://claytantor.wordpress.com/2021/04/22/solving-for-sleepminting/)

* Add md5 hash
* Metadata must be unique for token
* sha256 sig as base64 field
* Artist must publish public key

### CODE REVIEW

**Comment by MicahZoltu** [comment]
This EIP is final, which means it can not have any normative changes made to it.  If you would like to introduce these changes, you will need to create a new EIP.  That EIP can depend on this EIP if you like, but it needs a new number and everything otherwise filled out like a brand new EIP.

**Comment by claytantor** [comment]
Gotcha. Will do!

**Comment by claytantor** [comment]
> This EIP is final, which means it can not have any normative changes made to it. If you would like to introduce these changes, you will need to create a new EIP. That EIP can depend on this EIP if you like, but it needs a new number and everything otherwise filled out like a brand new EIP.

 @MicahZoltu  Gotcha. Will do! Do you mind showing me an example of someone doing this so I can do it correctly?

**Comment by MicahZoltu** [comment]
Sorry for the delay, looks like you figured things out though?  (#3542)

**Pull request closed without merging**
