### PR TITLE
Update EIP-5219: Move to Last Call

### PR DESCRIPTION
**Pull request by Pandapip1**

### CODE REVIEW

**Comment by Pandapip1** [comment]
@SamWilsn fixed

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
> How do you encode query parameters in the resource? You don't specify. Would it be something like ["foo", "bar", "?hello=world"] or ["foo", "bar?hello=world"]? Is this something that would be left up to the contract?

I forgot that stuff existed... I'll add a parameter for that.

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
