### PR TITLE
Updated EIP-1261 based on User Comments

### PR DESCRIPTION
**Pull request by chaitanyapotti**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by chaitanyapotti** [comment]
How do I merge this.?

**Comment by chaitanyapotti** [comment]
Some admin, please merge this to the master branch

**Comment by axic** [comment]
@chaitanyapotti I don't think this is the right way to do it, in this PR you are adding two new EIP files. How were the numbers assigned to them?

**Comment by chaitanyapotti** [comment]
@axic I created issues for both the eips and the number here is the issue number.
I couldn't create a new pr because this wasn't accepted yet and everything just merged into this pr.

**Pull request closed without merging**
