### PR TITLE
[EIP-1474] Fix  curl examples for eth_getUncleByBlockHashAndIndex and eth_getUncleByBlockNumberAndIndex

### PR DESCRIPTION
**Pull request by abdelhamidbakhta**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1474 requires approval from one of (@bitpshr, rekmarks@protonmail.com)

**Comment by MicahZoltu** [comment]
cc @rekmarks (probably good to get the Author line in this EIP switched over to a GitHub user name so mentions work properly)

**Comment by rekmarks** [comment]
@MicahZoltu thank you for pinging me. I opened #3061 per your suggestion!

**Review by rekmarks — APPROVED** [review]
LGTM!

**Comment by MicahZoltu** [comment]
Bot didn't auto-merge this because the approver wasn't technically an author (per the bot's heuristics) on the branch, but they were added later (after this PR was created).

**Pull request merged**
