### PR TITLE
Update EIP-7600: Delete EIPS/eip-7212.md

### PR DESCRIPTION
**Pull request by SamWilsn**
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by ulerdogan — APPROVED** [review]
Thanks for applying the changes. Can you also consider removing related assets under `assets/eip-7212`? Opened [a PR](https://github.com/ethereum/EIPs/pull/8781) for that.

**Comment by g11tech** [comment]
> Thanks for applying the changes. Can you also consider removing related assets under `assets/eip-7212`? Opened [a PR](https://github.com/ethereum/EIPs/pull/8781) for that.

i think assets also need to be deleted in same PR to make CI pass

**Comment by ulerdogan** [comment]
> > Thanks for applying the changes. Can you also consider removing related assets under `assets/eip-7212`? Opened [a PR](https://github.com/ethereum/EIPs/pull/8781) for that.
> 
> i think assets also need to be deleted in same PR to make CI pass

My PR aims this PR's branch to delete the assets, so it can make CI pass after it's merged. @g11tech

**Comment by g11tech** [comment]
> > > Thanks for applying the changes. Can you also consider removing related assets under `assets/eip-7212`? Opened [a PR](https://github.com/ethereum/EIPs/pull/8781) for that.
> > 
> > 
> > i think assets also need to be deleted in same PR to make CI pass
> 
> My PR aims this PR's branch to delete the assets, so it can make CI pass after it's merged. @g11tech

PR won't be merged if any of the branches don't pass the CI, so both deletions need to be in same PR i guess

**Comment by ulerdogan** [comment]
> > > Thanks for applying the changes. Can you also consider removing related assets under `assets/eip-7212`? Opened [a PR](https://github.com/ethereum/EIPs/pull/8781) for that.
> > 
> > 
> > i think assets also need to be deleted in same PR to make CI pass
> 
> My PR aims this PR's branch to delete the assets, so it can make CI pass after it's merged. @g11tech

Ah understood, yes. I assume @SamWilsn is able to merge the PR, even if the CI does not pass. I wanted to help him by preparing the PR, thinking it's not dangerous as it's him branch.

**Pull request merged**
