### PR TITLE
Delete copy in repository root

### PR DESCRIPTION
**Pull request by fulldecent**
Reference and authorization from https://github.com/ethereum/EIPs/issues/1736#issuecomment-460895370

Requesting manual assistance please @nicksavers

### CODE REVIEW

**Comment by cohabo** [comment]
Recommend that you move the EIP1491 from root repository to the EIP repository in the master branch.

**Comment by fulldecent** [comment]
Updated PR. This is now a move. Should be ready to go.

**Comment by axic** [comment]
I think this has been done in #1764.

**Comment by nicksavers** [comment]
> I think this has been done in #1764.

**Pull request closed without merging**
