### PR TITLE
Add EIP-6065: EIP Real Estate Standard Token

### PR DESCRIPTION
**Pull request by Alex-Klasma**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by Theo6890** [comment]
[REPOST from Discord server]

We concluded the same back then at @Omnia-DeFi that you need to create an SPV that owns the house and then sell NFT of the SPV. 
Otherwise, turning the house into an NFT itself is a way more heavier legal process https://twitter.com/KlasmaLabs/status/1571907145385517058?s=20&t=DhKo7sAMZsMFQy-zn7jeNg

Then the question is why choosing ERC-721 and not ERC-1155?

As you can have many types of shares, ERC-1155 might better suited as you can mint many times the same amount of the same share (same id). Obviously if you own some share you will have more rights than others, meaning a different access.
Then, you can even leverage IPFS submarine and give access based on an ERC-1155 id instead

**Comment by dfalloncyr** [comment]
@Pandapip1 thanks for updating the title. Looks like everything else has passed, are you able to merge at this point? Please let @Alex-Klasma or I know if there is anything else needed from us!

**Comment by Pandapip1** [comment]
Re-running CI.

**Comment by Pandapip1** [comment]
For some extremely odd reason all the CI is failing. @Alex-Klasma mind reviewing my (mostly formatting) changes

**Comment by dfalloncyr** [comment]
@Pandapip1 @Alex-Klasma under: failed check, details, summary it reads...The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

Not sure what the cause of that could be...if it's our side or yours?

**Comment by Alex-Klasma** [comment]
That's really strange, I just signed up for this Github account for this project, and I've generally never paid for GH before. Surely you don't need a paid plan to merge into this repo...? Maybe try again now that I've logged into this account? Been a few weeks I guess.

Thanks for the help and for trying to get this merged!

**Review by Pandapip1 — APPROVED** [review]
Lgtm if ci passes

**Comment by dfalloncyr** [comment]
Thanks for you help and review @Pandapip1!

**Comment by Pandapip1** [comment]
Np!

**Pull request merged**
