### PR TITLE
Remove external links in non-conforming EIPs

### PR DESCRIPTION
**Pull request by lightclient**
Per #2648, I'm removing links to external images and instead placing them in the proper `/assets` directory.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - File assets/eip-1175/wallet.png is not an EIP
 - File assets/eip-1175/workflow.png is not an EIP
 - File assets/eip-1438/avatar.png is not an EIP
 - File assets/eip-1438/intro.png is not an EIP
 - File assets/eip-1438/wallet.png is not an EIP
 - File assets/eip-1613/sequence.png is not an EIP
 - EIP 1175 requires approval from one of (@nitro888)
 - EIP 1438 requires approval from one of (@nitro888)
 - EIP 1613 requires approval from one of (alex@tabookey.com, dror@tabookey.com, @yoav-tabookey)

**Comment by lightclient** [comment]
Hi @Nitro888 and @yoav-tabookey, please take a moment to review my changes to your EIP. I've simply downloaded the images linked in the EIP document and placed in the in the `/assets` directory.

**Comment by MicahZoltu** [comment]
I'm not sure why this didn't auto-merge when @yoav-tabookey approved.  Going to manually merge for now and we can figure out the bot problem later.

**Comment by axic** [comment]
> I'm not sure why this didn't auto-merge when @yoav-tabookey approved.

Because two more EIPs were affected and those people did not approve and it also changed files outside of the EIPs, as evidenced by the bots message: https://github.com/ethereum/EIPs/pull/2753#issuecomment-650378177

**Comment by MicahZoltu** [comment]
Ah wow, I must have been totally out of it when I looked at this PR.  😳  Will try to do better at reading comprehension in the future.

**Pull request merged**
