### PR TITLE
Update EIP-2982: fix table displaying error

### PR DESCRIPTION
**Pull request by cocoyeal**
Before:

image

After:

image

### CODE REVIEW

**Comment by bumblefudge** [comment]
This makes the relevant table more conformant/proper markdown but I think it's rendering OK as-is in some browsers?
Chrome:
image
Edge:
image
Firefox:
image

**Comment by xinbenlv** [comment]
Hi thank you @cocoyeal  this is xinbenlv an EIP editor here. We discussed this on https://github.com/ethcatherders/EIPIP/issues/337 but it seems there is no rendering issue as shown by https://github.com/ethereum/EIPs/pull/8607#issuecomment-2150628223. I think we can close this PR unless @cocoyeal  can provide instruction to reproduce the issue.

**Comment by bumblefudge** [comment]
image

OP is correct that the Github markdown renderer is stricter than what the browsers are doing, not sure if that's important to the EIP editors, tho?

**Comment by cocoyeal** [comment]
@xinbenlv @bumblefudge Hi sir, yes, the rendering issue occurs to the EIP file on Github, as my original screenshot shows.

**Comment by g11tech** [comment]
> @xinbenlv @bumblefudge Hi sir, yes, the rendering issue occurs to the EIP file on Github, as my original screenshot shows.

the problem is other fixes need to be applied to the EIP for the CI to pass since CI rules have changed since this EIP was added

**Review by Mortiemi — APPROVED** [review]

**Comment by SamWilsn** [comment]
Merged since this shouldn't be controversial and only affect formatting.

**Pull request merged**
