### PR TITLE
EIP-225: mark Clique engine status as final

### PR DESCRIPTION
**Pull request by soc1c**
This changes the status of the clique EIP to **final**. cc @karalabe 

The reason behind this is that Clique engine is already implemented in the following clients:

- Go Ethereum (and Multi Geth)
- Parity Ethereum
- Pantheon
- Nethermind
- EthereumJS

In addition, this engine powers a couple of production networks, such as 

- Rinkeby
- Görli
- Kotti Classic

Changes to the clique engine would require a new proposal replacing or upgrading 225 at this stage. Therefore, I propose to move the Clique EIP to final.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 225 state from Draft to Final
 - EIP 225 requires approval from one of (@karalabe)

**Comment by nicksavers** [comment]
@soc1c The Dragt needs to go through **Last Call** status as specified in [EIP-1](https://eips.ethereum.org/EIPS/eip-1).

**Comment by soc1c** [comment]
Yeah, I know there is a process. But I'm saying this is already _de facto_ final as pointed out in OP. There is nothing to be gained by _last call_, because every objection would require a new proposal.

**Comment by axic** [comment]
Technically should this have a last call period before going into final state?

@karalabe how do you feel about this?

**Comment by karalabe** [comment]
Dunno, don't care really. Last Call, Final, all the same :P Someone just push it :)

**Comment by axic** [comment]
@karalabe the main question is: are you happy with the status of the Clique EIP? Once it turns `Final` only typos and changes of similar caliber can be made to it. Do you think it is in that state?

**Comment by axic** [comment]
Ping @karalabe

@Arachnid @nicksavers should this go through a last call instead?

**Comment by Arachnid** [comment]
IMO - it's already implemented in several clients in production; we should make it Final to reflect the current state of the art. Any changes would require a new EIP at this point anyway, to avoid confusion between versions.

**Comment by axic** [comment]
Ping @karalabe okay to merge?

**Comment by axic** [comment]
@karalabe confirmed it on geth's discord.

**Pull request merged**
