### PR TITLE
Update EIP-3085: Move to Review

### PR DESCRIPTION
**Pull request by Pandapip1**
Needs approval from either Erik Marks (@rekmarks) or Pedro Gomes (@pedrouid)

### CODE REVIEW

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
CC Erik Marks (@rekmarks) or Pedro Gomes (@pedrouid)

**Review by pedrouid — APPROVED** [review]
👍

**Pull request merged**
