### PR TITLE
EIP1344 to be considered for next upgrade (Meta EIP1679)

### PR DESCRIPTION
**Pull request by fubuloubu**
Per the proposed process for handling EIPs for Hardforks (detailed [here](https://github.com/ethereum/EIPs/blob/9233fd6aaa99161079e395f8733c26c9f4a3b17d/EIPsForHardfork.md)), we would like to propose EIP-1344 be formally considered for inclusion into the Istanbul hardfork (EIP-1679)

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1679 requires approval from one of (@5chdn, @axic)

**Comment by poojaranjan** [comment]
@fubuloubu Thanks for listing your EIP for consideration of Istanbul Upgrade. We've added it to the list of proposed EIPs for Istanbul [here](https://github.com/ethereum-cat-herders/PM/blob/ca6a01c1d0a45419a55f7e79688e28ea6e0c8482/Hard%20Fork%20Planning%20and%20Coordination/IstanbulHFEIPs.md). As it appears, pull requests submitted here is monitored by bot and it requests for approval from author of EIP 1679 because of its mention. 
So, it would be appropriate to create a new issue [here]( https://github.com/ethereum/EIPs/issues), which eventually be closed after the EIP is added to the ‘EIPs for Upgrade’ list. The proposal [#1929]( https://github.com/ethereum/EIPs/blob/97aac5f67b26c74ce78595cf493eecd1b15c09bb/EIPsForHardfork.md) is also updated accordingly.
Thanks for cooperation.

**Comment by fubuloubu** [comment]
Closing this in favor of #1935 per @poojaranjan's recommendations.

**Comment by axic** [comment]
I think we should merge this dependent on merging #1852.

**Comment by fubuloubu** [comment]
I deleted the branch so I can't reopen. But I will make a new one. Sorry for the inconvenience!

**Comment by axic** [comment]
In the branches view of your fork you may be able to reinstate it. Opening a new PR however should not be an issue 😉

**Comment by fubuloubu** [comment]
Re-opened at #1937

**Pull request closed without merging**
