### PR TITLE
Add EIP: Real Estate Token

### PR DESCRIPTION
**Pull request by Alex-Klasma**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by Alex-Klasma** [comment]
Made a large overhaul to EIP6065. I added a reference implementation (work in progress), and the EIP is drastically simplified and shorter now.

**Comment by dfalloncyr** [comment]
Hi @Pandapip1 we have updated this EIP significantly after feedback from the community. We would like to move it from `draft` to `review`. Is that something we have to do, or is that a change made on your team's end? Thanks for your help!

**Comment by abcoathup** [comment]
@Pandapip1 not sure why this is tagged as a new ERC, as it is an update to https://eips.ethereum.org/EIPS/eip-6065

**Comment by Alex-Klasma** [comment]
Yeah, not sure the issue. You guidelines say: 
```
We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

The PR edits only existing draft PRs.
```

Should be merged automatically then. Let me know if there's anything I can do or if I did something wrong!

**Comment by RonnyGiron** [comment]
I have not authorized any transactions, I've been using 1 inch exchange
app. Token pocket, ethplorer, etherscan, ethereum main-net, metabank,
MEW(my ether wallet, math wallet, etc... but no github, because you are
tolerant of hackers! I do not support hackers

**Pull request closed without merging**
