### PR TITLE
Add EIP-1702 as a proposal for Istanbul hard fork

### PR DESCRIPTION
**Pull request by sorpaas**
As requested by @bmann rel https://github.com/ethereum-cat-herders/PM/pull/63 https://github.com/ethereum-cat-herders/PM/issues/53

Note that this PR is made with the assumption that EIP-615 will also be in the proposal list.

### CODE REVIEW

**Comment by bmann** [comment]
Thanks @sorpaas! @axic if you can approve!

**Comment by axic** [comment]
It is failing the CI for some reason:
```
- ./_site/EIPS/eip-1679.html
  *  internally linking to https://eips.ethereum.org/EIPs/eip-1702, which does not exist (line 98)
     <a href="https://eips.ethereum.org/EIPs/eip-1702">EIP-1702</a>
htmlproofer 3.8.0 | Error:  HTML-Proofer found 1 failure!
```

**Comment by bmann** [comment]
I think it wants a capital S in the middle EIPS/eip-1702

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1679 requires approval from one of (@5chdn, @axic)

**Pull request merged**
