### PR TITLE
Update EIP-6065: Move to Review

### PR DESCRIPTION
**Pull request by Alex-Klasma**
Change to Review status

### CODE REVIEW

**Comment by dfalloncyr** [comment]
Hi @poojaranjan I reviewed the office hours meeting and did not see EIP6065 come up. Was it added for the next meeting? Thanks!

**Comment by poojaranjan** [comment]
We couldn't review the proposal due to limited time. I hope it is reviewed and merged async. If it is open until the next meeting, please include it on the agenda.

**Comment by dfalloncyr** [comment]
Sounds good, will keep and eye on it. Thanks! Assuming the next meeting is 5/16?

**Review by SamWilsn — COMMENTED** [review]
Things that need to be fixed:
 - `EIP6065Immutable` comment (Lines 57 - 70) should be removed. While we do allow some suggestions for implementers in complex cases, I don't think this particular comment adds significant value.
 - Similarly the `EIP6065Mutable` bits of that comment should be removed.
 - Define RWA before its first use.
 - Foreclosure needs to be defined outside of a comment. What does that mean in terms of the token? Is it forcibly transferred to a different owner? Destroyed?
 - The debt stuff is under-specified. If the debt is a token, how is it "utilized specifically for off-chain debt"?
 - Link to your reference implementation file in the reference implementation section.
 - Remove `(*see pull request above*)` on line 180.
 - EIPs are not advertisements, so I'd like to see the reference implementation section de-klasma'd a bit. I'm fine with a "Klasma Labs offers a work in progress..." intro sentence, but I'd prefer everything after use fictitious company names.

**Comment by Alex-Klasma** [comment]
Still working on this, just merging some prior stuff

**Comment by Alex-Klasma** [comment]
> Things that need to be fixed:
> 
>     * `EIP6065Immutable` comment (Lines 57 - 70) should be removed. While we do allow some suggestions for implementers in complex cases, I don't think this particular comment adds significant value.
> 
>     * Similarly the `EIP6065Mutable` bits of that comment should be removed.
> 
>     * Define RWA before its first use.
> 
>     * Foreclosure needs to be defined outside of a comment. What does that mean in terms of the token? Is it forcibly transferred to a different owner? Destroyed?
> 
>     * The debt stuff is under-specified. If the debt is a token, how is it "utilized specifically for off-chain debt"?
> 
>     * Link to your reference implementation file in the reference implementation section.
> 
>     * Remove `(*see pull request above*)` on line 180.
> 
>     * EIPs are not advertisements, so I'd like to see the reference implementation section de-klasma'd a bit. I'm fine with a "Klasma Labs offers a work in progress..." intro sentence, but I'd prefer everything after use fictitious company names.

1. Comments in the code about "structs" removed.
2. removed
3. defined RWA as "real world assets" now before first usage of abbreviation.
4. Foreclosure defined in L#126,`### debtOf` heading
5. "off chain" debt has been specified further with some examples.
6. Reference implementation linked
7. This line has been removed and replaced by the reference implementation link.
8. All "Klasma" references have been removed except the single line you were OK with -- image also been changed to account for this

**Comment by dfalloncyr** [comment]
@SamWilsn sorry we missed the office hours yesterday! Didn't see it mentioned until after it had happened (we are located in California). We have addressed all of your comments above, please let us know if there is anything else that needs to be changed to move this to review and we can address async. Thanks for all of your help!

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
