### PR TITLE
Add header row to support gfm for table formatting

### PR DESCRIPTION
**Pull request by njgheorghita**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

Adds an empty header row to tables enable table formatting with github flavored markdown.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
If you know how, would you mind throwing this into the page somewhere (I don't even know if it is possible):
```css
table.empty {
  width: 350px;
  border-collapse: collapse;
  empty-cells: hide;
}
td.empty {
  border-style: solid;
  border-width: 1px;
  border-color: blue;
}
```
And see if that resolves the issue?  (you may need to tweak the specific settings)

The tables are rendering now, but they have an empty row in them.

**Comment by MicahZoltu** [comment]
Hmm, maybe that isn't possible.

**Comment by MicahZoltu** [comment]
Maybe we can update the jekyll site at least so it hides empty rows, and just deal with it in GitHub markdown...

**Comment by njgheorghita** [comment]
Yeah I'm not able to find some straightforward way to do this - imo it's not that offensive to the eyes in the github flavored markdown since the empty header column is rendered quite small

**Comment by MicahZoltu** [comment]
I'll talk to the other editors to see what they want to do.

**Comment by MicahZoltu** [comment]
Spoke with some other editors: Would it be possible to change these to lists instead of tables?  e.g.:
```md
* **Required**: If `name` is included.
* **Key**: `version`
* **Type**: String
```
* **Required**: If `name` is included.
* **Key**: `version`
* **Type**: String

**Comment by njgheorghita** [comment]
Yup, works for me! That should be suitable for all the tables afaik - I'll submit the update asap

**Comment by MicahZoltu** [comment]
Tables with actual headers I think everyone is good with being a markdown table.  It is just the headerless tables that are problematic.

**Pull request merged**
