### PR TITLE
Add various example citation formats

### PR DESCRIPTION
**Pull request by fulldecent**
This will help people that want to make citations

### CODE REVIEW

**Comment by axic** [comment]
I think this is a good idea, but would be more fair if the example would be about "EIP-1" and not picking up random EIPs.

Also personally I'd prefer to give a single preferred format and not two.

**Comment by fulldecent** [comment]
It would be fair. But to be honest, probably ERC-721 and 20 are the only ones being cited in academia right now. I see about 2 a week.

This PR is temporary. Later I want to make it so these are customized and show up on the bottom of every EIP page. And then I'll undo this. At that point there will be a selector and many more reference formats, including BibTeX. I'm still working on that. It's not that we are preferring a specific format -- the researcher needs a certain format for their use.

**Comment by axic** [comment]
> This PR is temporary. Later I want to make it so these are customized and show up on the bottom of every EIP page. And then I'll undo this. 

I think #2738 added this. @fulldecent can this be closed?

**Comment by fulldecent** [comment]
Yes, good to close. We now have full examples, which are better.

**Pull request closed without merging**
