### PR TITLE
Update eip-998.md

### PR DESCRIPTION
**Pull request by dhaileytaha**
missing semicolon

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 998 requires approval from one of (@mudgen, @mattlockyer, jordan.schalm@gmail.com)

**Comment by lightclient** [comment]
bump @mudgen @mattlockyer

**Review by mudgen — APPROVED** [review]

**Comment by mudgen** [comment]
> bump @mudgen @mattlockyer

thanks, I approved the pull request.

**Comment by MicahZoltu** [comment]
Please sync with master.

**Pull request merged**
