### PR TITLE
Reformat EIP1967 to match requirements from EIP1

### PR DESCRIPTION
**Pull request by spalladino**
- Add inline reference implementation
- Change simple summary section to description header field
- Move extraneous Beacon section to within the Specification
- Add new Security Considerations section
- Update some outdated links

cc @axic

### CODE REVIEW

**Comment by lightclient** [comment]
@spalladino there are a few spelling errors here. Once fixed, this should auto-merge.

**Comment by spalladino** [comment]
@lightclient thanks for the heads-up, just fixed them!

**Comment by spalladino** [comment]
Hey @axic, what would be the next steps to push forward this EIP?

**Comment by MicahZoltu** [comment]
@spalladino Submit a PR that changes the status from Draft to Review if you are no longer actively iterating on it.  A reviewer will review the EIP again (a bit more thoroughly than the first time) and either give feedback or approve.  Once it is in Review, that is a good opportunity to solicit feedback from a wider audience before moving to Last Call and then eventually Final.

**Comment by spalladino** [comment]
Done, thanks @MicahZoltu! #4495

**Pull request merged**
