### PR TITLE
Update EIP-223: Fix major vuln

### PR DESCRIPTION
**Pull request by Pandapip1**
CC @Dexaran

### CODE REVIEW

**Comment by Dexaran** [comment]
Whose genius idea it was to call a "clarification of specification" that already has a reference implementation that perfectly demonstrates the order of function executions a `Fix major vuln`. Like... do you call plain ether vulnerable?

**Comment by Dexaran** [comment]
btw I can't merge this PR

**Comment by Dexaran** [comment]
https://github.com/ethereum/EIPs/pull/7473

**Comment by Pandapip1** [comment]
FYI @Dexaran - if you want to merge someone else's proposed modification, you can simply approve it using the files tab instead of making your own PR.

**Pull request closed without merging**
