### PR TITLE
Website: Move last call rss feed to rss folder

### PR DESCRIPTION
**Pull request by Pandapip1**
Pretty self-explanatory.

### CODE REVIEW

**Comment by SamWilsn** [comment]
This breaks anything that currently uses the RSS feed?

**Comment by SamWilsn** [comment]
Do you also need to update https://github.com/ethereum/EIPs/blob/611981eb554a9669052cdf08f2cb85afc87a3e94/last-call.xml#L10?

**Comment by Pandapip1** [comment]
> This breaks anything that currently uses the RSS feed?

Yes.

**Comment by Pandapip1** [comment]
Oops didn't mean to close.

**Comment by Pandapip1** [comment]
> Do you also need to update 

Yes

**Comment by SamWilsn** [comment]
> > This breaks anything that currently uses the RSS feed?
> 
> Yes.

@poojaranjan are you aware of anything that depends on the RSS feed?

**Comment by poojaranjan** [comment]
@SamWilsn 
> 
> @poojaranjan are you aware of anything that depends on the RSS feed?

People mentioned subscribing to RSS feeds and we were planning to add that on ECH website.  But, we haven't started working on it. 
Nothing comes to my mind that could be dependent on these RSS feeds.

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
