### PR TITLE
Update EIP-7044: Move to Final

### PR DESCRIPTION
**Pull request by dapplion**
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by poojaranjan — COMMENTED** [review]
May want to update the "Test Cases" Comment. 
Something as "Test cases are available within the standard Consensus Layer tests."

**Comment by timbeiko** [comment]
+1 @dapplion

**Comment by timbeiko** [comment]
@dapplion I did the change in https://github.com/ethereum/EIPs/pull/8345

**Comment by dapplion** [comment]
Closing for https://github.com/ethereum/EIPs/pull/8345

**Pull request closed without merging**
