### PR TITLE
EIP for RFT

### PR DESCRIPTION
**Pull request by tlxsam**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by axic** [comment]
Without fully reading the proposal, this seems to be similar to #1633. Would it be possible to merge efforts?

**Comment by tlxsam** [comment]
We are upgrading the implementation based on the latest contract definitions and will resubmit for review.

**Comment by lightclient** [comment]
@tlxsam do you plan to use this PR or will you close?

**Comment by tlxsam** [comment]
> @tlxsam do you plan to use this PR or will you close?

yes, we are planning to use this PR, we will be updating it soon.

**Comment by 3scava1i3r** [comment]
Is this EIP going to be used for refungible tokens?

**Pull request closed without merging**
