### PR TITLE
chore(docs): fix typo

### PR DESCRIPTION
**Pull request by xwartz**
fix typo: `BLOCK_EXPORER_URL` -> `BLOCK_EXPLORER_URL` in EIPS/eip-3091.md

### CODE REVIEW

**Comment by MicahZoltu** [comment]
@xwartz This is a stagnant EIP, which means the author appears to have abandoned it and it isn't yet a standard.  If you wish to pursue this as a standard, I recommend trying to contact the author or if that fails create a fork of the EIP if you plan to champion the EIP through to completion.

**Comment by xwartz** [comment]
cc @pedrouid

**Review by fulldecent — APPROVED** [review]

**Comment by fulldecent** [comment]
Thank you, approved

**Comment by MicahZoltu** [comment]
This EIP is stagnant, which means it doesn't have an author pushing it forward.  If you would like to make changes to this (including typos and the like) then you will either need to get the author to move this EIP forward, get the author to add you as an author so you can push it forward, or you will need to create a new EIP that you are the author of and you will push it forward.

**Pull request closed without merging**
