### PR TITLE
Remove greeting bot

### PR DESCRIPTION
**Pull request by Pandapip1**
Rationale: With #5066 merged, users should be more aware of the information given in the greeting bot - and at this point, the greeting bot seems to cause more annoyances than benefits. I suggest it be removed.

@eth-bot will not merge this. It will need to be manually merged.

### CODE REVIEW

**Comment by Pandapip1** [comment]
Editor CC since @eth-bot didn't ping: @MicahZoltu @lightclient @gcolvin @axic @SamWilsn

**Comment by SamWilsn** [comment]
I can't override the bot, sorry ^^;;

**Comment by MicahZoltu** [comment]
Given the changes in #5066, I'm open to giving things a try without the greeter to see if it would still add value or not.  I'll wait to hear from other editors before merging though.

**Comment by Pandapip1** [comment]
Re-mentioning editors that have not responded: @lightclient @gcolvin @axic

**Comment by Pandapip1** [comment]
It's been a week since there's been discussion on this. @MicahZoltu would you mind merging this for now? It can always be reverted.

**Comment by gcolvin** [comment]
> Can someone TLDR this entire convo for me? What is wrong with the greeter?

The only complaints I'm hearing is that it is verbose and redundant.

In which case make it less so, but even I find the reminders useful.  What is right about the greeter for me is that it mentions me as an editor only for core EIPs.  That makes it possible to get notifications for those PRs without being flooded with ERCs.  Those mentions might also help authors know who to go hassle if their work isn't getting reviewed ;)

**Comment by Pandapip1** [comment]
Sorry for the confusion. This is specifically the @github-actions bot that comments on new issues reminding users to check out EIP-1. The @eth-bot PR greeter is a totally separate system.

**Review by lightclient — APPROVED** [review]
This is okay with me. Will wait to see if there is any other feedback.

**Comment by MicahZoltu** [comment]
@axic There was a recent change to the issue creation flow that should (hopefully) serve the same purpose as the greeter bot but *before* the user creates the issue, rather than after.  This PR proposes to remove the greeter since it is functionally redundant.  If you want to see the new issue flow, just click the new issue button in GitHub.

**Comment by Pandapip1** [comment]
Bump.

**Review by MicahZoltu — APPROVED** [review]

**Review by MicahZoltu — APPROVED** [review]

**Pull request merged**
