### PR TITLE
ERC820: Move to Final

### PR DESCRIPTION
**Pull request by 0xjac**
The Last Call period for ERC820 ended on 2018-12-30 without further comments, suggestions or modifications. Hence I would like to move 820 to a final status.

I'd also like to thank everyone who contributed and helped with ERC820, (including in no particular order): @fulldecent @mcdee @jaycenhorton @Recmo @hyperfekt @wighawag @thegostep @Arachnid @Souptacular and everyone I forget.

### CODE REVIEW

**Comment by 0xjac** [comment]
Note: The CI failed due to errors in the build process, not the changes in this PR.

**Comment by Arachnid** [comment]
Can you please merge or rebase your PR from master? That should fix the build error.

**Comment by fulldecent** [comment]
This is hot off the press and good to merge!

**Comment by bluerosss** [comment]
“That's one small step for a man, one giant leap for mankind” :)  #EIP820 #ERC777

**Comment by thegostep** [comment]
Congrats ! Thank you for the great work

**Pull request merged**
