### PR TITLE
Wording

### PR DESCRIPTION
**Pull request by royosherove**

### CODE REVIEW

**Comment by royosherove** [comment]
The codespell is breaking on assets that have nothing to do with this pull request. Not sure what I can do about that..?

**Comment by Pandapip1** [comment]
Yea, something's broken. It should only lint changed files.

**Comment by Pandapip1** [comment]
Also, eip-bot should not be automerging this 👀

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
Oh I see, you've merged instead of rebased the PR, and you clearly overwrote your changes since there are zero modified files. @royosherove mind if I recreate the PR for you?

**Comment by Pandapip1** [comment]
Oh, this isn't the PR to modify

**Pull request closed without merging**
