### PR TITLE
Update eip-1057.md with code walk through.

### PR DESCRIPTION
**Pull request by ifdefelse**
merge in code walkthrough from from ProgPoW readme.md

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by marienuac** [comment]
lol

**Comment by Kylebrown9** [comment]
https://blog.sia.tech/the-state-of-cryptocurrency-mining-538004a37f9b

Their manufacturing timetable is estimated to be in the neighborhood of 5 months and even if they do crack it in the near future that doesn't necessarily make it an invalid option. 

Either way if you're looking to complain or advise a different course of action you're in the wrong thread. Head over to the [actual proposal](https://github.com/ethereum/EIPs/pull/1057#issuecomment-389554723) instead of what is essentially a documentation pull request.

**Comment by tbonillas** [comment]
Please implement asap

**Comment by neymar08** [comment]
yes please needs to be implemented asap this is a serious issue pushing casper in defense is not smart we need casper to be everything its meant to be in the time it takes if this new algo passes test do it give some breathing room to triple check casper before implementing it thank you

**Comment by eds17** [comment]
yep!

**Comment by VanillaIce83** [comment]
Yes would really recommend the implementation to keep the Coins decentralized and do not let the chinese control all the Coins!!!

**Comment by mikeydent** [comment]
Implement please, you know it is the right thing to do! Think about the little guys, like me. gpu mining was the first stepping stone which got me into the world of cryptocurrency if it dies, so does industry growth.

**Comment by ShehabIsmail** [comment]
We need to fork out of asic!

**Comment by crypto4techs** [comment]
Fully support implementing ProgPoW to thwart ASICs

**Comment by SerpentXSF** [comment]
Fork it! Fork it good!

**Comment by quyquan** [comment]
Yes, please implement!

**Comment by woodaxed** [comment]
yes  implement

**Comment by gfunksound** [comment]
Let's implement this for Constantinople!

**Pull request merged**
