### PR TITLE
Add myself (@Pandapip1) as an editor

### PR DESCRIPTION
**Pull request by Pandapip1**
I don't think there's anything special I need to put here, so I'm writing this sentence because it feels incorrect to leave a form field blank.

EDIT: I do have something to put here. EIP Editors - do NOT approve this, signal approval with a comment instead. @eth-bot _will_ auto-merge this with only one approval.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Lets wait to get feedback from @axic @lightclient @gcolvin before merging.  If we haven't heard from them in 3 weeks mention me and I'll merge.

**Comment by lightclient** [comment]
👍 from me.

**Comment by Pandapip1** [comment]
Bump. @axic @gcolvin

**Comment by MicahZoltu** [comment]
Given we have 3 editors in support, lets drop the wait time to 1 more week (when this post says "7 days ago").  Ping me at that time and assuming no negative feedback I'll merge.

**Comment by gcolvin** [comment]
Sorry I missed this.  Good by me.

**Pull request merged**
