### PR TITLE
Net gas metering for SSTORE with a reentrancy protection

### PR DESCRIPTION
**Pull request by alex-forshtat-tbk**
Moving proposal from pull request to existing EIP into a new one. 
See discussion:
https://github.com/ethereum/EIPs/pull/1701

### CODE REVIEW

**Comment by sorpaas** [comment]
@alex-forshtat-tbk Please restore the `eip-X.md` file!

**Comment by Ry1xao** [comment]
ryan.alvar@yahoo.com

**Comment by stvenyin** [comment]
YES

**Comment by stvenyin** [comment]
It defines three concepts:

The original value of the storage slot (original): The value that exists after the current transaction has been reverted is called the original value.
Current value of the storage slot (current): The value existing before the SSTORE opcode is used is called the current value.
The new value of the slot (new): the value that exists after using the SSTORE opcode is called the new value.

**Comment by stvenyin** [comment]
- 
101529y544txkfofists8i

**Pull request merged**
