### PR TITLE
Reject EIP-1355 "Ethash 1a"

### PR DESCRIPTION
**Pull request by chfast**
Reject EIP-1355 "Ethash 1a" because it is not useful.

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Supported

**Comment by axic** [comment]
Why is it not useful?

**Comment by chfast** [comment]
It might break the current generation of ASICs (if they are not able to adjust by upgrading firmware, but that is not confirmed). But it is easy to create a new revision of ASICs and ship within 3-6 months. We would need similar changes to be done every HF or quicker to make this approach sustainable.

**Comment by axic** [comment]
I've thought that would be the answer, but I wouldn't say it is completely useless. 

> if they are not able to adjust by upgrading firmware, but that is not confirmed

This is the only worrying part.

> We would need similar changes to be done every HF or quicker to make this approach sustainable.

If there is a sentiment that PoW must be ASIC-safe, then I would argue that might be more sustainable short term than delaying changes due to the need of review/auditing a more complex change, such as ProgPoW.

**Comment by nicksavers** [comment]
This can't be merged until the website generator supports status "Rejected"

**Comment by axic** [comment]
I think the reasoning @chfast wrote should be incorporated into the "rationale" part.

**Comment by axic** [comment]
I think the `Abandoned` status introduced in #2051 may be the best option here.

**Comment by axic** [comment]
@chfast #2051 was merged, this can be marked Abandoned now.

**Comment by axic** [comment]
Damn, also need to update eip-validator:
```
total:206, valid:199, invalid:1, errors:6
	statuses: [["Final", 45], ["Draft", 150], ["Deferred", 3], ["Abandoned", 1], ["Last Call", 1]]
	types: [["Standards Track", 186], ["Meta", 13], ["Informational", 1]]
	categories: [["Core", 80], [nil, 14], ["ERC", 84], ["Interface", 15], ["Networking", 7]]
	layers: [[nil, 200]]
```

**Comment by axic** [comment]
Will be fixed by #2161.

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1355 state from Draft to Abandoned

**Pull request merged**
