### PR TITLE
EIP 2929 -> final

### PR DESCRIPTION
**Pull request by vbuterin**
^^

### CODE REVIEW

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - Trying to change EIP 2929 state from last call to final

**Comment by timbeiko** [comment]
@alita-moore why is this failing?

**Comment by alita-moore** [comment]
@timbeiko this seems like an edge case where the author of the PR is an author on the PR so it fails because the change would have triggered a requirement for review but that edge case wasn't handled yet. I'll look into it.

**Comment by MicahZoltu** [comment]
This failed correctly.  Editor approval is required to change the status to anything other than Withdrawn from Draft or Withdrawn from Review or Withdrawn from Last Call.

**Comment by timbeiko** [comment]
@MicahZoltu so @vbuterin should have approved his on PR, basically?

**Comment by MicahZoltu** [comment]
No, this one was submitted by an author, thus it just needs *Editor* approval (me, lightclient, axic, etc.).  In this case, I "approved" it by merging (since we are going through some bot transition growing pains).

**Comment by timbeiko** [comment]
Got it, thanks! I assumed that an author's PR to their own EIP would be auto-merged, that's why.

**Comment by MicahZoltu** [comment]
> Got it, thanks! I assumed that an author's PR to their own EIP would be auto-merged, that's why.

Normally this is true, but when changing the status (Draft > Review > Last Call > Final) you need an editor to also review.

**Pull request merged**
