### PR TITLE
2678: Convert html tables to markdown

### PR DESCRIPTION
**Pull request by njgheorghita**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

Changes in this pr are related to the discussion in https://github.com/ethereum/EIPs/pull/3269#pullrequestreview-591995056

### CODE REVIEW

**Comment by MicahZoltu** [comment]
CI is choking with:
```
- ./_site/EIPS/eip-2678.html
  *  internally linking to "#term-link-value", which does not exist (line 2244)
     <a href="&quot;#term-link-value&quot;">Link Values</a>
  *  linking to internal hash #term-link-reference" that does not exist (line 2244)
     <a href="#term-link-reference&quot;">Link References</a>
  *  linking to internal hash #term-link-value" that does not exist (line 2244)
     <a href="&quot;#term-link-value&quot;">Link Values</a>
```

Also, I believe you can do anchors in markdown (no need for HTML anchors):
https://gist.github.com/asabaylus/3071099

**Comment by MicahZoltu** [comment]
Any idea why the tables aren't rendering in GitHub markdown?  I'm pretty confident GitHub markdown supports tables.

**Comment by MicahZoltu** [comment]
I think you need a header row for GitHub flavored markdown perhaps?

**Comment by njgheorghita** [comment]
Hmmm that's weird, the tables were rendering fine when I served them locally... I'll try adding a header though

**Comment by MicahZoltu** [comment]
Different markdown renderers have different rules.  The Jekyll site, for example, does fine with what you have: https://eips.ethereum.org/EIPS/eip-2678

**Pull request merged**
