### PR TITLE
Update EIP 918 to Last Call

### PR DESCRIPTION
**Pull request by 0xbitcoin**
Also added a brief comment about how to check a hash digest for validity as that was missing.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 918 state from Draft to Last Call
 - EIP 918 requires approval from one of (bg2655@columbia.edu, mgs33@cornell.edu, @jlogelin, admin@0xbitcoin.org)

**Comment by 1blockologist** [comment]
@axic  @MadeofTin  What if the authors don't have github accounts under those email addresses?

I think a human can look at this and see the correct account is being used to approve this

**Comment by Arachnid** [comment]
Please also add a `discussions-to` URL.

**Comment by 1blockologist** [comment]
@jlogelin anything I can help with in regard to the changes @Arachnid suggested?

**Comment by jlogelin** [comment]
@0xbitcoin Could you please address requested additions to this PR? ( I don't have write access to that repo )

**Comment by jlogelin** [comment]
> Please specify a `review-period-end` at least 2 weeks in the future.
> 
> If you are not going to provide test cases, the test cases section should be deleted.
> 
> Speaking as a contributor rather than an editor: A section describing the algorithm for a miner interacting with the contract, step-by-step, would be useful.

Something like this?

**Mining for EIP918 Tokens**

There are several CPU, GPU and ASIC miners available for mining solidity sha3 solutions. Each of them uses the following steps to mint and submit solution nonces:

1. Obtain the current difficulty(target) and challenge number from the EIP918 contract using the calls `getMiningDifficulty` and `getChallengeNumber`.
2. Search for a solution by generating a random nonce.
3. Apply SHA3 to the challenge, public key and nonce.
4. Check if the resulting SHA3 hash is less than the target ( greater than the token difficulty )
5. Once a solution is found, submit it and it's hash ( sha3( challenge, publicKey, nonce ) ) to the `mint` function of the contract.

The following javascript code illustrates these steps for mining an EIP918 token(0xbitcoin):

```javascript
const Web3 = require('web3')
var web3 = new Web3()

const bitcoinJson = require('abi/0xbitcoin.json')
const BITCOIN_ADDRESS = '0xb6ed7644c69416d67b522e20bc294a9a9b405b31'
const bitcoin = new web3.eth.Contract(bitcoinJson.abi, BITCOIN_ADDRESS)

web3.setProvider('https://mainnet.infura.io/<your-token-here>')
MAX_TARGET = web3.utils.toBN(2).pow(web3.utils.toBN(234))

function targetFromDifficulty(difficulty) {
    return MAX_TARGET.div(web3.utils.toBN(difficulty))
}

// Loop through random numbers until a solution is found, returning both the solution and
// the hash of the contract's current challenge, publicKey of the miner and the solution
async function mine(publicKey) {
    let challenge = await this.bitcoin.methods.getChallengeNumber().call()
    let difficulty = await this.bitcoin.methods.getMiningDifficulty().call()
    while (true) {
        // pick a random number
        var nonce = web3.utils.randomHex(64)
        // encode the hash with 0xbitcoin challenge, public key and random number
        var digest = web3.utils.soliditySha3(challenge, publicKey, nonce)
        var digestBigNumber = web3.utils.toBN(digest)
        var target = this.targetFromDifficulty(difficulty)
        // check if the hash is less than the target ( greater than the difficulty )
        if (digestBigNumber.lt(target)) {
            return { nonce, digest }
        }
    }
}

async function main() {
    let address = 0xYourMiningAddress
    // mine for 0xBitcoin using your public key account
    let minedResults = mine(0xYourMiningAddress)
    // submit the mined nonce to the contract, once verified, a token reward will be submitted to your 
    // Ethereum account
    let mintResults = await this.bitcoin.methods.mint(minedResults.nonce, minedResults.digest).call({ from: 0xYourMiningAddress })
    // log the results
    console.log(mintResults)
}
```

**Review by MicahZoltu — CHANGES_REQUESTED** [review]
The motivation section should explain why this needs to be a Standard rather than just a Good Idea since it isn't immediately obvious.  A standard is valuable when there is a many-to-many relationship between parties.  An example of something that needs a standard is web pages because there are many browsers that come and go over time and there are many web pages on the internet that come and go over time.  In order for all web pages to work on all browsers, we need a standard.  If you have a one to many relationship or a one to one relationship, then you don't need a standard and instead just have a Good Idea that you can implement.

In this case there is a one to one relationship between the token and the mining interface, so it doesn't seem like there is a need for a standard.  Each token will have its own user interface (because they each will have their own PoW function) and they can each define whatever contract interface they like.

----

Interface standards should never define internal behavior, as that is an implementation detail.  This standard defines several internal functions which should all be removed.

The same for the implementation details of the functions.  While a reference implementation can be useful in the `## Implementation` section, it is not part of the specification and instead you should only define publicly visible behavior expectations, not internal implementation details of how to achieve that behavior.

**Comment by jlogelin** [comment]
@MicahZoltu I agree that the Motivation section should be a little less philosophical and more tactical. It could be updated to include a statement explaining that there are currently multiple mineable tokens and each have to have supporting infrastructure including pools, client mining software, etc. Standardizing a mineable contract interface helps miner and pool authors to have a consistent polymorphic interface.

At a minimum, the interface behavior is defined here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-918.md#interface. The remaining sections do shift towards abstract implementation. It's a bit of a balancing act to make this document useful beyond conceptual, but your point is noted.

**Comment by MicahZoltu** [comment]
> there are currently multiple mineable tokens and each have to have supporting infrastructure including pools, client mining software, etc. 

Wouldn't this still be true after this standard is published because each token would have its own mining algorithm, thus would need custom tooling to mine that particular algorithm?  Perhaps the idea is that all of those tools have a plugin system of some sort for plugging in the mining algorithm but otherwise they interface with the token in a standardized way?  If so it feels like this contract is missing the critical requirement of a way to ask the contract for the algorithm (e.g., by name or something).  If not, then it seems like this doesn't benefit from being standardized.

> It's a bit of a balancing act to make this document useful beyond conceptual, but your point is noted.

Standards are not meant to be maximally useful documents for all parties, they are meant to clearly specify the bits that must be standardized.  It is up to other documents (e.g., blog posts, tutorials, YouTube videos, GitHub repositories, etc.) to provide all of that extra useful information to users wanting to implement the standard.

If the motivation for standardizing this is so that multiple tools can support multiple minable contracts, then only the interface definition is required (along with description of that interface).  Implementations can do whatever they want, and the tools shouldn't care what happens internally as long as the interface is fulfilled.

**Pull request closed without merging**
