### PR TITLE
Disallow the word "smart" in EIP titles and descriptions

### PR DESCRIPTION
**Pull request by Pandapip1**
Closes https://github.com/ethereum/EIPs/issues/5308

### CODE REVIEW

**Comment by Pandapip1** [comment]
CC @SamWilsn for eipw

**Comment by lightclient** [comment]
I am against this change - of the 9 EIPs that have `smart` in their title [only 1](https://github.com/ethereum/EIPs/pull/5247) of them would I consider having a non-descriptive title. I would rather editors provide a little feedback on titles in these cases.

**Comment by Pandapip1** [comment]
I would be okay with allowing "smart" in the description, but in the title, I'd say that at least one of the following is always true:

- The author is anthropomorphizing
- The adjective is used subjectively
- The author is referring to "smart contracts"

The first two cases are obvious errors, and context is enough to allow readers to know what type of contracts are being referred to in the title.

**Comment by Pandapip1** [comment]
Would also like to point out https://github.com/ethereum/EIPs/pull/4519

**Comment by Pandapip1** [comment]
Closing this for now. If someone wants to re-open this please just comment.

**Pull request closed without merging**
