### PR TITLE
Disable selfdestruct

### PR DESCRIPTION
**Pull request by lightclient**
Rendered: https://github.com/lightclient/EIPs/blob/b8befca8626da48834daaae060facbae6e095806/EIPS/eip-2751.md

I've grabbed the commits from @AlexeyAkhunov's PR #2751 and added them + some spelling fixes. I'd like to get this merged since there has been discussion in the magicians thread and on Twitter. I believe Alexey does not wish to pursue this at this moment and therefore may not have the bandwidth to address the issues blocking the merge in his original PR.

### CODE REVIEW

**Comment by axic** [comment]
#2751 has **a ton of** unanswered comments, especially concerning the specification. Are you planning to address those?

**Comment by lightclient** [comment]
I don't plan on addressing any concerns relating to the specification itself in the near future. I generally think those are best hashed out in the magicians thread (as it appears some of them have been). I'm afraid that allowing that PR to continue to be open will further fragment the discussion. Happy to close this if you find it inappropriate to push this into a draft w/o further clarifications from the author.

**Comment by axic** [comment]
It is an interesting question. If the author does not want to pursue it further, merging it as a draft will not really improve the situation. Who will be able to merge changes into it? I think it should be merged if someone is picking it up and plans to address the comments. Otherwise keeping it as a PR+magicians forum is fine, imho.

**Comment by MicahZoltu** [comment]
If Alexy isn't interested in pursuing #2751 and you don't plan on pursuing this, then I think both PRs should be closed until such time as someone is interested in *actually* taking the EIP through to completion.

Have you checked with Alexey to see if perhaps they just don't understand the EIP process and think they need to get agreement before merging to draft?  Maybe this is just a matter of education and helping an author with the process.

**Comment by wjmelements** [comment]
Proposed alternative https://github.com/ethereum/EIPs/pull/2936

**Pull request closed without merging**
