### PR TITLE
Update EIP-1155: Fix arg order for balanceOf

### PR DESCRIPTION
**Pull request by cha0sg0d**
In ERC1155, the function balanceOf is defined as follows:
function `balanceOf(address _owner, uint256 _id) external view returns (uint256);`

However, in the [Split ID bits](https://eips.ethereum.org/EIPS/eip-1155#split-id-bits) section of EIP1155, the ordering of args is reversed:
```js
balanceOf(baseTokenNFT, msg.sender); 
balanceOf(baseTokenNFT + indexNFT, msg.sender); 
balanceOf(baseTokenFT, msg.sender); 
```
This PR simply switches the args to match the spec.

### CODE REVIEW

**Comment by Pandapip1** [comment]
Please fix the EIP Walidator errors.

**Comment by Pandapip1** [comment]
> @Pandapip1 sorry for the trouble, but it looks like the EIP Walidator errors aren't related to the code snippet I changed. Could you advise on how to remove the errors?

Ah - this changes a final EIP. This is waiting for approval from one of (@coinfork, @AC0DEM0NK3Y, @wighawag) and then we can merge this manually.

**Review by xinbenlv — APPROVED** [review]
Thank you for the correction. I checked it's appropriate. Please consider a manuel approval because this is a final EIP. @SamWilsn

**Review by Pandapip1 — APPROVED** [review]

**Comment by SamWilsn** [comment]
Tagging @PhABC as well.

**Comment by cha0sg0d** [comment]
> There has been no activity on this pull request for 2 weeks. It will be closed after 3 months of inactivity. If you would like to move this PR forward, please respond to any outstanding feedback or add a comment indicating that you have addressed all required feedback and are ready for a review.

pinging @PhABC @SamWilsn just to make sure this gets addressed before PR is auto-closed. Thanks!

**Comment by Pandapip1** [comment]
I think this change is sufficiently minor that a manual merge is justified. Tagging @SamWilsn - thoughts?

**Comment by SamWilsn** [comment]
I got in touch with @PhABC on twitter, but I guess he hasn't come by yet.

**Comment by Pandapip1** [comment]
Waiting on author review. Re-CC @PhABC

**Comment by Pandapip1** [comment]
Waiting on author review. Re-CC @PhABC

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Skylerspencer** [comment]
Haven't because don't understand this and you guys know that instead of
just giving me my cause you can  you want to keep playing this I'm a god
thing but there are some gods I known bigger and more powerful then any of
you so in less it's access to just get my money with a id or bank card nio
need to continue this  game thanks good night  the loser right. Please stop
texting me if it's not your money is in the bank thank you.

**Review by wighawag — APPROVED** [review]

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
