### PR TITLE
Update EIP-627: fix typo

### PR DESCRIPTION
**Pull request by momodaka**
metainformation -> Meta-information
excuding -> excluding
possiblitity -> possibility

### CODE REVIEW

**Comment by g11tech** [comment]
@momodaka  unfortunately you might also need to fix some other linter rules to get this PR merge ready

**Comment by momodaka** [comment]
all lint issue are fixed

**Review by g11tech — CHANGES_REQUESTED** [review]
umm there is an author change, so could you get the original author to approve the change

**Comment by SamWilsn** [comment]
Since this is a Final EIP, and this is changing more than typos, @lightclient and I feel we should close this without merging.

**Pull request closed without merging**
