### PR TITLE
EIP-1047 - Enhancements to token metadata json schema

### PR DESCRIPTION
**Pull request by jamesmorgan**
* Enhancement to - https://github.com/ethereum/EIPs/blob/master/eip-1047.md

This PR closes the original issue raised here https://github.com/ethereum/EIPs/pull/1028 and expands on the original draft EIP-1047 which was merged in here https://github.com/ethereum/EIPs/pull/1047

Further discussion can be found here https://www.reddit.com/r/raredigitalart/comments/8hfk2a/token_metadata_json_schema_eip_1047/

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1047 requires approval from one of (@mateosu, @tomasienrbc, @johnzettler)

**Comment by axic** [comment]
Ping @mateosu, @tomasienrbc, @JohnZettler.

**Comment by maria1118** [comment]
Appreciate your patience with me

**Comment by maria1118** [comment]
liquid I can get my car back #1071

**Comment by GrzegorzWil** [comment]
but what should I do, somehow I do not know that it will work. Is it
possible? what should I include a lot of portweli keys in the tex file,
what agreements it is about, how to get to it

sob., 3 sie 2019 o 15:08 Ria C <notifications@github.com> napisał(a):

**Comment by maria1118** [comment]
Go ahead be merry

**Comment by skyfly200** [comment]
Hello, I think this EIP serves a valid point. It encourages the interoperability of NFTs across platforms. This encourages the ethos of the metaverse with assets ownable beyond platforms and accessible across the Web3 space.

**Pull request closed without merging**
