### PR TITLE
Add Nick Savers, remove Yoichi on EIP editors list

### PR DESCRIPTION
**Pull request by fulldecent**
As discussed in https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2031.md#10957-decision-process-for-eips

@nicksavers is now an editor for the EIPs.

### CODE REVIEW

**Comment by veox** [comment]
The meeting notes also mention Yoichi Hirai, but he has [recently resigned](https://github.com/ethereum/EIPs/pull/867#issuecomment-365800936).

Would it make sense to add the change removing Yoichi in this PR, too? (Probably less chance of git merge conflict.)

**Comment by fulldecent** [comment]
@veox Thank you, updated.

**Comment by fulldecent** [comment]
Pinging @pirapira since you are mentioned

**Comment by pirapira** [comment]
No problem.

**Pull request merged**
