### PR TITLE
Update eip-634.md

### PR DESCRIPTION
**Pull request by DutchBoyd**
Hey Rick. 
Thanks for the good work. Hope to meet you in person one day.
I'm updating my dutch.eth name to include my Twitter handle and came across this description of what the vnd.twitter should be. It was a little bit confusing having the "SHOULD" capitalized and the "not" uncapitalized, so figured I'd suggest this small change and capitalize both words.
-Dutch

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 634 requires approval from one of (@ricmoo)

**Comment by ricmoo** [comment]
Ah thanks! I will get to this today. I also have a few other changes I’d like to make to this, but I need to bounce them off some people first, but thanks for reminding me. :)

**Comment by axic** [comment]
@ricmoo can this be merged?

**Comment by ricmoo** [comment]
How do I reopen this? I don’t seem to have permission.

**Comment by MicahZoltu** [comment]
@ricmoo Done.  If you are the author of this EIP and you want to merge this PR then just do a GitHub PR Review and choose approve.

**Pull request closed without merging**
