### PR TITLE
Add EIP: dApp Permission Framework (DPF)

### PR DESCRIPTION
**Pull request by jqphu**
Adding initial draft here to get EIP number and link before sharing in Ethereum Magicians.

Note: I've placed this in the EIP Interface section not ERC as I see other wallet related EIPs here.

Let me know if there's something I've missed in the process :).

### CODE REVIEW

**Comment by BigBro17on25tolife** [comment]
Hey Justin, I'm new to the platform, still learning I appreciate your work
hope you don't mind if I tag along👍

**Comment by abcoathup** [comment]
> Note: I've placed this in the EIP Interface section not ERC as I see other wallet related EIPs here.

@jqphu as this is at the app layer it should be an ERC.

**Comment by jqphu** [comment]
> > Note: I've placed this in the EIP Interface section not ERC as I see other wallet related EIPs here.
> 
> @jqphu as this is at the app layer it should be an ERC. Suggest closing this PR and creating a PR in the ERC repo. Then an ERC number can be issued.

Got it, will do. Thanks!

**Comment by jqphu** [comment]
Replaced with https://github.com/ethereum/ERCs/pull/217

**Pull request closed without merging**
