### PR TITLE
Move EIP-155 status to Active because people are changing it

### PR DESCRIPTION
**Pull request by fulldecent**
Changes to this EIP include prescriptive changes, such as these recent ones

> 7bfdc93b00bdba468ae5373ec86dacef1fe2d992 @Arachnid 
> af5c1aed95ebf14478b66b1c283c83b59991695a @nicksavers 

The addition of this information materially affects the specification. Therefore this EIP is not properly classified as FINAL, it should be ACTIVE.

### CODE REVIEW

**Comment by Arachnid** [comment]
I don't understand the point of this. The changes are to a table that is explicitly intended to be kept up to date, and "Active" isn't a valid state for this kind of EIP.

Flagging every EIP containing a table as Active would be pointless and confusing, and we're not at the point where we need a separate registry of tables like the IETF.

**Comment by fulldecent** [comment]
Does there exist any other EIP that contains a table which will be kept up to date?

Because 155 contains a changing table, it will never be possible to fully "implement EIP-155". Instead, the best you can say is that an implementation "recognizes the networks in EIP-155 as of March 5, 2019".

This is distinguishable from ERC-721 which *can* be implemented in full and is not expected to have any prescriptive changes applied.

**Comment by Arachnid** [comment]
@fulldecent Sure - for instance, EIP 137 (ENS) contains a list of resolver profiles. Anecdotally, I've seen many other EIPS with tables of this kind.

Implementing EIP 155 does not require copying the table into your implementation; all implementing it requires is that you accept an integer for the chain ID value. The table is informative for people wanting to allocate new chain IDs while avoiding conflicts with existing ones.

**Comment by nicksavers** [comment]
We can move out the network id's into an external table if this keeps updating. For now I'd like to close this issue to focus on more important discussions.

**Pull request closed without merging**
