### PR TITLE
Change "Hard Fork" for "Network Upgrade"

### PR DESCRIPTION
**Pull request by timbeiko**
It seems the consensus within the Ethereum community is now to use "network upgrade" over "hard fork". This change updates EIP-1 to reflect this. 

There was a conversation about this in a different PR (see https://github.com/ethereum/EIPs/pull/2508#discussion_r376796355), but for visibility I wanted to separate this into a distinct PR. 

From the PR linked above: 
> FWIW, "network upgrade" is what is currently used in communications from the EF, see [Muir Glacier](https://blog.ethereum.org/2019/12/23/ethereum-muir-glacier-upgrade-announcement/), [Istanbul](https://blog.ethereum.org/2019/11/20/ethereum-istanbul-upgrade-announcement/), [Constantinople](https://blog.ethereum.org/2019/02/22/ethereum-constantinople-st-petersburg-upgrade-announcement/). Last use of "hard fork" was for [Byzantium](https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/).

### CODE REVIEW

**Comment by edsonayllon** [comment]
I'm still at the perspective of preferring the term "update" over "upgrade." "Upgrade" for every hard fork may not be completely correct, as something like delaying the difficulty bomb may need a hard fork, but isn't necessarily an upgrade. I think Microsoft and Apple use the term "update" to label changes to their operating systems, and then specify what kind of update, either a feature update (an upgrade), or a maintenance update, and then there are performance updates. 

But, I do agree on changing the term "hard fork." As, hard fork has associations with Bitcoin Cash/Bitcoin, and Ethereum Classic/Ethereum, where hard fork can be interpreted as splitting, instead of pivoting towards an improvement.

**Comment by Souptacular** [comment]
I have come around to accepting that network upgrade is a better term than hard fork because of the connotations around hard fork described by Edson and Tim. I do want to advocate for "network upgrade" vs "network update".

An Ethereum update to me implies a client update that updates your node to perform enhancements or optimizations at the client level. Upgrade is a term with more weight that to me indicates that major changes have occurred requiring all to upgrade. Additionally, ZCash uses network upgrades and I think we shouldn't make a third term within major cryptocurrency networks. I support using "network upgrade".

Example of ZCash using network upgrade terminology: https://z.cash/upgrade/blossom/

**Comment by timbeiko** [comment]
+1 on "upgrade" vs. "update".

**Comment by edsonayllon** [comment]
I see. Network upgrade is fine with me.

**Comment by Souptacular** [comment]
LGTM. We should merge now that we have decided that network upgrade is the right vernacular.

@timbeiko the last thing you need to do is add a line to the History section at the bottom of EIP-1 to indicate the change.

**Comment by axic** [comment]
Does changing that single instance in EIP-1 have any measurable effect? The "hard fork metas" are still called like that.

If terminology change is wished, probably a good step would be getting an agreement from ACD for the new terminology and applying that cross the EIP repo.

**Comment by Souptacular** [comment]
@axic good point. @timbeiko what do you think?

**Comment by timbeiko** [comment]
@axic good point. Do you think the ACD gitter is the best place to bring this up? The calls seem not ideal.

**Comment by axic** [comment]
Probably getting buy-in from clients would be a good way, so that their messaging also uses the new terminology.

**Comment by timbeiko** [comment]
Closed in favor of https://github.com/ethereum/EIPs/pull/2624

**Pull request closed without merging**
