### PR TITLE
EIP-258 - 2 Factor Authentication within Smart contracts to provide a second layer of security. 

### PR DESCRIPTION
**Pull request by VexyCats**
This ERC could be used across the ecosystem by individual smart contracts, or used as one general smart contract for the entire mainnet. If used individually, I'd host my own login server like traditional websites offer now, but also implementing the new standard within my smart contract and running a registeredAgent node on my server. This would allow for my project to provide its own second layer security over my project's smart contracts. So my users have extra protection.

If a global contract is used for the entire ecosystem, then replace "my"  with "any" in the explanation above. ie: This would allow for any project to provide its own second layer security over any project's smart contracts. So any project's users would have extra protection.

### CODE REVIEW

**Comment by Arachnid** [comment]
What's stopping an attacker just reading the current 2FA code from the contract's storage?

**Comment by VexyCats** [comment]
Nothing at all. But accessing the code doesn't matter unless they also have the private key. Since sending a transfer from their address with my code, does nothing. 

Sending a transfer from my address with my code is how you steal funds. But you need my private key, and now, my code. To get my code, you need my username and password, from the registeredAgent's traditional log in, that sends the code. Or you need to be actively waiting for a code to be generated. Regardless, still a second layer. 

Thoughts? Great question!

**Comment by MicahZoltu** [comment]
How does this differ from a multisig?  Fundamentally, it feels like this is just a multisig where one signer is the user, the other signer is some service provider.

What happens if the service provider disappears, how do you regain access to your funds?

**Comment by VexyCats** [comment]
@MicahZoltu Thats exactly what it is. Just another way to provide multisig for users who are keen on using it. Good UX means offering every service someone might want! 

If the service provider goes offline, or a code can't be generated, a flag needs to be set on the smart contract to allow withdrawals without a code.

**Comment by Arachnid** [comment]
> Or attacker needs to be actively waiting for a code to be generated after stealing private key. Regardless, still a second layer. 

Any attacker can just wait for the code to be submitted, automatically submit it, and then frontrun the user's transaction. This doesn't add any  real security, only obscurity. I also don't see any reason for this to be a standard, as opposed to just a contract.

**Comment by VexyCats** [comment]
Well the attacker would need the private key of the account they are stealing.... So whereas in the flow of stealing an account would go like this:

Without 2FA: 
Get access to private key
Execute transaction. 
Funds stolen

With 2FA on Contract:
Get access to private key
Now need to wait for the user to submit a code, could be months that the hacker has no idea when its being submitted, they just wait. 
Then front run their transaction. 

So it does provide some level of waiting for a hacker, and if they are not using a 24/7 automated script, most likely would not be aware someone has generated a code.

**Pull request closed without merging**
