### PR TITLE
EIP-681: move to Last Call

### PR DESCRIPTION
**Pull request by nagydani**
As there were no more change requests while ERC-681 was in Review, it can move on to Last Call

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 681 state from Review to Last Call

**Comment by nagydani** [comment]
@MicahZoltu , could you please take a look? Obviously the review-period-end needs to change, but it is up to the editor to assign, I was just hoping for a speedy merge since there was no more feedback during the Review period.

**Comment by MicahZoltu** [comment]
I'm not handling ERCs anymore, so you'll have to wait for one of the other editors to check it out.  Sorry!

**Comment by nagydani** [comment]
@Souptacular , could you please take a look? Obviously the review-period-end needs to change, but it is up to the editor to assign, I was just hoping for a speedy merge since there was no more feedback during the Review period.

**Comment by Souptacular** [comment]
Hey @nagydani! Go ahead and change the review-period-end and I will merge the last call status today.

**Comment by nagydani** [comment]
> Hey @nagydani! Go ahead and change the review-period-end and I will merge the last call status today.

Hey @Souptacular ! Missed your message from last week, but better late than never, just changed the review-period-end as required, so please merge. Also, if you cannot merge today, feel free to edit the review-period-end yourself; AFAIK, it is up to the editors to set, I just wanted to be proactive.

**Comment by Souptacular** [comment]
Merged. Thank you @nagydani!

**Pull request merged**
