### PR TITLE
eip-2535.md updates

### PR DESCRIPTION
**Pull request by mudgen**

### CODE REVIEW

**Comment by mudgen** [comment]
I don't know why CI failed.

@MicahZoltu or @lightclient can you please merge this?

**Comment by mudgen** [comment]
@axic Do you know how to fix `travis-ci` so I can get my pull request merged?

**Comment by mudgen** [comment]
@holiman travis-ci is down/not working.  Can you please merge my changes?

**Comment by MicahZoltu** [comment]
CI is currently broken.  Hopefully it will get fixed soon at which point someone will hopefully go and poke all of these EIPs it failed on which will trigger a re-run.

**Comment by mudgen** [comment]
@MicahZoltu Thanks for this update.  Do you know if someone is working on fixing the CI?

**Comment by lightclient** [comment]
@mudgen it should be fixed via #3007.

**Comment by mudgen** [comment]
> @mudgen it should be fixed via #3007.

@lightclient Yes, thank you. It works now.

**Pull request merged**
