### PR TITLE
Move EIPs activated Byzantium to Finalized

### PR DESCRIPTION
**Pull request by nicksavers**

### CODE REVIEW

**Comment by MicahZoltu** [comment]
We should really merge the various EIPs as well (I'm not suggesting this be held up for that though).  For example, https://github.com/ethereum/EIPs/pull/211 is still un-merged, so the link in this document refers to a PR rather than a file (which is what it really should point at for finalized EIPs).

**Comment by rachel-rose** [comment]
+1

**Comment by 5chdn** [comment]
Yes, I already finalized #669 - would be nice to have an overall process for that.

**Comment by 5chdn** [comment]
There was some confusion about "_my meta EIP_", I think you were talking about this one #609

**Comment by nicksavers** [comment]
That's correct. The EIP #669 you linked to directly refers to that in the description, so my assumption was that you also wrote that one, but @axic did. I'll close this EIP in favour of #770 which includes #609 in the README as finalized.

**Pull request closed without merging**
