### PR TITLE
Update EIP-7742: Move to Review

### PR DESCRIPTION
**Pull request by ralexstokes**
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by SamWilsn — CHANGES_REQUESTED** [review]
Please remove the "TBD" and replace with its actual value before moving to review. You can instead remove the whole `FORK_TIMESTAMP` thing (it's a holdover from ancient EIPs), and just say "after this proposal is activated" or similar.

**Comment by ralexstokes** [comment]
@SamWilsn done!

**Comment by g11tech** [comment]
> @SamWilsn done!

CI failing

**Comment by ralexstokes** [comment]
> > @SamWilsn done!
> 
> CI failing

@g11tech fixed, thanks!

**Review by lightclient — APPROVED** [review]

**Pull request merged**
