### PR TITLE
Revert EIP-695 to draft

### PR DESCRIPTION
**Pull request by fulldecent**
Last call is long overdue

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 695 state from Last Call to Draft
 - EIP 695 requires approval from one of (isaac.ardis@gmail.com, @tcz001, @sorpaas)

**Comment by fulldecent** [comment]
The fact that it is implemented is not a good reason to skip Last Call.

**Comment by sorpaas** [comment]
@fulldecent Hmm EIP-695 is already in Last Call status and "Final" is the status after that. Have I understand this correctly? Or do you mean it's better for EIP-695 to stay in draft? I'm fine with that as well!

**Comment by fulldecent** [comment]
Got it. Please make a separate PR to promote from Last Call to Final and include the normal notes that are included these types of PRs. (You can use BLAME against `status: Final` lines in other recent Final EIPs to see this.)

**Pull request closed without merging**
