### PR TITLE
Update EIP-2070: Move to Withdrawn

### PR DESCRIPTION
**Pull request by timbeiko**
See https://github.com/ethereum/EIPs/pull/8005#issuecomment-1845557812, cc: @axic

### CODE REVIEW

**Comment by timbeiko** [comment]
Blocking https://github.com/ethereum/EIPs/pull/8048

**Comment by timbeiko** [comment]
@axic ser

**Comment by timbeiko** [comment]
@axic FYI I've removed the reference to 2070 in EIP-7568, which is now in last call, see https://github.com/ethereum/EIPs/pull/8172. Assuming this PR got merged, I'd be happy to link it back. Otherwise, I'll finalize 7568 without the 2070 mention on Feb 23rd.

**Review by axic — APPROVED** [review]

**Review by Raimbow04 — COMMENTED** [review]
Cool merci

**Review by Raimbow04 — COMMENTED** [review]
Cool

**Review by nullkecakke256felix-blip — APPROVED** [review]

**Pull request merged**
