### PR TITLE
Update Template: New EIP for a Collateralized NFT Standard

### PR DESCRIPTION
**Pull request by harpocrates555**
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by abcoathup** [comment]
@harpocrates555 please create your ERC PR in the ERC repo (https://github.com/ethereum/ercs) and close this PR.

Please create a new file for your ERC rather than modifying the template.

**Comment by harpocrates555** [comment]
> @harpocrates555 please create your ERC PR in the ERC repo (https://github.com/ethereum/ercs) and close this PR.
> 
> Please create a new file for your ERC rather than modifying the template.

Hi @abcoathup , thank you for guidance. Can you please let us know which file name we should use? We will absolutely close this PR and create a new one.

**Comment by abcoathup** [comment]
> should


> Can you please let us know which file name we should use?

Call it collateralizedNFT.md. You can rename it once an ERC number has been issued.

**Comment by harpocrates555** [comment]
Done, thank you so much! @abcoathup

**Pull request closed without merging**
