### PR TITLE
Responsible Disclosure EIP

### PR DESCRIPTION
**Pull request by yrashk**
It's a pretty simple EIP. Feedback is welcome!

### CODE REVIEW

**Comment by Arachnid** [comment]
This seems entirely too specialised to me; something that would be better accomplished with metadata such as an ENS text record.

**Comment by yrashk** [comment]
Nick, the idea for having this as a separate ERC is to enable its universal use for the most barebones scenarios -- regardless whether ENS or anything like it is used.

**Comment by Arachnid** [comment]
It's not the separate EIP that I'm objecting to, it's inventing another special purpose method for it.

**Comment by Arachnid** [comment]
This is a courtesy notice to let you know that the format for EIPs has been modified slightly. If you want your draft merged, you will need to make some small changes to how your EIP is formatted:

 - Frontmatter is now contained between lines with only a triple dash ('---')
 - Headers in the frontmatter are now lowercase.

If your PR is editing an existing EIP rather than creating a new one, this has already been done for you, and you need only rebase your PR.

In addition, a continuous build has been setup, which will check your PR against the rules for EIP formatting automatically once you update your PR. This build ensures all required headers are present, as well as performing a number of other checks.

Please rebase your PR against the latest master, and edit your PR to use the above format for frontmatter. For convenience, here's a sample header you can copy and adapt:

```
---
eip: <num>
title: <title>
author: <author>
type: [Standards Track|Informational|Meta]
category: [Core|Networking|Interface|ERC] (for type: Standards Track only)
status: Draft
created: <date>
---
```

**Comment by nicksavers** [comment]
@yrashk Could you link to an implementation of this proposal? I'm closing this now for inactivity. It can be reopened if there is any progress on it.

**Pull request closed without merging**
