### PR TITLE
Change EIP-5131 to use ENS TEXT records for signing resolution

### PR DESCRIPTION
**Pull request by wwhchung**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by Pandapip1** [comment]
I would definitely like to investigate this.

**Comment by Pandapip1** [comment]
Aha, I think it happens when multiple pushes are done at the same time. I think I have an idea to fix this.

**Comment by Pandapip1** [comment]
Okay, it appears that the easy solution is to add the `Automerge / automerge` check as a required check in the branch protection settings.

**Comment by Pandapip1** [comment]
@MicahZoltu

**Comment by MicahZoltu** [comment]
Done, but why would one expect that to help?

**Pull request merged**
