### PR TITLE
Remove Deferred from the status list

### PR DESCRIPTION
**Pull request by axic**
It doesn't seem to serve any purpose. It could suggest those EIPs have been properly discussed
and accepted, but are deferred. It could also suggest there's no point discussion them now,
but that doesn't seem to be too different from draft.

### CODE REVIEW

**Comment by Arachnid** [comment]
> It could suggest those EIPs have been properly discussed and accepted, but are deferred.

Isn't that just what it means? As the description says, it's for EIPs that are planned for a future hard fork.

**Comment by axic** [comment]
> Isn't that just what it means?

It may mean that but the EIPs marked as such definitely don't fall under that description.

**Comment by axic** [comment]
And I don't understand the notion that something can be well discussed and agreed on, then postponed and at the next hard fork it won't start over again in the review process, because changes implemented in the last hard fork likely would render these "deferred" EIPs vulnerable to issues. There may exists a very few exceptional cases, but not sure it is worth the complexity having this special status for those rare cases.

**Comment by Arachnid** [comment]
Well, we're trying to remove fork acceptance as being a driver of status anyway, right? That's what fork meta EIPs are for. Do we have other statuses that could be removed for the same reason?

**Comment by axic** [comment]
> Well, we're trying to remove fork acceptance as being a driver of status anyway, right? That's what fork meta EIPs are for.

I wouldn't say the reason for this PR here is that. To me the deferred status in general doesn't seem to make sense for the above reason I've explained. At least the currently marked EIPs shouldn't be deferred because I don't recall any of them were discussed in depth in the first place.

> Do we have other statuses that could be removed for the same reason?

I think the rest is fine. I can see that "Rejected" likely will only be applied to EIPs which are proposed for hard forks, because it doesn't seem that "ACD calls" will bother reviewing random EIPs/ERCs and forming an opinion on them. That being said it is still a useful status.

**Comment by Arachnid** [comment]
> I wouldn't say the reason for this PR here is that. To me the deferred status in general doesn't seem to make sense for the above reason I've explained. At least the currently marked EIPs shouldn't be deferred because I don't recall any of them were discussed in depth in the first place.

Sure, but my overall point is that this is cleanup we should be doing anyway.

**Comment by nicksavers** [comment]
You're missing the one in https://github.com/ethereum/EIPs/blob/master/index.html
Other than that I'm fine with this.

**Comment by axic** [comment]
@nicksavers fixed!

**Comment by axic** [comment]
@nicksavers ping

**Pull request merged**
