### PR TITLE
Add anchor headings to EIPs website

### LINKED ISSUE #1106: Support anchor tags on eips.ethereum.org (direct links to sections)

### LINKED ISSUE #1314: Website: show permalink on mouseover
On GitHub, if you mouseover a H1 or H2... heading then you will see a permalink on the left which links directly to that anchor. This is helpful referencing documentation in EIPs because yon can link to the specific text that is relevant.

Now that we have switched from GitHub code repository to the EIP website as being the canonical place to cite EIPS, I would like to request the same feature there.

Additionally, I would like to ask for paragraph-specific selectors if possible. The text of web pages on EIPS.ethereum.org are likely to stay unchanged for a long time. So it will be helpful to link to specific paragraphs if we can.

I'm doing smart contract audits now, it is great to link to the specific thing that illustrates problems in my findings.

### PR DESCRIPTION
**Pull request by ryanio**
This PR adds [jekyll-anchor-headings](https://github.com/allejo/jekyll-anchor-headings) to the EIPs website like so:

Screen Shot 2020-03-31 at 2 24 30 PM

Closes #1106.
Closes #1314.

### CODE REVIEW

**Comment by axic** [comment]
This is awesome, it seems to work!

However, it gets confused with multiple levels of headings. As an example in EIP-1474 each method has a Description and Parameters subheading. Each of them get a heading, but the subsequent ones have a number postfix. Would it be possible to making those deep heading have the higher level heading as a prefix in the anchor?

**Comment by axic** [comment]
It seems setting `h_max` to 2 would be a good middle ground. If we want to be fully safe, we only want the highest level heading to be anchored (the sections of an EIP).

**Comment by ryanio** [comment]
hm thinking about this, I think deep linking is useful. It’s helpful when referencing from other docs and you want to be specific to a section.

**Review by MicahZoltu — APPROVED** [review]
I was *just* wanting this yesterday and wondering how hard it would be to add.  Glad to see someone already did the work!

I agree with @axic that we could probably "do better" with various levels of linking but I think even without dealing with that problem this is a pretty big improvement.  If someone wants to submit a PR after that tunes/tweaks this I would be fine with that.

**Comment by MicahZoltu** [comment]
Merging this since there was no hard vetos and the only negative feedback was basically "we could do better".  If someone wants to do better, I will support an iterative improvement on top of this change, but in the meantime I think this is significantly better than nothing.

**Pull request merged**
