### PR TITLE
Add EIP: Self Tradable NFT

### PR DESCRIPTION
**Pull request by yjgaia**
Discussion thread: https://ethereum-magicians.org/t/proposal-for-a-new-eip-self-tradable-nft/15491

### CODE REVIEW

**Comment by Hanul** [comment]
## Implementation

- https://github.com/gaiaprotocol/self-tradable-nft

**Comment by abcoathup** [comment]
EIP/ERC numbering changes to sequential from 7500 and is no longer the PR number: https://github.com/ethereum/EIPs/issues/6990#issuecomment-1648535814

Assigning number 7502.

**Review by AnitaLHoward — APPROVED** [review]

**Review by Aryan9592 — APPROVED** [review]

**Comment by hanul** [comment]
In ERC-7502, blocking Approval when NFT is in Self Tradable mode ensures safety against hacking attempts to acquire Approval.
https://github.com/gaiaprotocol/self-tradable-nft/commit/486e387350a1544fa93e84032baba11a4706dcfe

**Comment by SamWilsn** [comment]
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

**Pull request closed without merging**
