### PR TITLE
Add `Table of Contents` to EIPs website

### PR DESCRIPTION
**Pull request by ryanio**
This PR adds [jekyll-toc](https://github.com/allejo/jekyll-toc) to the EIPs website like so:

Screen Shot 2020-03-31 at 2 29 23 PM

### CODE REVIEW

**Comment by axic** [comment]
I think this would be a very useful feature. I would however suggest we get to an agreement in #2581 regarding the anchors and use the same configuration here.

**Comment by axic** [comment]
Also have you tried running this together with #2581? I have a hunch that this plugin also creates anchors as those are needed for the ToC and likely we don't need to install both?

**Comment by ryanio** [comment]
> Also have you tried running this together with #2581? I have a hunch that this plugin also creates anchors as those are needed for the ToC and likely we don't need to install both?

Good point, I did run it together and it worked well but didn’t investigate how much anchor functionality might be included just with the ToC plugin. 

We might not be able to get the nifty icon on hover without the anchor plugin, but I’ll investigate further and report back.

Thanks for taking a look!

**Comment by ryanio** [comment]
@axic I took a look and #2581 would be needed for the on:hover icon next to the heading to get the permalink. I think it's useful, but you're right that people could just find the anchor link from the table. I don't see any harm in having both.

**Review by MicahZoltu — APPROVED** [review]
Was also looking for this feature the other day.

**Comment by axic** [comment]
Apparently this gets confused when there are too nested headings:
Screenshot

**Comment by axic** [comment]
With `h_max=3`:
Screenshot

**Comment by MicahZoltu** [comment]
I wonder if the reason it failed for 1011 is because that EIP skips some levels:
```md
## Specification

#### Deploying Casper Contract
```

If that is the problem and this otherwise works with up to `n` levels, then I think we should just fix EIP-1011 (and any others that have incorrect nesting) rather than losing ToC for everything below h3 (which I believe is always going to only be 2 levels deep).

**Comment by axic** [comment]
>I wonder if the reason it failed for 1011 is because that EIP skips some levels:

That might be a reason, good find.

What I am more concerned about is that each anchor heading is just the title itself, so if there's overlapping text somewhere, then it will not work properly. Perhaps this is an unfounded concern and is rather something what should be warned about in EIP-1 and either enforced in eipv or just left as a decision for EIP authors.

---

Merging this and #2581 results in anchor headings, but no toc being displayed.

**Comment by ryanio** [comment]
Ah nice investigation guys about the header levels.

> What I am more concerned about is that each anchor heading is just the title itself, so if there's overlapping text somewhere, then it will not work properly.

Do you mean if there are multiple headers with the same text it’ll get confused? I think standard behavior is to append a number like -1 and -2 to the url to dedupe them. I can check if this plugin supports that. 

> Merging this and #2581 results in anchor headings, but no toc being displayed.

Hm when I first opened these PRs I had them running together on local and it worked well so I split them up just for the PRs (I knew anchor headings were pretty agreeable due to prior issues but wasn’t so sure about the ToC). I can take a closer look if you can’t resolve, let me know. We can also merge both features one branch if that makes this process easier.

**Comment by ryanio** [comment]
Hey @axic @MicahZoltu is there anything I can do to help get this and #2581 merged in?

**Comment by MicahZoltu** [comment]
I just merged #2581 which has caused this PR to now be in conflict with master.  Can you resolve those conflicts and verify that both anchors and ToC work once the merge conflict is resolved?

Also, I think we either need to go through and find and fix all EIPs that skip nesting levels (like 1011) or we need to restrict nesting to 1 or 2 levels (which in this repository actually means `h_max=3`).  It is probably easier to just limit to `h_max=3`, so that is my recommendation and then perhaps a PR that fixes nesting repository wide, followed by a PR that changes `h_max` to something like 5.

**Comment by ryanio** [comment]
@MicahZoltu great! thanks. just resolved the conflict. yes `h_max` is currently set to 3 so that should be good for now. I like the idea of fixing the EIPs with skipped nesting levels then bumping the number up.

**Comment by MicahZoltu** [comment]
@ryanio Were you able to test this (after resolving merge conflicts) to verify that both anchors and ToC work?  Particularly on problematic ones like EIP-1011.  Once someone has confirmed they have tested after having resolved the conflicts I'll merge this.

For context, the reason I want that extra step of validation is because someone mentioned there was a problem in the thread above, so I want to make sure we do due diligence.

**Comment by ryanio** [comment]
@MicahZoltu yes just tested the branch, 1011 looks like it's rendering fine with h_max=3 and the anchor headings also work:

Screen Shot 2020-10-29 at 12 05 36 PM

Any other problematic EIPs I can possibly take a look at?

If there are too many EIPs to check manually we could write a script to check for other cases of skipped heading levels. That would be a nice future PR to round up all the fixes and remove the ToC h_max limit.

**Comment by MicahZoltu** [comment]
If you are up for writing an automated script that fixes the invalid nesting in all EIPs that would be great, and then we could potentially increase the ToC h_max up.  However, I'm quite happy with this change alone and would be satisfied if no further progress was made.

**Pull request merged**
