### PR TITLE
EIP-712: Make TypedData schema stricter

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request attempts to clarify and tighten the `TypedData` schema provided by EIP-712 by making necessary fields `required`. It's not possible to properly infer or encode type information without `types` and a `primaryType`, [EIP-191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-191.md) conformance mandates a 32-byte "version specific" `domain`, and domain encoding in turn requires a `types.EIP712Domain` type definition. Alternatively, the schema could specify default values for necessary fields, but it's not clear what those default values should be.

From a high level, the proposal should detail how implementations should handle encoding when certain values are not provided. Context: we're implementing the latest EIP-712 changes in MetaMask and we're trying to determine what parameters to validate or default beyond validation of the current schema (which seems insufficient.)

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 712 requires approval from one of (@logvinovleon, remco@wicked.ventures, @dekz)

**Comment by Recmo** [comment]
> EIP-191 conformance mandates a 32-byte "version specific" domain.

Minor nitpick: EIP-191 does not specify this. It only requires that EIP-712 encoded signed data starts with `0x1901`. It is EIP-712 itself that requires the 32 byte domain separator.

**Comment by Recmo** [comment]
@Arachnid  I'm not sure if @eip-automerger recognized my approval. The `remco@wicked.ventures` email address was not linked to my GitHub account before, but it is now.

**Comment by LogvinovLeon** [comment]
@Recmo Let's see if it picks up my approval

**Pull request merged**
