### PR TITLE
Update EIP-5553: Move to Review

### PR DESCRIPTION
**Pull request by royosherove**
2nd try - mistakenly removed previous review request.

### CODE REVIEW

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Please fix the spdx license identifiers.

**Comment by royosherove** [comment]
> Please fix the spdx license identifiers.

Moved to CC0

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Please fix all the grammar issues. I recommend Grammarly.

**Comment by royosherove** [comment]
bump. Grammarly was pretty useful. Thanks for the suggestion. Let me know if we're good to go.

**Comment by royosherove** [comment]
bump   - any other feedback? is it OK to merge?

**Review by Pandapip1 — APPROVED** [review]

**Pull request merged**
