### PR TITLE
Update word choice

### PR DESCRIPTION
**Pull request by fulldecent**
++

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1592 requires approval from one of (cyril.lapinte@mtpelerin.com, laurent.aapro@mtpelerin.com)

**Comment by axic** [comment]
@sirhill can you approve?

**Comment by MicahZoltu** [comment]
Or deny, we (editors) just dislike having the PRs open indefinitely.

**Comment by axic** [comment]
Yes, I meant to write "review", but got lazy.

**Pull request closed without merging**
