### PR TITLE
Updates to 3541 (test cases and mark as review)

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Review by lightclient — APPROVED** [review]
Looks good to me - only potential issue is that the table isn't rendering properly on github. Maybe this is to render correctly on the EIPs website?

**Comment by axic** [comment]
> Looks good to me - only potential issue is that the table isn't rendering properly on github. Maybe this is to render correctly on the EIPs website?

Good catch! It was rendering correctly in hackmd, but github is not so lenient on the extra column in the header separator. Fixed.

**Comment by axic** [comment]
@MicahZoltu @lightclient can this merged by any chance before the ACD tomorrow?

**Comment by axic** [comment]
Thanks @MicahZoltu!

**Pull request merged**
