### PR TITLE
EIP2981

### PR DESCRIPTION
**Pull request by blmalone**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 2981 requires approval from one of (@jamesmorgan, @vexycats)

**Comment by VexyCats** [comment]
Hey @blmalone I think you need to make the PR on my repo in my github, and I'll merge the changes into the EIP which is approved automatically

**Comment by MicahZoltu** [comment]
@VexyCats If you do a GitHub review of this PR and approve it, the bot will auto-merge directly.  No need to PR against your repository separately.

**Comment by blmalone** [comment]
@VexyCats I'm keen to brainstorm a little more on this EIP. Are you actively working on it? I see there are some other competing.

**Review by VexyCats — APPROVED** [review]
Looks good

**Pull request merged**
