### PR TITLE
Move EIP-712 to review

### PR DESCRIPTION
**Pull request by lightclient**
Seems like we can start inching this to final? @Recmo @LogvinovLeon @dekz

### CODE REVIEW

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - Trying to change EIP 712 state from draft to review
	 - eip-712.md requires approval from one of (recmo,logvinovleon,dekz)

**Comment by lightclient** [comment]
bump @Recmo @LogvinovLeon @dekz

**Review by LogvinovLeon — APPROVED** [review]

**Comment by lightclient** [comment]
Thanks @LogvinovLeon :)

**Comment by lightclient** [comment]
@alita-moore seems like the bot is blocking this merge too?

**Comment by MicahZoltu** [comment]
The bot block is scheduled to be fixed soon™ I believe.  The solution will be to make it so an editor can approve the PR when it is changing status and the bot will unblock at that point.

**Pull request merged**
