### PR TITLE
Update EIP-5380: Move to Review

### PR DESCRIPTION
**Pull request by Pandapip1**

### CODE REVIEW

**Comment by sangnguyen696969** [comment]
> jp8263

**Comment by sangnguyen696969** [comment]
> @sangnguyen696969

**Review by SamWilsn — COMMENTED** [review]
Please compute the interface ids and mention them in the proposal.

Are you okay moving into review without the security considerations section filled out?

**Comment by Pandapip1** [comment]
> Are you okay moving into review without the security considerations section filled out?

Thanks for reminding me. I'll fix that.

**Comment by Pandapip1** [comment]
For some reason GitHub isn't showing this branch. I'm going to create a new PR.

**Pull request closed without merging**
