### PR TITLE
Adjustment Interval

### PR DESCRIPTION
**Pull request by jlogelin**
Cleaned up presentation code and added adjustment interval getter to base interface

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 918 requires approval from one of (jlogelin@fas.harvard.edu, mgs33@cornell.edu, admin@0xbitcoin.org)

**Comment by jlogelin** [comment]
@Arachnid Any suggestions to get this bot to play nice with me?

**Comment by Arachnid** [comment]
FYI, the bot isn't merging your PR because your email address isn't published on your Github profile, so it doesn't know it's you.

**Comment by jlogelin** [comment]
Yeah I realized that after I pinged you. Thanks
Jay

**Pull request merged**
