### PR TITLE
Remove misformatted requires field on EIPs 2711 & 2718

### PR DESCRIPTION
**Pull request by lightclient**
Current output of `.travis-ci.sh`:

```console
Warning: EIPS/eip-2711.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x000055bc8db14370>
Warning: EIPS/eip-2718.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x000055bc8dab6860>
```

### CODE REVIEW

**Comment by lightclient** [comment]
@MicahZoltu this PR fixes a warning caused by EIP-2711 and EIP-2718 that is appearing in CI. Thanks.

```
Warning: EIPS/eip-2711.md 	 undefined method `requires (*optional)=' for #<EipValidator::Validator:0x00000001801f00>
Warning: EIPS/eip-2718.md 	 undefined method `requires (*optional)=' for #<EipValidator::Validator:0x000000017f0340>
```

**Comment by MicahZoltu** [comment]
Someone should probably update the template to have the optionality in a comment rather than inline like that, I just started with the template and edited things, it wasn't clear that I shouldn't include optional!

**Comment by MicahZoltu** [comment]
I approve this change, but I'm not an editor so I cannot merge.  cc @gcolvin

**Comment by lightclient** [comment]
You're right, it isn't clear and should be updated. I'm also surprised that the automerger won't merge this with you approval, since it nothing of substance is being changed.

**Comment by MicahZoltu** [comment]
I believe it won't auto-merge because the EIPs are final.

**Comment by MicahZoltu** [comment]
Oh, I guess it will.  I just had to approve!

**Comment by lightclient** [comment]
I think you're confusing 2711 & 2718 for 2696 & 2700 -- I wish 2711 & 2718 were final!

**Pull request merged**
