### PR TITLE
Update EIP statuses

### PR DESCRIPTION
**Pull request by lightclient**
I'm updating EIP statuses according to #2996. The mappings are as follows:

```
Draft => Draft
Last Call => Last Call
Accepted => Final
Final => Final
Superseded => Final
Abandoned => Withdrawn
Rejected => Withdrawn
Active => Living
```

### CODE REVIEW

**Comment by lightclient** [comment]
cc: @axic @MicahZoltu @Souptacular

**Comment by MicahZoltu** [comment]
Going to merge this since we have already discussed it at length and I *suspect* (based on history) no one else will comment.  It touches fairly few files, so if we decide we want to rollback later we can pretty easily.

**Comment by MicahZoltu** [comment]
Oops, just after clicking merge I realized that `Accepted => Review` is what it should have been.  I'll get that fixed.

**Comment by edsonayllon** [comment]
Are we not using Stagnant anymore? Because `Abandoned` would be `Stagnant`.

**Comment by MicahZoltu** [comment]
I believe we only had Abandoned previously, and I *believe* that previous to now we have never marked an EIP as Abandoned except when the author requested/supported it.  Would probably be valuable to go through and check the PRs that changed each of these to Abandoned and verify that is the case though.

**Comment by MicahZoltu** [comment]
I just verified all of them were moved to Abandoned by the author, so I believe Withdrawn is correct here.

**Comment by lightclient** [comment]
I guess my understanding if ProgPow's status was that it was fully specified and ready to be included in a hard fork if it were decided by the core developers necessary. In which case, I believe the appropriate status is `Final`.

**Comment by MicahZoltu** [comment]
I'm *really* hesitant to automatically move anyone's EIP into Final without their consent, since they lose the ability to make normative changes at that point.

**Comment by edsonayllon** [comment]
Yeah, I think `Review` is more appropriate for now, unless Greg wants it in `Final`.

**Pull request merged**
