### PR TITLE
typo: add missing )

### PR DESCRIPTION
**Pull request by fvictorio**

### CODE REVIEW

**Comment by alita-moore** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - eip-3521.md requires approval from one of (lightclient)
 @lightclient

**Review by lightclient — APPROVED** [review]

**Review by alita-moore — COMMENTED** [review]
testing bot

**Review by Kalliingi — COMMENTED** [review]
EIPS/eip-3521.md

**Comment by Kalliingi** [comment]
- [ ] > EIPS/eip-3521.md

**Pull request merged**
