### PR TITLE
EIP-3675: move to Final

### PR DESCRIPTION
**Pull request by mkalinin**

### CODE REVIEW

**Review by Pandapip1 — APPROVED** [review]
@SamWilsn it looks like we've got a circular dependency problem. I'm going to add this to the manual merge queue.

**Comment by axic** [comment]
2982 should also be finalised 👀

**Comment by mkalinin** [comment]
> 2982 should also be finalised 👀

сс @djrtwo

**Review by djrtwo — APPROVED** [review]
lgtm

**Review by xinbenlv — APPROVED** [review]

**Comment by SamWilsn** [comment]
@eth-bot rerun

**Pull request merged**
