### PR TITLE
Update EIP-7495: Allow setting properties in `StableContainer` impl

### PR DESCRIPTION
**Pull request by etan-status**

### CODE REVIEW

**Comment by etan-status** [comment]
Errors don't have anything to do with this PR. Maybe the eth-bot stuff is broken when only `assets` but no `.md` files are modified :-)

**Comment by etan-status** [comment]
Ah, seems to just be the e-consensus tag that's a bit weird when not touching `.md`. The HTMLProofer issue seems to stem from the split into ERC.

**Comment by etan-status** [comment]
@eth-bot rerun

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by g11tech** [comment]
i think someone needs to rectify `eip-6358` for the htmlproofer to pass

**Comment by etan-status** [comment]
> i think someone needs to rectify `eip-6358` for the htmlproofer to pass

Seems to be related to https://github.com/ethereum/ERCs/pull/40

The ERCs repo is a bit weird, it has `assets/erc-XYZ` folders, but most references seem to be for `../assets/eip-XYZ` (eip instead of erc). The 6358 ref seems to have been changed to point to `erc` and now it breaks here.

@Pandapip1 maybe some insight?

**Comment by etan-status** [comment]
- https://github.com/ethereum/ERCs/pull/133

**Review by g11tech — APPROVED** [review]

**Pull request merged**
