### PR TITLE
Update EIPs to follow the rules regarding EVM opcodes (as stated in EIP-1)

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 1014 is in state Final, not Draft or Last Call
 - EIP 1052 is in state Final, not Draft or Last Call
 - EIP 1283 is in state Final, not Draft or Last Call
 - EIP 1051 requires approval from one of (@arachnid)
 - EIP 1087 requires approval from one of (@arachnid)
 - EIP 1109 requires approval from one of (@jbaylina)
 - EIP 1153 requires approval from one of (@alexeyakhunov)
 - EIP 1285 requires approval from one of (adam@daostack.io, ben@daostack.io)

**Review by MicahZoltu — APPROVED** [review]
I'm a fan of improving stylistic consistency, and I think including the opcode number along with the name is valuable.

**Comment by axic** [comment]
@MicahZoltu feel free to merge if happy with this. I'm sure in the past 6 months there are many more examples now, but I won't attempt at fixing those.

**Comment by MicahZoltu** [comment]
Sorry, I forgot that you are philosophically against merging ones own PRs.  😁 I approved without merging specifically so that you could merge yourself since that is what I prefer for my PRs.

**Pull request merged**
