### PR TITLE
ercs past last call deadline to Final

### PR DESCRIPTION
**Pull request by wschwab**
This PR sets 5 ERCs past their Last Call deadline to Final (173, 1191, 1967, 2266, and 2535).

Pinging authors to approve:

- 173: @mudgen @danfinlay 
- <del>1191: @juli </del>
- <del>1967: @spalladino @frangio </del>
- <del> 2266: will try to add later, unsure </del>
- 2535: @mudgen

I'll crossthrough EIPs which have been approved

### CODE REVIEW

**Review by spalladino — APPROVED** [review]

**Comment by wschwab** [comment]
2266: @HAOYUatHZ (please approve this PR so we can make your EIP Final)

**Review by HAOYUatHZ — APPROVED** [review]

**Comment by mudgen** [comment]
Approved on eip-2535.   I just made the last change on eip-173 and the pull request was merged.

**Review by juli — APPROVED** [review]

**Comment by wschwab** [comment]
@mudgen I hadn't noticed, but you need to approve through the Github interface. Look at the PR tab (on this page, towards the top, but under the generic Github tabs) which should have tabs for "Conversations" (that's this), "Commits", "Checks", and "Files Changed". If you go to "Files Changed", you'll see a green button for starting a review.

One of the options in the review will be "Approve". I'll need you to select that.

**Comment by mudgen** [comment]
@wschwab Understand, done.

**Comment by wschwab** [comment]
looking through the bot, it looks like either @sebastianelvis or @jiangshan-yu (not @HAOYUatHZ like I originally thought) need to approve 2266 - can one of you please approve this PR so we can set it to Final?

**Review by SebastianElvis — APPROVED** [review]

**Comment by MicahZoltu** [comment]
Please re-open this as 5 separate PRs.  All in one breaks the bot, makes it much harder to track discussions and approvals, and kinda messes up history and issue tracking.

Sorry!

**Comment by wschwab** [comment]
I lost track of this, will do

**Pull request closed without merging**
