### PR TITLE
Update EIP-4906: Move Status to Final

### PR DESCRIPTION
**Pull request by emojidao**
EIP-4906: Move Status to Final

### CODE REVIEW

**Review by 0xanders — APPROVED** [review]

**Comment by Pandapip1** [comment]
@0xanders I made a few changes (typos + fixes + formatting errors). Could you make sure that the changes I've made are correct?

**Comment by 0xanders** [comment]
> @0xanders I made a few changes (typos + fixes + formatting errors). Could you make sure that the changes I've made are correct?

thank you!

**Review by 0xanders — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]

**Comment by pcaversaccio** [comment]
Can someone quickly elaborate on how the `interfaceId` was exactly calculated here (since no functions are present within the interface)?

**Comment by Pandapip1** [comment]
It was chosen arbitrarily IIUC.

**Comment by pcaversaccio** [comment]
Ok thx @Pandapip1.

**Pull request merged**
