### PR TITLE
EIP-2569: move to "Review"

### PR DESCRIPTION
**Pull request by lemontreeran**
Move EIP-2569 from "Draft" to "Review" to continue the review process

### CODE REVIEW

**Review by lightclient — CHANGES_REQUESTED** [review]
Please add the required `Security Considerations" section.

**Comment by Sawanee250825** [comment]
> ตรวจ

**Comment by zhous** [comment]
Acutally we're still working on this EIP, and we may modify it in May.

**Comment by MicahZoltu** [comment]
Once you are ready to iterate some more just submit another PR.

**Pull request closed without merging**
