### PR TITLE
Updating ERC-721 JSON schema spec to include two new optional fields

### PR DESCRIPTION
**Pull request by jamesmorgan**
This a proposal to enhance the `ERC721 Metadata JSON Schema` defined in https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md 

The proposal covers 2 new fields, both fields are used by existing applications and marketplaces in some form but are not currently covered by the existing Metadata JSON schema.

The first field is `external_uri` - a field similar to this is already used in applications like https://trustwalletapp.com/ and on marketplaces such as https://opensea.io/ however they follow a slightly different naming convention of `externalUrl`. see: https://opensea.readme.io/docs/2-adding-metadata The purpose of these attributes would be to allow 3rd parties who are consuming and displaying ERC-721 to allow them to link back to the original place the token was purchased or ownership was transferred e.g. the original marketplace.

The second field is `attributes` which is also used by https://opensea.io/ (see above opensea link). The purpose of these attributes would be to allow 3rd parties who are consuming and displaying ERC-721 tokens to quickly classified/filter/search tokens based on these attributes. 

Both these fields are optional as they are not required as a minimum in my opinion for a valid ERC-721 token, also the token may not have an originating URI to link back to and or required a set of attributes to define it. 

Let me know your thoughts. 

The Updated JSON schema would look something like this:

```
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents",
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents",
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive.",
        },
        "external_uri": {
            "type": "string",
            "description": "A URI pointing to a a externally hosted resources, usually the originating market place. Allows for 3rd party services to link to the originally NFT.",
            "required": false
        },
        "attributes": {
            "type": "object",
            "description": "Defines a set of attributes which classifies and defines the NFT. Allows for applications to build fitlers and attribute search functionalities for a set of NFTs.",
            "required": false
        }
    }
}
```

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 721 requires approval from one of (nastassia.sachs@protonmail.com, @fulldecent, @dete, @dekz)

**Comment by fulldecent** [comment]
The `external_uri` name could be more descriptive. Your current rationale is to point to a marketplace. However ERC-721s can be traded on multiple marketplaces at the same time. It may be nice for some applications to 

The `attributes` is an additional level of name spacing that is unnecessary. Anything that could be stored under `attributes` could more simply be stored directly under the root object.

Thanks for sharing. Do you represent any of the projects mentioned above?

---

There are MANY use cases for 721, I do not think this proposed addition is applicable for a majority, or even a significant portion of use cases. But as time goes on we will all learn more about whether or not that is true.

I would like to pass on this to the standard and reevaluate in a year or so as many more implementations hit mainnet. It is simple enough for applications to adopt this proprietary extension. The risk is that they chose `external_uri` but then later everyone else chooses `externaluri` or something. But luckily, nearly all implementations are using off-chain metadata, which means that if there is appetite to standardize this then everybody can quickly adopt the standard without much cost.

**Comment by andygray** [comment]
@fulldecent I work with @jamesmorgan on knownorigin.io - we implemented the ERC721 for our application but we want to take advantage of the secondary marketplaces. In essence the `external_uri` it a link back to originating source of the ERC721 token where you can see it how the implementors intended.

Maybe this should be `host_uri` or something to allow consumers to re-direct to the original source. The danger is that all implementation have a different name for this common requirement. A couple of optional properties could lead the way going forward?

`attributes` just allows generic "tags" to be added in a standard manner. 

@fulldecent thanks for the reply we are keen to help evolve the standard so any thoughts/feedback is valid.

**Comment by jamesmorgan** [comment]
Hi @fulldecent, I don't represent any of the above, its just something I have noticed when getting our project (http://knownorigin.io/) added to OpenSea and TrustWallet. 

Regrading `attributes` I think keeping this contained under a separate property is beneficial and cleaner than simply listing these out under the root object. Group attributes together also defineds scope and usage better than placing under the root object.

Agreed `external_uri` may not be applicable to all, my thoughts on this is than in most cases a single entity would be responsible for minting the original token, this would provide a mechanism to link back to this entity.  

I think that if something like this isn't standardised then there will be lots of 721 metadatas which implement something similar but all different, reducing the synergy within the 721 ecosystem and making it harder for applications/services/marketplaces etc to integrate various tokens to different standards.

**Comment by fulldecent** [comment]
To be clear, metadata is application specific. The attributes of a cryptokitties are not compatible with a cryptofighter. I expect many types of incompatible metadata. This is a design goal.

In the standard we have discussed connecting assets/debts/property to wallets/auctions/exchanges. The standard did NOT consider synergy between different types of assets etc. as considered above.

It is perfectly OK for OpenSea to add requirements over the top. But those will only apply to digital assets for sale on OpenSea. There are MANY types of digital assets even.

When the actual problems start happening then I will be happy to review and start considering solutions. There is minimal benefit of forethought in this space.

**Comment by jamesmorgan** [comment]
I understand your points, fair enough and thanks for the feedback. 

Just so I explain myself better if this is reviewed in the future. I'm not proposing `attributes` to be standardised across the board, in-fact the opposite. These attributes can be defined by the original creators and are unique to the set/type/individual token, for example it would be expected that cryptokitties would have a different set of attributes to cryptofighter, as would a debt token would have a different set of attributes to a piece of artwork.

Thanks for your feedback on this subject 👍

**Comment by jamesmorgan** [comment]
I have a branch on a fork which details some of these and adds them to 1047 standard originally merged in here https://github.com/ethereum/EIPs/pull/1047

* https://github.com/jamesmorgan/EIPs/tree/eip-1047-optional-properties

Further discussions can be seen on here: https://www.reddit.com/r/raredigitalart/comments/8hfk2a/token_metadata_json_schema_eip_1047/

**Comment by jamesmorgan** [comment]
closing due to the new PR https://github.com/ethereum/EIPs/pull/1071

**Pull request closed without merging**
