### PR TITLE
Update EIP-4844: Clarify type for better readability

### PR DESCRIPTION
**Pull request by xinbenlv**

### CODE REVIEW

**Review by protolambda — APPROVED** [review]

**Comment by xinbenlv** [comment]
Thanks! I also asked a few technical questions on the FEM discussion thread, look forward to having more discussions with the 4844 author group.

**Review by Coretaker101 — COMMENTED** [review]
Now what do o do

**Comment by Coretaker101** [comment]
I'm confused because everything I'm reading is like I run a business and I do not

**Comment by YaroslavPysanskyi** [comment]
Pool request

**Pull request merged**
