### PR TITLE
Update EIP-2535

### PR DESCRIPTION
**Pull request by mudgen**
@lightclient, @Pandapip1, @SamWilsn,  please merge this pull request. It makes some necessary changes to EIP2535 Diamonds, to make it conform better to EIP-1. It fixes the order of the EIP headers, and adds a description header, and changes the discussion link.

### CODE REVIEW

**Comment by mudgen** [comment]
@lightclient please merge this pull request.  It makes some necessary changes to EIP2535 Diamonds, to make it conform better to EIP-1.  It fixes the order of the EIP headers, and adds a description header.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Please update this to the current EIP format, then it will be automatically merged.

**Comment by mudgen** [comment]
> Please update this to the current EIP format, then it will be automatically merged.

@Pandapip1 I understand that, but that will require a great many more changes that I can't do right now.  This pull request will update the currently published EIP2535 to make it comply with more of the EIP formatting. Can you please merge this pull request to update the currently published EIP2535 so it complies with more of the required formatting?

**Comment by Pandapip1** [comment]
> @Pandapip1 I understand that, but that will require a great many more changes that I can't do right now. This pull request will update the currently published EIP2535 to make it comply with more of the EIP formatting. Can you please merge this pull request to update the currently published EIP2535 so it complies with more of the required formatting?

I cannot. @SamWilsn can.

**Comment by xinbenlv** [comment]
Hi @mudgen you seem to created 4 PRs #5513  #5512 #5511 #5510 that are duplicates of each other for the same EIP-2535,  may I suggest you first close all other PRs so as to give editors a better idea of which one to focus on reviewing?

**Comment by mudgen** [comment]
> Hi @mudgen you seem to created 4 PRs #5513 #5512 #5511 #5510 that are duplicates of each other for the same EIP-2535, may I suggest you first close all other PRs so as to give editors a better idea of which one to focus on reviewing?

@xinbenlv Yes, I closed the other pull requests.  Thanks for this suggestion.

**Comment by xinbenlv** [comment]
Cool thank you. Could you continue to revise this PR to fix all lint errors and then leave a comment when it's ready for a next round of review?

> > Hi @mudgen you seem to created 4 PRs #5513 #5512 #5511 #5510 that are duplicates of each other for the same EIP-2535, may I suggest you first close all other PRs so as to give editors a better idea of which one to focus on reviewing?
> 
> @xinbenlv Yes, I closed the other pull requests. Thanks for this suggestion.

**Comment by mudgen** [comment]
> Cool thank you. Could you continue to revise this PR to fix all lint errors and then leave a comment when it's ready for a next round of review?
> 
> > > Hi @mudgen you seem to created 4 PRs #5513 #5512 #5511 #5510 that are duplicates of each other for the same EIP-2535, may I suggest you first close all other PRs so as to give editors a better idea of which one to focus on reviewing?
> > 
> > 
> > @xinbenlv Yes, I closed the other pull requests. Thanks for this suggestion.

No but merging this pull request will improve the current published version of this EIP.  
See this this comment: https://github.com/ethereum/EIPs/pull/5513#issuecomment-1221582176

**Comment by xinbenlv** [comment]
Thanks for the response.

I think the current policy on merging PR for non-Final EIPs requires fixing lint errors. While I personally disagree with such policy and share you view on merging them improve the EIP, it would unfortunately likely delay your merge if lint errors werent fixed. Again, to be clear I am not a fan of such policy but it seems the way it is enforced right now.

**Comment by mudgen** [comment]
@xinbenlv Understood and thanks. I am willing to wait for @SamWilsn to merge it.

**Review by Pandapip1 — APPROVED** [review]
I've decided that I'm in favor of these changes. CC @SamWilsn

**Comment by mudgen** [comment]
> I've decided that I'm in favor of these changes. CC @SamWilsn

@SamWilsn Can you please merge this pull request?

**Comment by SamWilsn** [comment]
I've created https://github.com/mudgen/EIPs/pull/1 with my editorial and technical reviewer suggestions. They're both mixed, sorry about that :sweat_smile:

**Pull request closed without merging**
