### PR TITLE
Update EIP-3091: Move to Draft

### PR DESCRIPTION
**Pull request by ligi**
Polish and Resurrect EIP3091
This EIP is used and did a good job aligning block explorers to use the same routes - it should not be stagnant but move to Final finally.

### CODE REVIEW

**Comment by pedrouid** [comment]
LGTM 👍 Can we just first add all 3 suggested changes bt @SamWilsn ?

**Review by SamWilsn — APPROVED** [review]

**Comment by SamWilsn** [comment]
Just need an approval from @pedrouid

**Comment by ligi** [comment]
wait a bit - also want to address your Rationale/Motivation suggestion - but this needs a bit more thought than the other 2 suggestions that I could merge in passing.

**Comment by ligi** [comment]
@pedrouid / @SamWilsn - from my side it would be mergeable now

**Review by Pandapip1 — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]
Pretty sure I approved this already

**Comment by Pandapip1** [comment]
Oh. Indeed I did.

Waiting on @pedrouid

**Comment by Pandapip1** [comment]
@SamWilsn what do you think about overriding author approval here? They seem to be unreachable.

**Review by pedrouid — APPROVED** [review]
👍

**Pull request merged**
