### PR TITLE
mark EIP-1153 as review

### PR DESCRIPTION
**Pull request by moodysalem**

### CODE REVIEW

**Comment by Pandapip1** [comment]
@MicahZoltu are external links to eth magicians allowed?

**Review by MicahZoltu — CHANGES_REQUESTED** [review]
External link in Security Considerations should be removed.  I recommend extracting the critical information from that thread and including it in the EIP directly.

Otherwise this looks good to move to Review.

**Comment by MicahZoltu** [comment]
Good catch @Pandapip1!

**Comment by Pandapip1** [comment]
Test cases should be removed until there is text

**Comment by Pandapip1** [comment]
I've suggested a few changes: #4947

**Comment by moodysalem** [comment]
> * There are missing `requires` in the header

This header is optional according to eip-template.md

I've approved changes from @Pandapip1 and added some small language nits/some additional context to security considerations to this PR

**Comment by Pandapip1** [comment]
> This header is optional according to eip-template.md

It's optional because not every EIP references other EIPs. If you reference an EIP, you should put the header in.

**Review by MicahZoltu — APPROVED** [review]

**Pull request merged**
