### PR TITLE
Website: Autogenerated directory listings

### PR DESCRIPTION
**Pull request by Pandapip1**
Allows for autogenerated directory listings with minimal hassle.

### CODE REVIEW

**Comment by Pandapip1** [comment]
More tweaks might be needed... 😬

**Comment by xinbenlv** [comment]
Thanks for working on this! Can you share a link to demo?

**Comment by Pandapip1** [comment]
> Thanks for working on this! Can you share a link to demo?

No. It doesn't work yet 😆

**Comment by Pandapip1** [comment]
Rerunning CI to see what the problem is

**Pull request closed without merging**
