### PR TITLE
Add Webchain chain id

### PR DESCRIPTION
**Pull request by lukaszmatczak**
Please add Webchain chain id (101)
https://github.com/webchain-network/webchaind

### CODE REVIEW

**Comment by bmann** [comment]
I don't think other chains are accepted into that EIP at this point.

See https://chainid.network/ and https://github.com/ethereum-lists/chains for a larger list of maintained chains, that you are welcome to file a PR against.

**Comment by hackmod** [comment]
See also https://github.com/MetaMask/metamask-extension/issues/1820#issuecomment-394573130

**Comment by lukaszmatczak** [comment]
OK. Thank you for the links.

**Comment by hackmod** [comment]
See also https://github.com/ethereum-lists/chains/pull/10

**Comment by lukaszmatczak** [comment]
@gcolvin If it can't be merged then I have no choice I think.

**Pull request closed without merging**
