### PR TITLE
Corrected wrong hex value in EIP-145

### PR DESCRIPTION
**Pull request by cburgdorf**
The value `0x100` in test case 16 of the SAR test cases is supposed to mean `0x0100`

### CODE REVIEW

**Comment by axic** [comment]
@Arachnid @Souptacular can be merged

**Comment by axic** [comment]
@cburgdorf if you rebase or click the update branch button it should automerge given one of the authors (me) have approved.

**Comment by cburgdorf** [comment]
@axic for some reason CI seems to be stuck in limbo forever

**Comment by axic** [comment]
It just takes 4-6 hours to start for some reason.

**Pull request merged**
