### PR TITLE
Remove Mist from EIP-55 as it is deprecated

### PR DESCRIPTION
**Pull request by ligi**
context: 

Selection_042

https://medium.com/@avsa/sunsetting-mist-da21c8e943d2

### CODE REVIEW

**Comment by nicksavers** [comment]
For historic purposes it might be good?

**Comment by axic** [comment]
@ligi are you still pursuing this? If not, can you please close?

**Comment by ligi** [comment]
I still think this should be removed

**Comment by MicahZoltu** [comment]
I would prefer to remove the entire Adoption section (and References too while we are in there mucking around) to bring this EIP more in line with our current EIP standards.  This EIP was created back when the EIPs repository was used for hard fork coordination, and one of the many reasons we have moved away from that is that maintaining these lists is too much work and out of scope of editors.

**Comment by ligi** [comment]
I would also be OK with removing all of them - but leave this PR as it is. IMHO it should still be merged.

**Comment by MicahZoltu** [comment]
Created https://github.com/ethereum/EIPs/pull/3092 as an alternative, I'm OK with either.  I would accept *either* author sign-off **OR** editor sign-off for the change that removes the whole section, but I think I would want author sign-off alone for a change that just edits a section.

The reason for this is because I feel like removing a section is just bringing an old EIP in line with modern standards, while editing a section is more like making a non-normative change to an existing EIP that has an owner.

**Review by lightclient — APPROVED** [review]

**Comment by lightclient** [comment]
This PR looks good to me and agree that it is non-normative.

**Pull request closed without merging**
