### PR TITLE
Replace question with suggestion

### PR DESCRIPTION
**Pull request by ligi**
Just implementing this EIP client side and think it is not nice to have such a question in the standard. Would like to replace with  this suggestion (hence SHOULD not MUST) - for making it a MUST it might already be to late as people might already prefixed with an @. I think it is better to not have the @ as it is redundant and just bloates state.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP 634 requires approval from one of (me@ricmoo.com)

**Comment by axic** [comment]
@ricmoo please review

**Comment by ricmoo** [comment]
Yes, it looks good to me. Is there a button somewhere to automatically approve? Or is this comment sufficient? :)

**Comment by ligi** [comment]
@ricmoo great - AFAIK you just need to do a normal github review approval for the bot to pick it up

**Comment by axic** [comment]
@ricmoo it seems the email address you have used in the EIP is not under your github account so the automerger can't pick up your approval. Or the automerger is off. You can alternatively use a github username in the EIP.

**Comment by ricmoo** [comment]
Thanks. I'll switch to using GitHub user names from now on. Too many e-mail addresses. :)

**Pull request merged**
