### PR TITLE
add temporal replay protection

### PR DESCRIPTION
**Pull request by holiman**
This PR adds an EIP about temporal replay protection, basically `valid-until` in the form of a timestamp to transactions.

### CODE REVIEW

**Comment by axic** [comment]
It may make sense to have a look at #599, which seems to be similar, and has some discussions.

**Comment by holiman** [comment]
Oh thanks @axic , I vaguely recalled there being something like it already, but didn't find it. It differs a bit, though, since this one uses timestamp instead of block numbers, to make it more 'sane' from the perspective of an offline signer. I'll add it as a reference though.

**Comment by jvluso** [comment]
We should include that the address of a contract created by an EOA in a transaction with replay protection depends on the valid-until date in addition to depending on the nonce so that once dust account removal starts, contracts cannot be redeployed at the same address after being self destructed.

**Comment by moodysalem** [comment]
Can we make this EIP more user-friendly? 'temporal replay protection' sounds a lot more complicated, and it sounds like it is security related similar to the replay protection EIP, vs. 'transaction deadlines' which is just a badly needed UX feature

**Pull request merged**
